// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: acl.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const addGroupPermission = `-- name: AddGroupPermission :exec
INSERT INTO group_permissions (group_id, permission_id, created_at, updated_at)
VALUES (?, ?, NOW(), NOW())
`

type AddGroupPermissionParams struct {
	GroupID      int64 `json:"group_id"`
	PermissionID int64 `json:"permission_id"`
}

func (q *Queries) AddGroupPermission(ctx context.Context, arg AddGroupPermissionParams) error {
	_, err := q.db.ExecContext(ctx, addGroupPermission, arg.GroupID, arg.PermissionID)
	return err
}

const addUserToGroup = `-- name: AddUserToGroup :exec
INSERT INTO user_groups (user_id, group_id, created_at, updated_at)
VALUES (?, ?, NOW(), NOW())
`

type AddUserToGroupParams struct {
	UserID  int64 `json:"user_id"`
	GroupID int64 `json:"group_id"`
}

func (q *Queries) AddUserToGroup(ctx context.Context, arg AddUserToGroupParams) error {
	_, err := q.db.ExecContext(ctx, addUserToGroup, arg.UserID, arg.GroupID)
	return err
}

const createGroup = `-- name: CreateGroup :execresult
INSERT INTO usergroup (groupname, groupdescrip, created_at, updated_at)
VALUES (?, ?, NOW(), NOW())
`

type CreateGroupParams struct {
	Groupname    string `json:"groupname"`
	Groupdescrip string `json:"groupdescrip"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createGroup, arg.Groupname, arg.Groupdescrip)
}

const createPermission = `-- name: CreatePermission :execresult
INSERT INTO acl_permissions (permission_name, permission_desc, created_at, updated_at)
VALUES (?, ?, NOW(), NOW())
`

type CreatePermissionParams struct {
	PermissionName string `json:"permission_name"`
	PermissionDesc string `json:"permission_desc"`
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPermission, arg.PermissionName, arg.PermissionDesc)
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM usergroup WHERE id = ?
`

func (q *Queries) DeleteGroup(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, id)
	return err
}

const deletePermission = `-- name: DeletePermission :exec
DELETE FROM acl_permissions WHERE id = ?
`

func (q *Queries) DeletePermission(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePermission, id)
	return err
}

const getGroup = `-- name: GetGroup :one
SELECT id, groupname, groupdescrip, created_at, updated_at
FROM usergroup
WHERE id = ?
`

type GetGroupRow struct {
	ID           int64     `json:"id"`
	Groupname    string    `json:"groupname"`
	Groupdescrip string    `json:"groupdescrip"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) GetGroup(ctx context.Context, id int64) (GetGroupRow, error) {
	row := q.db.QueryRowContext(ctx, getGroup, id)
	var i GetGroupRow
	err := row.Scan(
		&i.ID,
		&i.Groupname,
		&i.Groupdescrip,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupPermissions = `-- name: GetGroupPermissions :many

SELECT p.id, p.permission_name, p.permission_desc
FROM group_permissions gp
JOIN acl_permissions p ON gp.permission_id = p.id
WHERE gp.group_id = ?
ORDER BY p.permission_name
`

type GetGroupPermissionsRow struct {
	ID             int64  `json:"id"`
	PermissionName string `json:"permission_name"`
	PermissionDesc string `json:"permission_desc"`
}

// Group-Permission Assignments
func (q *Queries) GetGroupPermissions(ctx context.Context, groupID int64) ([]GetGroupPermissionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupPermissions, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupPermissionsRow
	for rows.Next() {
		var i GetGroupPermissionsRow
		if err := rows.Scan(&i.ID, &i.PermissionName, &i.PermissionDesc); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPermission = `-- name: GetPermission :one
SELECT id, permission_name, permission_desc, created_at, updated_at
FROM acl_permissions
WHERE id = ?
`

type GetPermissionRow struct {
	ID             int64     `json:"id"`
	PermissionName string    `json:"permission_name"`
	PermissionDesc string    `json:"permission_desc"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) GetPermission(ctx context.Context, id int64) (GetPermissionRow, error) {
	row := q.db.QueryRowContext(ctx, getPermission, id)
	var i GetPermissionRow
	err := row.Scan(
		&i.ID,
		&i.PermissionName,
		&i.PermissionDesc,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPermissions = `-- name: GetUserPermissions :many

SELECT DISTINCT p.permission_name
FROM user_groups ug
JOIN group_permissions gp ON ug.group_id = gp.group_id
JOIN acl_permissions p ON gp.permission_id = p.id
WHERE ug.user_id = ?
ORDER BY p.permission_name
`

// User Permission Check (for authorization)
func (q *Queries) GetUserPermissions(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getUserPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission_name string
		if err := rows.Scan(&permission_name); err != nil {
			return nil, err
		}
		items = append(items, permission_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many

SELECT id, groupname, groupdescrip, created_at, updated_at
FROM usergroup
ORDER BY groupname
`

type ListGroupsRow struct {
	ID           int64     `json:"id"`
	Groupname    string    `json:"groupname"`
	Groupdescrip string    `json:"groupdescrip"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

// Groups
func (q *Queries) ListGroups(ctx context.Context) ([]ListGroupsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupsRow
	for rows.Next() {
		var i ListGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Groupname,
			&i.Groupdescrip,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissions = `-- name: ListPermissions :many

SELECT id, permission_name, permission_desc, created_at, updated_at
FROM acl_permissions
ORDER BY permission_name
`

type ListPermissionsRow struct {
	ID             int64     `json:"id"`
	PermissionName string    `json:"permission_name"`
	PermissionDesc string    `json:"permission_desc"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

// Permissions
func (q *Queries) ListPermissions(ctx context.Context) ([]ListPermissionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPermissionsRow
	for rows.Next() {
		var i ListPermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.PermissionName,
			&i.PermissionDesc,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGroups = `-- name: ListUserGroups :many

SELECT ug.group_id, g.groupname, g.groupdescrip
FROM user_groups ug
JOIN usergroup g ON ug.group_id = g.id
WHERE ug.user_id = ?
ORDER BY g.groupname
`

type ListUserGroupsRow struct {
	GroupID      int64  `json:"group_id"`
	Groupname    string `json:"groupname"`
	Groupdescrip string `json:"groupdescrip"`
}

// User-Group Assignments
func (q *Queries) ListUserGroups(ctx context.Context, userID int64) ([]ListUserGroupsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserGroupsRow
	for rows.Next() {
		var i ListUserGroupsRow
		if err := rows.Scan(&i.GroupID, &i.Groupname, &i.Groupdescrip); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGroupPermission = `-- name: RemoveGroupPermission :exec
DELETE FROM group_permissions
WHERE group_id = ? AND permission_id = ?
`

type RemoveGroupPermissionParams struct {
	GroupID      int64 `json:"group_id"`
	PermissionID int64 `json:"permission_id"`
}

func (q *Queries) RemoveGroupPermission(ctx context.Context, arg RemoveGroupPermissionParams) error {
	_, err := q.db.ExecContext(ctx, removeGroupPermission, arg.GroupID, arg.PermissionID)
	return err
}

const removeUserFromGroup = `-- name: RemoveUserFromGroup :exec
DELETE FROM user_groups
WHERE user_id = ? AND group_id = ?
`

type RemoveUserFromGroupParams struct {
	UserID  int64 `json:"user_id"`
	GroupID int64 `json:"group_id"`
}

func (q *Queries) RemoveUserFromGroup(ctx context.Context, arg RemoveUserFromGroupParams) error {
	_, err := q.db.ExecContext(ctx, removeUserFromGroup, arg.UserID, arg.GroupID)
	return err
}

const updateGroup = `-- name: UpdateGroup :exec
UPDATE usergroup
SET groupname = ?, groupdescrip = ?, updated_at = NOW()
WHERE id = ?
`

type UpdateGroupParams struct {
	Groupname    string `json:"groupname"`
	Groupdescrip string `json:"groupdescrip"`
	ID           int64  `json:"id"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) error {
	_, err := q.db.ExecContext(ctx, updateGroup, arg.Groupname, arg.Groupdescrip, arg.ID)
	return err
}

const userHasPermission = `-- name: UserHasPermission :one
SELECT COUNT(*) > 0 AS has_permission
FROM user_groups ug
JOIN group_permissions gp ON ug.group_id = gp.group_id
JOIN acl_permissions p ON gp.permission_id = p.id
WHERE ug.user_id = ? AND p.permission_name = ?
`

type UserHasPermissionParams struct {
	UserID         int64  `json:"user_id"`
	PermissionName string `json:"permission_name"`
}

func (q *Queries) UserHasPermission(ctx context.Context, arg UserHasPermissionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, userHasPermission, arg.UserID, arg.PermissionName)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}
