// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: action_items.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const billingActionItems = `-- name: BillingActionItems :many
SELECT 'unpaid_claim' AS action_type,
       cl.id AS ref_id,
       CONCAT('Claim #', cl.id, ' for patient ', p.ptlname) AS description,
       cl.cltimestamp AS action_date,
       pr.procbalcurrent AS amount
FROM claimlog cl
LEFT JOIN procrec pr ON cl.clprocedure = pr.id
LEFT JOIN patient p ON pr.procpatient = p.id
WHERE pr.procbalcurrent > 0 AND pr.active = 'active'
UNION ALL
SELECT 'expiring_auth' AS action_type,
       a.id AS ref_id,
       CONCAT('Authorization #', a.id, ' for patient ', p.ptlname, ' expires ', DATE(a.authdtend)) AS description,
       a.authdtend AS action_date,
       0 AS amount
FROM authorizations a
LEFT JOIN patient p ON a.authpatient = p.id
WHERE a.authdtend BETWEEN CURDATE() AND DATE_ADD(CURDATE(), INTERVAL 30 DAY) AND a.active = 'active'
UNION ALL
SELECT 'unbilled_procedure' AS action_type,
       pr.id AS ref_id,
       CONCAT('Procedure ', c.cptnameext, ' for patient ', p.ptlname, ' on ', DATE(pr.procdt)) AS description,
       pr.procdt AS action_date,
       pr.proccharges AS amount
FROM procrec pr
LEFT JOIN cpt c ON pr.proccpt = c.id
LEFT JOIN patient p ON pr.procpatient = p.id
WHERE pr.procbalcurrent = pr.proccharges AND pr.proccharges > 0 AND pr.active = 'active'
ORDER BY action_date DESC
LIMIT 50
`

type BillingActionItemsRow struct {
	ActionType  string          `json:"action_type"`
	RefID       int64           `json:"ref_id"`
	Description string          `json:"description"`
	ActionDate  time.Time       `json:"action_date"`
	Amount      sql.NullFloat64 `json:"amount"`
}

func (q *Queries) BillingActionItems(ctx context.Context) ([]BillingActionItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, billingActionItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillingActionItemsRow
	for rows.Next() {
		var i BillingActionItemsRow
		if err := rows.Scan(
			&i.ActionType,
			&i.RefID,
			&i.Description,
			&i.ActionDate,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
