// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: addresses.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const deleteAddress = `-- name: DeleteAddress :exec
UPDATE patient_address
SET active = 0, updated_at = NOW()
WHERE id = ? AND patient = ?
`

type DeleteAddressParams struct {
	AddressID int64 `json:"address_id"`
	PatientID int64 `json:"patient_id"`
}

// Addresses: deactivate an address (soft delete)
func (q *Queries) DeleteAddress(ctx context.Context, arg DeleteAddressParams) error {
	_, err := q.db.ExecContext(ctx, deleteAddress, arg.AddressID, arg.PatientID)
	return err
}

const deleteAllAddresses = `-- name: DeleteAllAddresses :exec
UPDATE patient_address
SET active = 0, updated_at = NOW()
WHERE patient = ?
`

// Addresses: deactivate all addresses for a patient (bulk soft delete)
func (q *Queries) DeleteAllAddresses(ctx context.Context, patientID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAllAddresses, patientID)
	return err
}

const listAddresses = `-- name: ListAddresses :many
SELECT
  id,
  patient,
  line1,
  line2,
  city,
  stpr,
  postal,
  zip,
  active,
  created_at,
  updated_at
FROM patient_address
WHERE patient = ? AND active = 1
ORDER BY id ASC
`

type ListAddressesRow struct {
	ID        int64          `json:"id"`
	Patient   int64          `json:"patient"`
	Line1     sql.NullString `json:"line1"`
	Line2     sql.NullString `json:"line2"`
	City      sql.NullString `json:"city"`
	Stpr      sql.NullString `json:"stpr"`
	Postal    sql.NullString `json:"postal"`
	Zip       sql.NullString `json:"zip"`
	Active    bool           `json:"active"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

// Addresses: list all active addresses for a patient
func (q *Queries) ListAddresses(ctx context.Context, patientID int64) ([]ListAddressesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAddresses, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAddressesRow
	for rows.Next() {
		var i ListAddressesRow
		if err := rows.Scan(
			&i.ID,
			&i.Patient,
			&i.Line1,
			&i.Line2,
			&i.City,
			&i.Stpr,
			&i.Postal,
			&i.Zip,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAddresses = `-- name: SetAddresses :execresult
INSERT INTO patient_address (patient, line1, line2, city, stpr, postal, active)
VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  1
)
`

type SetAddressesParams struct {
	PatientID int64          `json:"patient_id"`
	Line1     sql.NullString `json:"line1"`
	Line2     sql.NullString `json:"line2"`
	City      sql.NullString `json:"city"`
	Stpr      sql.NullString `json:"stpr"`
	Postal    sql.NullString `json:"postal"`
}

// Addresses: insert a new address for a patient
func (q *Queries) SetAddresses(ctx context.Context, arg SetAddressesParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, setAddresses,
		arg.PatientID,
		arg.Line1,
		arg.Line2,
		arg.City,
		arg.Stpr,
		arg.Postal,
	)
}

const updateAddress = `-- name: UpdateAddress :exec
UPDATE patient_address
SET
  line1 = ?,
  line2 = ?,
  city = ?,
  stpr = ?,
  postal = ?,
  updated_at = NOW()
WHERE id = ? AND patient = ?
`

type UpdateAddressParams struct {
	Line1     sql.NullString `json:"line1"`
	Line2     sql.NullString `json:"line2"`
	City      sql.NullString `json:"city"`
	Stpr      sql.NullString `json:"stpr"`
	Postal    sql.NullString `json:"postal"`
	AddressID int64          `json:"address_id"`
	PatientID int64          `json:"patient_id"`
}

// Addresses: update an address for a patient
func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) error {
	_, err := q.db.ExecContext(ctx, updateAddress,
		arg.Line1,
		arg.Line2,
		arg.City,
		arg.Stpr,
		arg.Postal,
		arg.AddressID,
		arg.PatientID,
	)
	return err
}
