// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: aging.sql

package dbgen

import (
	"context"
)

const agingSummary = `-- name: AgingSummary :many
SELECT
  SUM(procbalcurrent) AS balance,
  CASE
    WHEN DATEDIFF(NOW(), procdt) < 30 THEN '0-30'
    WHEN DATEDIFF(NOW(), procdt) < 60 THEN '31-60'
    WHEN DATEDIFF(NOW(), procdt) < 90 THEN '61-90'
    ELSE '90+'
  END AS age_bucket
FROM procrec
WHERE procdt IS NOT NULL
  AND procbalcurrent > 0
  AND active = 'active'
GROUP BY age_bucket
`

type AgingSummaryRow struct {
	Balance   interface{} `json:"balance"`
	AgeBucket string      `json:"age_bucket"`
}

func (q *Queries) AgingSummary(ctx context.Context) ([]AgingSummaryRow, error) {
	rows, err := q.db.QueryContext(ctx, agingSummary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgingSummaryRow
	for rows.Next() {
		var i AgingSummaryRow
		if err := rows.Scan(&i.Balance, &i.AgeBucket); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
