// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: allergies.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createAllergy = `-- name: CreateAllergy :execresult
INSERT INTO allergies (
  created_at, updated_at, patient, active
) VALUES (
  NOW(), NOW(), ?, 'active'
)
`

// Allergies: create a new allergy record
func (q *Queries) CreateAllergy(ctx context.Context, patientID int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAllergy, patientID)
}

const deactivateAllergy = `-- name: DeactivateAllergy :exec
UPDATE allergies
SET active = 'inactive', updated_at = NOW()
WHERE id = ?
`

// Allergies: deactivate an allergy (soft delete)
func (q *Queries) DeactivateAllergy(ctx context.Context, allergyID int64) error {
	_, err := q.db.ExecContext(ctx, deactivateAllergy, allergyID)
	return err
}

const listAllergies = `-- name: ListAllergies :many
SELECT
  id,
  created_at,
  updated_at,
  deleted_at,
  patient,
  active
FROM allergies
WHERE patient = ? AND active = 'active'
ORDER BY created_at DESC
`

// Allergies: list active allergies for a patient
func (q *Queries) ListAllergies(ctx context.Context, patientID int64) ([]Allergy, error) {
	rows, err := q.db.QueryContext(ctx, listAllergies, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Allergy
	for rows.Next() {
		var i Allergy
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Patient,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
