// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: annotations.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createAnnotation = `-- name: CreateAnnotation :execresult
INSERT INTO annotations (
  atimestamp, apatient, amodule, atable, aid, auser, annotation,
  created_at, updated_at
) VALUES (
  ?, ?, ?,
  ?, ?, ?,
  ?, NOW(), NOW()
)
`

type CreateAnnotationParams struct {
	Atimestamp time.Time `json:"atimestamp"`
	PatientID  int64     `json:"patient_id"`
	Amodule    string    `json:"amodule"`
	Atable     string    `json:"atable"`
	Aid        int64     `json:"aid"`
	UserID     int64     `json:"user_id"`
	Annotation string    `json:"annotation"`
}

// Create a new annotation entry
func (q *Queries) CreateAnnotation(ctx context.Context, arg CreateAnnotationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAnnotation,
		arg.Atimestamp,
		arg.PatientID,
		arg.Amodule,
		arg.Atable,
		arg.Aid,
		arg.UserID,
		arg.Annotation,
	)
}

const listAnnotations = `-- name: ListAnnotations :many
SELECT id, created_at, updated_at, deleted_at, atimestamp, apatient, amodule, atable, aid, auser, annotation FROM annotations
WHERE apatient = ?
ORDER BY created_at DESC
`

// List annotations for a patient, ordered by created_at descending
func (q *Queries) ListAnnotations(ctx context.Context, patientID int64) ([]Annotation, error) {
	rows, err := q.db.QueryContext(ctx, listAnnotations, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Annotation
	for rows.Next() {
		var i Annotation
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Atimestamp,
			&i.Apatient,
			&i.Amodule,
			&i.Atable,
			&i.Aid,
			&i.Auser,
			&i.Annotation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
