// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authorizations.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const getAuthorization = `-- name: GetAuthorization :one
SELECT a.id, a.created_at, a.updated_at, a.deleted_at, a.authdtadd, a.authdtmod, a.authpatient, a.authdtbegin, a.authdtend, a.authnum, a.authtype, a.authprov, a.authprovid, a.authinsco, a.authvisits, a.authvisitsused, a.authvisitsremain, a.user, a.active, i.insconame
FROM authorizations a
LEFT JOIN insco i ON a.authinsco = i.id
WHERE a.id = ?
`

type GetAuthorizationRow struct {
	ID               int64          `json:"id"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	DeletedAt        sql.NullTime   `json:"deleted_at"`
	Authdtadd        time.Time      `json:"authdtadd"`
	Authdtmod        time.Time      `json:"authdtmod"`
	Authpatient      int64          `json:"authpatient"`
	Authdtbegin      time.Time      `json:"authdtbegin"`
	Authdtend        time.Time      `json:"authdtend"`
	Authnum          string         `json:"authnum"`
	Authtype         int64          `json:"authtype"`
	Authprov         int64          `json:"authprov"`
	Authprovid       string         `json:"authprovid"`
	Authinsco        int64          `json:"authinsco"`
	Authvisits       int64          `json:"authvisits"`
	Authvisitsused   int64          `json:"authvisitsused"`
	Authvisitsremain int64          `json:"authvisitsremain"`
	User             int64          `json:"user"`
	Active           string         `json:"active"`
	Insconame        sql.NullString `json:"insconame"`
}

// Get single authorization with insurance company name
func (q *Queries) GetAuthorization(ctx context.Context, id int64) (GetAuthorizationRow, error) {
	row := q.db.QueryRowContext(ctx, getAuthorization, id)
	var i GetAuthorizationRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Authdtadd,
		&i.Authdtmod,
		&i.Authpatient,
		&i.Authdtbegin,
		&i.Authdtend,
		&i.Authnum,
		&i.Authtype,
		&i.Authprov,
		&i.Authprovid,
		&i.Authinsco,
		&i.Authvisits,
		&i.Authvisitsused,
		&i.Authvisitsremain,
		&i.User,
		&i.Active,
		&i.Insconame,
	)
	return i, err
}

const listAuthorizations = `-- name: ListAuthorizations :many
SELECT a.id, a.created_at, a.updated_at, a.deleted_at, a.authdtadd, a.authdtmod, a.authpatient, a.authdtbegin, a.authdtend, a.authnum, a.authtype, a.authprov, a.authprovid, a.authinsco, a.authvisits, a.authvisitsused, a.authvisitsremain, a.user, a.active, i.insconame
FROM authorizations a
LEFT JOIN insco i ON a.authinsco = i.id
WHERE a.authpatient = ?
  AND a.active = 'active'
ORDER BY a.authdtbegin DESC
`

type ListAuthorizationsRow struct {
	ID               int64          `json:"id"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	DeletedAt        sql.NullTime   `json:"deleted_at"`
	Authdtadd        time.Time      `json:"authdtadd"`
	Authdtmod        time.Time      `json:"authdtmod"`
	Authpatient      int64          `json:"authpatient"`
	Authdtbegin      time.Time      `json:"authdtbegin"`
	Authdtend        time.Time      `json:"authdtend"`
	Authnum          string         `json:"authnum"`
	Authtype         int64          `json:"authtype"`
	Authprov         int64          `json:"authprov"`
	Authprovid       string         `json:"authprovid"`
	Authinsco        int64          `json:"authinsco"`
	Authvisits       int64          `json:"authvisits"`
	Authvisitsused   int64          `json:"authvisitsused"`
	Authvisitsremain int64          `json:"authvisitsremain"`
	User             int64          `json:"user"`
	Active           string         `json:"active"`
	Insconame        sql.NullString `json:"insconame"`
}

// List authorizations for a patient with insurance company name
func (q *Queries) ListAuthorizations(ctx context.Context, patientID int64) ([]ListAuthorizationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuthorizations, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuthorizationsRow
	for rows.Next() {
		var i ListAuthorizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Authdtadd,
			&i.Authdtmod,
			&i.Authpatient,
			&i.Authdtbegin,
			&i.Authdtend,
			&i.Authnum,
			&i.Authtype,
			&i.Authprov,
			&i.Authprovid,
			&i.Authinsco,
			&i.Authvisits,
			&i.Authvisitsused,
			&i.Authvisitsremain,
			&i.User,
			&i.Active,
			&i.Insconame,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
