// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billkey.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const getBillkeyById = `-- name: GetBillkeyById :one
SELECT id, created_at, updated_at, deleted_at, billkeydate, billkey, bkprocs FROM billkey WHERE id = ?
`

func (q *Queries) GetBillkeyById(ctx context.Context, id int64) (Billkey, error) {
	row := q.db.QueryRowContext(ctx, getBillkeyById, id)
	var i Billkey
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Billkeydate,
		&i.Billkey,
		&i.Bkprocs,
	)
	return i, err
}

const insertBillkey = `-- name: InsertBillkey :execresult
INSERT INTO billkey (
  billkeydate,
  billkey,
  bkprocs,
  created_at,
  updated_at
) VALUES (
  ?,
  ?,
  ?,
  NOW(),
  NOW()
)
`

type InsertBillkeyParams struct {
	Billkeydate time.Time      `json:"billkeydate"`
	Billkey     sql.NullString `json:"billkey"`
	Bkprocs     string         `json:"bkprocs"`
}

func (q *Queries) InsertBillkey(ctx context.Context, arg InsertBillkeyParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertBillkey, arg.Billkeydate, arg.Billkey, arg.Bkprocs)
}
