// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billkey_months.sql

package dbgen

import (
	"context"
	"time"
)

const listBillkeyMonths = `-- name: ListBillkeyMonths :many
SELECT
  id,
  billkeydate,
  bkprocs
FROM billkey
ORDER BY billkeydate DESC
`

type ListBillkeyMonthsRow struct {
	ID          int64     `json:"id"`
	Billkeydate time.Time `json:"billkeydate"`
	Bkprocs     string    `json:"bkprocs"`
}

func (q *Queries) ListBillkeyMonths(ctx context.Context) ([]ListBillkeyMonthsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBillkeyMonths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBillkeyMonthsRow
	for rows.Next() {
		var i ListBillkeyMonthsRow
		if err := rows.Scan(&i.ID, &i.Billkeydate, &i.Bkprocs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
