// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: callin.sql

package dbgen

import (
	"context"
)

const getCallIn = `-- name: GetCallIn :one
SELECT
  id,
  cilname,
  cifname,
  cicomplaint,
  created_at,
  updated_at,
  deleted_at
FROM callin
WHERE id = ?
`

// CallIn: get a single call-in record by ID
func (q *Queries) GetCallIn(ctx context.Context, id int64) (Callin, error) {
	row := q.db.QueryRowContext(ctx, getCallIn, id)
	var i Callin
	err := row.Scan(
		&i.ID,
		&i.Cilname,
		&i.Cifname,
		&i.Cicomplaint,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCallIns = `-- name: ListCallIns :many
SELECT
  id,
  cilname,
  cifname,
  cicomplaint,
  created_at,
  updated_at,
  deleted_at
FROM callin
ORDER BY id DESC
LIMIT 50
`

// CallIn: list all call-in records
func (q *Queries) ListCallIns(ctx context.Context) ([]Callin, error) {
	rows, err := q.db.QueryContext(ctx, listCallIns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Callin
	for rows.Next() {
		var i Callin
		if err := rows.Scan(
			&i.ID,
			&i.Cilname,
			&i.Cifname,
			&i.Cicomplaint,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
