// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: certifications.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createCertification = `-- name: CreateCertification :execresult
INSERT INTO certifications (
  created_at, updated_at, patient, cert_type, cert_form_num,
  cert_desc, cert_form_data, user, active
) VALUES (
  NOW(), NOW(), ?, ?,
  ?,
  ?, ?,
  ?, 'active'
)
`

type CreateCertificationParams struct {
	PatientID    int64          `json:"patient_id"`
	CertType     int64          `json:"cert_type"`
	CertFormNum  sql.NullInt64  `json:"cert_form_num"`
	CertDesc     string         `json:"cert_desc"`
	CertFormData sql.NullString `json:"cert_form_data"`
	UserID       int64          `json:"user_id"`
}

func (q *Queries) CreateCertification(ctx context.Context, arg CreateCertificationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCertification,
		arg.PatientID,
		arg.CertType,
		arg.CertFormNum,
		arg.CertDesc,
		arg.CertFormData,
		arg.UserID,
	)
}

const listCertificationsByPatient = `-- name: ListCertificationsByPatient :many
SELECT id, created_at, updated_at, deleted_at, patient, cert_type, cert_form_num, cert_desc, cert_form_data, user, active FROM certifications
WHERE patient = ?
  AND active = 'active'
  AND deleted_at IS NULL
ORDER BY id DESC
`

func (q *Queries) ListCertificationsByPatient(ctx context.Context, patientID int64) ([]Certification, error) {
	rows, err := q.db.QueryContext(ctx, listCertificationsByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Certification
	for rows.Next() {
		var i Certification
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Patient,
			&i.CertType,
			&i.CertFormNum,
			&i.CertDesc,
			&i.CertFormData,
			&i.User,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
