// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chronic_problems.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createChronicProblem = `-- name: CreateChronicProblem :execresult
INSERT INTO chronic_problems (
  created_at, updated_at, patient, date, problem, user
) VALUES (
  NOW(), NOW(), ?, ?,
  ?, ?
)
`

type CreateChronicProblemParams struct {
	PatientID int64     `json:"patient_id"`
	Date      time.Time `json:"date"`
	Problem   string    `json:"problem"`
	UserID    int64     `json:"user_id"`
}

func (q *Queries) CreateChronicProblem(ctx context.Context, arg CreateChronicProblemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createChronicProblem,
		arg.PatientID,
		arg.Date,
		arg.Problem,
		arg.UserID,
	)
}

const listChronicProblemsByPatient = `-- name: ListChronicProblemsByPatient :many
SELECT id, created_at, updated_at, deleted_at, patient, date, problem, user FROM chronic_problems
WHERE patient = ?
  AND deleted_at IS NULL
ORDER BY date DESC
`

func (q *Queries) ListChronicProblemsByPatient(ctx context.Context, patientID int64) ([]ChronicProblem, error) {
	rows, err := q.db.QueryContext(ctx, listChronicProblemsByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChronicProblem
	for rows.Next() {
		var i ChronicProblem
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Patient,
			&i.Date,
			&i.Problem,
			&i.User,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
