// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: claimlog.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const insertClaimLog = `-- name: InsertClaimLog :execresult
INSERT INTO claimlog (
  cltimestamp,
  cluser,
  clprocedure,
  clpayrec,
  claction,
  clcomment,
  clformat,
  cltarget,
  cltargetopt,
  clbillkey,
  created_at,
  updated_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  NOW(),
  NOW()
)
`

type InsertClaimLogParams struct {
	Cltimestamp time.Time `json:"cltimestamp"`
	Cluser      int64     `json:"cluser"`
	Clprocedure int64     `json:"clprocedure"`
	Clpayrec    int64     `json:"clpayrec"`
	Claction    string    `json:"claction"`
	Clcomment   string    `json:"clcomment"`
	Clformat    string    `json:"clformat"`
	Cltarget    string    `json:"cltarget"`
	Cltargetopt string    `json:"cltargetopt"`
	Clbillkey   int64     `json:"clbillkey"`
}

// Insert a claim log entry
func (q *Queries) InsertClaimLog(ctx context.Context, arg InsertClaimLogParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertClaimLog,
		arg.Cltimestamp,
		arg.Cluser,
		arg.Clprocedure,
		arg.Clpayrec,
		arg.Claction,
		arg.Clcomment,
		arg.Clformat,
		arg.Cltarget,
		arg.Cltargetopt,
		arg.Clbillkey,
	)
}

const listClaimLog = `-- name: ListClaimLog :many
SELECT
  id,
  cltimestamp,
  cluser,
  clprocedure,
  clpayrec,
  claction,
  clcomment,
  clformat,
  cltarget,
  cltargetopt,
  clbillkey,
  created_at,
  updated_at,
  deleted_at
FROM claimlog
WHERE clprocedure = ?
ORDER BY cltimestamp DESC
`

type ListClaimLogRow struct {
	ID          int64        `json:"id"`
	Cltimestamp time.Time    `json:"cltimestamp"`
	Cluser      int64        `json:"cluser"`
	Clprocedure int64        `json:"clprocedure"`
	Clpayrec    int64        `json:"clpayrec"`
	Claction    string       `json:"claction"`
	Clcomment   string       `json:"clcomment"`
	Clformat    string       `json:"clformat"`
	Cltarget    string       `json:"cltarget"`
	Cltargetopt string       `json:"cltargetopt"`
	Clbillkey   int64        `json:"clbillkey"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
}

// List claim log entries for a specific claim (clprocedure)
func (q *Queries) ListClaimLog(ctx context.Context, claimID int64) ([]ListClaimLogRow, error) {
	rows, err := q.db.QueryContext(ctx, listClaimLog, claimID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClaimLogRow
	for rows.Next() {
		var i ListClaimLogRow
		if err := rows.Scan(
			&i.ID,
			&i.Cltimestamp,
			&i.Cluser,
			&i.Clprocedure,
			&i.Clpayrec,
			&i.Claction,
			&i.Clcomment,
			&i.Clformat,
			&i.Cltarget,
			&i.Cltargetopt,
			&i.Clbillkey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
