// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clinical_orders.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createClinicalOrder = `-- name: CreateClinicalOrder :execresult
INSERT INTO clinical_orders (
  patient, order_type, description, status, date_ordered,
  ordering_provider, notes, user, active, created_at, updated_at
) VALUES (
  ?, ?, ?,
  ?, ?,
  ?, ?,
  ?, 'active', NOW(), NOW()
)
`

type CreateClinicalOrderParams struct {
	PatientID        int64          `json:"patient_id"`
	OrderType        string         `json:"order_type"`
	Description      string         `json:"description"`
	Status           string         `json:"status"`
	DateOrdered      sql.NullTime   `json:"date_ordered"`
	OrderingProvider int64          `json:"ordering_provider"`
	Notes            sql.NullString `json:"notes"`
	UserID           int64          `json:"user_id"`
}

// Create a new clinical order entry
func (q *Queries) CreateClinicalOrder(ctx context.Context, arg CreateClinicalOrderParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createClinicalOrder,
		arg.PatientID,
		arg.OrderType,
		arg.Description,
		arg.Status,
		arg.DateOrdered,
		arg.OrderingProvider,
		arg.Notes,
		arg.UserID,
	)
}

const listClinicalOrders = `-- name: ListClinicalOrders :many
SELECT id, created_at, updated_at, deleted_at, patient, order_type, description, status, date_ordered, ordering_provider, notes, user, active FROM clinical_orders
WHERE patient = ?
  AND active = 'active'
ORDER BY date_ordered DESC
`

// List clinical orders for a patient, ordered by date ordered descending
func (q *Queries) ListClinicalOrders(ctx context.Context, patientID int64) ([]ClinicalOrder, error) {
	rows, err := q.db.QueryContext(ctx, listClinicalOrders, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClinicalOrder
	for rows.Next() {
		var i ClinicalOrder
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Patient,
			&i.OrderType,
			&i.Description,
			&i.Status,
			&i.DateOrdered,
			&i.OrderingProvider,
			&i.Notes,
			&i.User,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
