// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: config.sql

package dbgen

import (
	"context"
	"database/sql"
)

const getConfigById = `-- name: GetConfigById :one
SELECT id, created_at, updated_at, deleted_at, c_option, c_value, c_title, c_section, c_type, c_options FROM config WHERE id = ?
`

func (q *Queries) GetConfigById(ctx context.Context, id int64) (Config, error) {
	row := q.db.QueryRowContext(ctx, getConfigById, id)
	var i Config
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.COption,
		&i.CValue,
		&i.CTitle,
		&i.CSection,
		&i.CType,
		&i.COptions,
	)
	return i, err
}

const getConfigSections = `-- name: GetConfigSections :many
SELECT DISTINCT c_section FROM config ORDER BY c_section
`

func (q *Queries) GetConfigSections(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, getConfigSections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var c_section sql.NullString
		if err := rows.Scan(&c_section); err != nil {
			return nil, err
		}
		items = append(items, c_section)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllConfig = `-- name: ListAllConfig :many
SELECT id, created_at, updated_at, deleted_at, c_option, c_value, c_title, c_section, c_type, c_options FROM config ORDER BY c_option
`

func (q *Queries) ListAllConfig(ctx context.Context) ([]Config, error) {
	rows, err := q.db.QueryContext(ctx, listAllConfig)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Config
	for rows.Next() {
		var i Config
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.COption,
			&i.CValue,
			&i.CTitle,
			&i.CSection,
			&i.CType,
			&i.COptions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConfig = `-- name: UpdateConfig :exec
UPDATE config SET c_value = ? WHERE id = ?
`

type UpdateConfigParams struct {
	CValue sql.NullString `json:"c_value"`
	ID     int64          `json:"id"`
}

func (q *Queries) UpdateConfig(ctx context.Context, arg UpdateConfigParams) error {
	_, err := q.db.ExecContext(ctx, updateConfig, arg.CValue, arg.ID)
	return err
}
