// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: coverages.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createCoverage = `-- name: CreateCoverage :execresult
INSERT INTO patient_coverage (
  patient, insurance_company, coverage_type,
  policy_number, group_number, effective_date,
  termination_date, primary_coverage, active,
  created_at, updated_at
) VALUES (
  ?, ?, ?,
  ?, ?, ?,
  ?, ?, 'active',
  NOW(), NOW()
)
`

type CreateCoverageParams struct {
	Patient          int64        `json:"patient"`
	InsuranceCompany int64        `json:"insurance_company"`
	CoverageType     int64        `json:"coverage_type"`
	PolicyNumber     string       `json:"policy_number"`
	GroupNumber      string       `json:"group_number"`
	EffectiveDate    sql.NullTime `json:"effective_date"`
	TerminationDate  sql.NullTime `json:"termination_date"`
	PrimaryCoverage  bool         `json:"primary_coverage"`
}

// CreateCoverage: create a new patient coverage record
func (q *Queries) CreateCoverage(ctx context.Context, arg CreateCoverageParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCoverage,
		arg.Patient,
		arg.InsuranceCompany,
		arg.CoverageType,
		arg.PolicyNumber,
		arg.GroupNumber,
		arg.EffectiveDate,
		arg.TerminationDate,
		arg.PrimaryCoverage,
	)
}

const getPrimaryCoverage = `-- name: GetPrimaryCoverage :one
SELECT
  pc.id,
  pc.patient,
  pc.insurance_company,
  i.insconame AS insurance_company_name,
  pc.coverage_type,
  ct.covtpname AS coverage_type_name,
  pc.policy_number,
  pc.group_number,
  pc.effective_date,
  pc.termination_date,
  pc.primary_coverage,
  pc.active,
  pc.created_at,
  pc.updated_at
FROM patient_coverage pc
LEFT JOIN insco i ON pc.insurance_company = i.id
LEFT JOIN covtypes ct ON pc.coverage_type = ct.id
WHERE pc.patient = ?
  AND pc.primary_coverage = 1
  AND pc.active = 'active'
LIMIT 1
`

type GetPrimaryCoverageRow struct {
	ID                   int64          `json:"id"`
	Patient              int64          `json:"patient"`
	InsuranceCompany     int64          `json:"insurance_company"`
	InsuranceCompanyName sql.NullString `json:"insurance_company_name"`
	CoverageType         int64          `json:"coverage_type"`
	CoverageTypeName     sql.NullString `json:"coverage_type_name"`
	PolicyNumber         string         `json:"policy_number"`
	GroupNumber          string         `json:"group_number"`
	EffectiveDate        sql.NullTime   `json:"effective_date"`
	TerminationDate      sql.NullTime   `json:"termination_date"`
	PrimaryCoverage      bool           `json:"primary_coverage"`
	Active               string         `json:"active"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
}

// GetPrimaryCoverage: get the primary active coverage for a patient
func (q *Queries) GetPrimaryCoverage(ctx context.Context, patientID int64) (GetPrimaryCoverageRow, error) {
	row := q.db.QueryRowContext(ctx, getPrimaryCoverage, patientID)
	var i GetPrimaryCoverageRow
	err := row.Scan(
		&i.ID,
		&i.Patient,
		&i.InsuranceCompany,
		&i.InsuranceCompanyName,
		&i.CoverageType,
		&i.CoverageTypeName,
		&i.PolicyNumber,
		&i.GroupNumber,
		&i.EffectiveDate,
		&i.TerminationDate,
		&i.PrimaryCoverage,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCoverages = `-- name: ListCoverages :many
SELECT
  pc.id,
  pc.patient,
  pc.insurance_company,
  i.insconame AS insurance_company_name,
  pc.coverage_type,
  ct.covtpname AS coverage_type_name,
  pc.policy_number,
  pc.group_number,
  pc.effective_date,
  pc.termination_date,
  pc.primary_coverage,
  pc.active,
  pc.created_at,
  pc.updated_at
FROM patient_coverage pc
LEFT JOIN insco i ON pc.insurance_company = i.id
LEFT JOIN covtypes ct ON pc.coverage_type = ct.id
WHERE pc.patient = ?
  AND pc.active = 'active'
ORDER BY pc.primary_coverage DESC, pc.effective_date DESC
`

type ListCoveragesRow struct {
	ID                   int64          `json:"id"`
	Patient              int64          `json:"patient"`
	InsuranceCompany     int64          `json:"insurance_company"`
	InsuranceCompanyName sql.NullString `json:"insurance_company_name"`
	CoverageType         int64          `json:"coverage_type"`
	CoverageTypeName     sql.NullString `json:"coverage_type_name"`
	PolicyNumber         string         `json:"policy_number"`
	GroupNumber          string         `json:"group_number"`
	EffectiveDate        sql.NullTime   `json:"effective_date"`
	TerminationDate      sql.NullTime   `json:"termination_date"`
	PrimaryCoverage      bool           `json:"primary_coverage"`
	Active               string         `json:"active"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
}

// ListCoverages: list active coverages for a patient with insurance company and coverage type names
func (q *Queries) ListCoverages(ctx context.Context, patientID int64) ([]ListCoveragesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCoverages, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCoveragesRow
	for rows.Next() {
		var i ListCoveragesRow
		if err := rows.Scan(
			&i.ID,
			&i.Patient,
			&i.InsuranceCompany,
			&i.InsuranceCompanyName,
			&i.CoverageType,
			&i.CoverageTypeName,
			&i.PolicyNumber,
			&i.GroupNumber,
			&i.EffectiveDate,
			&i.TerminationDate,
			&i.PrimaryCoverage,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCoverage = `-- name: RemoveCoverage :exec
UPDATE patient_coverage
SET active = 'inactive', updated_at = NOW()
WHERE id = ?
  AND patient = ?
`

type RemoveCoverageParams struct {
	CoverageID int64 `json:"coverage_id"`
	PatientID  int64 `json:"patient_id"`
}

// RemoveCoverage: soft-delete a patient coverage record
func (q *Queries) RemoveCoverage(ctx context.Context, arg RemoveCoverageParams) error {
	_, err := q.db.ExecContext(ctx, removeCoverage, arg.CoverageID, arg.PatientID)
	return err
}
