// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: current_problems.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createCurrentProblem = `-- name: CreateCurrentProblem :execresult
INSERT INTO current_problems (
  created_at, updated_at, patient, date, problem, user, active
) VALUES (
  NOW(), NOW(), ?, ?,
  ?, ?, 'active'
)
`

type CreateCurrentProblemParams struct {
	PatientID int64     `json:"patient_id"`
	Date      time.Time `json:"date"`
	Problem   string    `json:"problem"`
	UserID    int64     `json:"user_id"`
}

func (q *Queries) CreateCurrentProblem(ctx context.Context, arg CreateCurrentProblemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCurrentProblem,
		arg.PatientID,
		arg.Date,
		arg.Problem,
		arg.UserID,
	)
}

const listCurrentProblemsByPatient = `-- name: ListCurrentProblemsByPatient :many
SELECT id, created_at, updated_at, deleted_at, patient, date, problem, user, active FROM current_problems
WHERE patient = ?
  AND active = 'active'
  AND deleted_at IS NULL
ORDER BY date DESC
`

func (q *Queries) ListCurrentProblemsByPatient(ctx context.Context, patientID int64) ([]CurrentProblem, error) {
	rows, err := q.db.QueryContext(ctx, listCurrentProblemsByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CurrentProblem
	for rows.Next() {
		var i CurrentProblem
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Patient,
			&i.Date,
			&i.Problem,
			&i.User,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
