// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package dbgen

import (
	"context"
)

const dashboardActiveAuthorizationsCount = `-- name: DashboardActiveAuthorizationsCount :one
SELECT COUNT(*) AS total FROM authorizations
WHERE authdtend >= CURDATE()
  AND active = 'active'
`

// Dashboard: count of active authorizations that haven't expired
func (q *Queries) DashboardActiveAuthorizationsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, dashboardActiveAuthorizationsCount)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const dashboardPatientCount = `-- name: DashboardPatientCount :one
SELECT COUNT(*) AS total FROM patient WHERE ptarchive = 0
`

// Dashboard: count of non-archived patients
func (q *Queries) DashboardPatientCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, dashboardPatientCount)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const dashboardTodayAppointmentsCount = `-- name: DashboardTodayAppointmentsCount :one
SELECT COUNT(*) AS total FROM scheduler
WHERE DATE(caldateof) = CURDATE()
  AND calstatus NOT IN ('cancelled', 'noshow')
`

// Dashboard: count of today's appointments (excluding cancelled/noshow)
func (q *Queries) DashboardTodayAppointmentsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, dashboardTodayAppointmentsCount)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const dashboardUnreadMessagesCount = `-- name: DashboardUnreadMessagesCount :one
SELECT COUNT(*) AS total FROM messages
WHERE msgfor = ?
  AND msgread = 0
`

// Dashboard: count of unread messages for a user
func (q *Queries) DashboardUnreadMessagesCount(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, dashboardUnreadMessagesCount, userID)
	var total int64
	err := row.Scan(&total)
	return total, err
}
