// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: data_store.sql

package dbgen

import (
	"context"
)

const getDataStoreByPatientModule = `-- name: GetDataStoreByPatientModule :one
SELECT id, created_at, updated_at, deleted_at, patient, module, contents FROM pds
WHERE patient = ?
  AND module = LOWER(?)
  AND id = ?
`

type GetDataStoreByPatientModuleParams struct {
	PatientID int64  `json:"patient_id"`
	Module    string `json:"module"`
	ID        int64  `json:"id"`
}

func (q *Queries) GetDataStoreByPatientModule(ctx context.Context, arg GetDataStoreByPatientModuleParams) (Pd, error) {
	row := q.db.QueryRowContext(ctx, getDataStoreByPatientModule, arg.PatientID, arg.Module, arg.ID)
	var i Pd
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Patient,
		&i.Module,
		&i.Contents,
	)
	return i, err
}
