// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: diagnoses.sql

package dbgen

import (
	"context"
)

const patientDiagnoses = `-- name: PatientDiagnoses :many
SELECT
  'primary' AS dx_type,
  i.icd9code,
  i.icd9descrip
FROM patient p
JOIN icd9 i ON i.id = p.ptdiag1
WHERE p.id = ?
  AND p.ptdiag1 IS NOT NULL
UNION ALL
SELECT
  'secondary' AS dx_type,
  i.icd9code,
  i.icd9descrip
FROM patient p
JOIN icd9 i ON i.id = p.ptdiag2
WHERE p.id = ?
  AND p.ptdiag2 IS NOT NULL
UNION ALL
SELECT
  'secondary' AS dx_type,
  i.icd9code,
  i.icd9descrip
FROM patient p
JOIN icd9 i ON i.id = p.ptdiag3
WHERE p.id = ?
  AND p.ptdiag3 IS NOT NULL
UNION ALL
SELECT
  'secondary' AS dx_type,
  i.icd9code,
  i.icd9descrip
FROM patient p
JOIN icd9 i ON i.id = p.ptdiag4
WHERE p.id = ?
  AND p.ptdiag4 IS NOT NULL
`

type PatientDiagnosesParams struct {
	PatientID int64 `json:"patient_id"`
}

type PatientDiagnosesRow struct {
	DxType      string `json:"dx_type"`
	Icd9code    string `json:"icd9code"`
	Icd9descrip string `json:"icd9descrip"`
}

// PatientDiagnoses: list all ICD-9 diagnoses for a patient
func (q *Queries) PatientDiagnoses(ctx context.Context, arg PatientDiagnosesParams) ([]PatientDiagnosesRow, error) {
	rows, err := q.db.QueryContext(ctx, patientDiagnoses,
		arg.PatientID,
		arg.PatientID,
		arg.PatientID,
		arg.PatientID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatientDiagnosesRow
	for rows.Next() {
		var i PatientDiagnosesRow
		if err := rows.Scan(&i.DxType, &i.Icd9code, &i.Icd9descrip); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
