// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dicom.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const countDicomByMd5 = `-- name: CountDicomByMd5 :one
SELECT COUNT(*) FROM dicom
WHERE d_md5 = ?
  AND deleted_at IS NULL
`

func (q *Queries) CountDicomByMd5(ctx context.Context, md5 string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDicomByMd5, md5)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDicom = `-- name: CreateDicom :execresult
INSERT INTO dicom (
  created_at, updated_at, d_md5, d_patient, d_study_description, d_filename,
  d_study_date, d_institution_name, d_institution_address, d_study_uid,
  d_series_uid, d_sop_uid, d_referring_provider, d_modality, d_patient_id,
  d_xml_data, storage_status, user, d_data
) VALUES (
  NOW(), NOW(),
  ?, ?, ?, ?,
  ?, ?, ?, ?,
  ?, ?, ?, ?, ?,
  ?, ?, ?, ?
)
`

type CreateDicomParams struct {
	Md5                string         `json:"md5"`
	PatientID          int64          `json:"patient_id"`
	StudyDescription   sql.NullString `json:"study_description"`
	Filename           sql.NullString `json:"filename"`
	StudyDate          sql.NullTime   `json:"study_date"`
	InstitutionName    sql.NullString `json:"institution_name"`
	InstitutionAddress sql.NullString `json:"institution_address"`
	StudyUid           sql.NullString `json:"study_uid"`
	SeriesUid          sql.NullString `json:"series_uid"`
	SopUid             sql.NullString `json:"sop_uid"`
	ReferringProvider  sql.NullString `json:"referring_provider"`
	Modality           sql.NullString `json:"modality"`
	DicomPatientID     sql.NullString `json:"dicom_patient_id"`
	XmlData            sql.NullString `json:"xml_data"`
	StorageStatus      string         `json:"storage_status"`
	UserID             int64          `json:"user_id"`
	Data               sql.NullString `json:"data"`
}

func (q *Queries) CreateDicom(ctx context.Context, arg CreateDicomParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createDicom,
		arg.Md5,
		arg.PatientID,
		arg.StudyDescription,
		arg.Filename,
		arg.StudyDate,
		arg.InstitutionName,
		arg.InstitutionAddress,
		arg.StudyUid,
		arg.SeriesUid,
		arg.SopUid,
		arg.ReferringProvider,
		arg.Modality,
		arg.DicomPatientID,
		arg.XmlData,
		arg.StorageStatus,
		arg.UserID,
		arg.Data,
	)
}

const deleteDicom = `-- name: DeleteDicom :exec
UPDATE dicom SET updated_at = NOW(), deleted_at = NOW()
WHERE id = ?
  AND deleted_at IS NULL
`

func (q *Queries) DeleteDicom(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDicom, id)
	return err
}

const getDicom = `-- name: GetDicom :one
SELECT id, created_at, updated_at, deleted_at, d_md5, d_patient, d_study_description, d_filename, d_study_date, d_institution_name, d_institution_address, d_study_uid, d_series_uid, d_sop_uid, d_referring_provider, d_modality, d_patient_id, d_xml_data, storage_status, user, d_data FROM dicom
WHERE id = ?
  AND deleted_at IS NULL
`

func (q *Queries) GetDicom(ctx context.Context, id int64) (Dicom, error) {
	row := q.db.QueryRowContext(ctx, getDicom, id)
	var i Dicom
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DMd5,
		&i.DPatient,
		&i.DStudyDescription,
		&i.DFilename,
		&i.DStudyDate,
		&i.DInstitutionName,
		&i.DInstitutionAddress,
		&i.DStudyUid,
		&i.DSeriesUid,
		&i.DSopUid,
		&i.DReferringProvider,
		&i.DModality,
		&i.DPatientID,
		&i.DXmlData,
		&i.StorageStatus,
		&i.User,
		&i.DData,
	)
	return i, err
}

const getDicomBySop = `-- name: GetDicomBySop :one
SELECT id, created_at, updated_at, deleted_at, d_md5, d_patient, d_study_description, d_filename, d_study_date, d_institution_name, d_institution_address, d_study_uid, d_series_uid, d_sop_uid, d_referring_provider, d_modality, d_patient_id, d_xml_data, storage_status, user, d_data FROM dicom
WHERE d_study_uid = ?
  AND d_series_uid = ?
  AND d_sop_uid = ?
  AND deleted_at IS NULL
ORDER BY id DESC
LIMIT 1
`

type GetDicomBySopParams struct {
	StudyUid  sql.NullString `json:"study_uid"`
	SeriesUid sql.NullString `json:"series_uid"`
	SopUid    sql.NullString `json:"sop_uid"`
}

func (q *Queries) GetDicomBySop(ctx context.Context, arg GetDicomBySopParams) (Dicom, error) {
	row := q.db.QueryRowContext(ctx, getDicomBySop, arg.StudyUid, arg.SeriesUid, arg.SopUid)
	var i Dicom
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DMd5,
		&i.DPatient,
		&i.DStudyDescription,
		&i.DFilename,
		&i.DStudyDate,
		&i.DInstitutionName,
		&i.DInstitutionAddress,
		&i.DStudyUid,
		&i.DSeriesUid,
		&i.DSopUid,
		&i.DReferringProvider,
		&i.DModality,
		&i.DPatientID,
		&i.DXmlData,
		&i.StorageStatus,
		&i.User,
		&i.DData,
	)
	return i, err
}

const listDicomByPatient = `-- name: ListDicomByPatient :many
SELECT id, created_at, updated_at, d_md5, d_patient,
       d_study_description, d_filename, d_study_date, d_institution_name,
       d_institution_address, d_study_uid, d_series_uid, d_sop_uid,
       d_referring_provider, d_modality, d_patient_id, storage_status, user
FROM dicom
WHERE d_patient = ?
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListDicomByPatientRow struct {
	ID                  int64          `json:"id"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
	DMd5                string         `json:"d_md5"`
	DPatient            int64          `json:"d_patient"`
	DStudyDescription   sql.NullString `json:"d_study_description"`
	DFilename           sql.NullString `json:"d_filename"`
	DStudyDate          sql.NullTime   `json:"d_study_date"`
	DInstitutionName    sql.NullString `json:"d_institution_name"`
	DInstitutionAddress sql.NullString `json:"d_institution_address"`
	DStudyUid           sql.NullString `json:"d_study_uid"`
	DSeriesUid          sql.NullString `json:"d_series_uid"`
	DSopUid             sql.NullString `json:"d_sop_uid"`
	DReferringProvider  sql.NullString `json:"d_referring_provider"`
	DModality           sql.NullString `json:"d_modality"`
	DPatientID          sql.NullString `json:"d_patient_id"`
	StorageStatus       string         `json:"storage_status"`
	User                int64          `json:"user"`
}

func (q *Queries) ListDicomByPatient(ctx context.Context, patientID int64) ([]ListDicomByPatientRow, error) {
	rows, err := q.db.QueryContext(ctx, listDicomByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDicomByPatientRow
	for rows.Next() {
		var i ListDicomByPatientRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DMd5,
			&i.DPatient,
			&i.DStudyDescription,
			&i.DFilename,
			&i.DStudyDate,
			&i.DInstitutionName,
			&i.DInstitutionAddress,
			&i.DStudyUid,
			&i.DSeriesUid,
			&i.DSopUid,
			&i.DReferringProvider,
			&i.DModality,
			&i.DPatientID,
			&i.StorageStatus,
			&i.User,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDicomStudies = `-- name: ListDicomStudies :many
SELECT d_study_uid, d_study_date, d_study_description, d_patient_id,
       d_patient, d_modality
FROM dicom
WHERE deleted_at IS NULL
  AND (? IS NULL OR d_patient_id = ?)
  AND (? IS NULL OR d_study_uid = ?)
GROUP BY d_study_uid, d_study_date, d_study_description, d_patient_id, d_patient, d_modality
ORDER BY d_study_date DESC
`

type ListDicomStudiesParams struct {
	PatientID sql.NullString `json:"patient_id"`
	StudyUid  sql.NullString `json:"study_uid"`
}

type ListDicomStudiesRow struct {
	DStudyUid         sql.NullString `json:"d_study_uid"`
	DStudyDate        sql.NullTime   `json:"d_study_date"`
	DStudyDescription sql.NullString `json:"d_study_description"`
	DPatientID        sql.NullString `json:"d_patient_id"`
	DPatient          int64          `json:"d_patient"`
	DModality         sql.NullString `json:"d_modality"`
}

func (q *Queries) ListDicomStudies(ctx context.Context, arg ListDicomStudiesParams) ([]ListDicomStudiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDicomStudies,
		arg.PatientID,
		arg.PatientID,
		arg.StudyUid,
		arg.StudyUid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDicomStudiesRow
	for rows.Next() {
		var i ListDicomStudiesRow
		if err := rows.Scan(
			&i.DStudyUid,
			&i.DStudyDate,
			&i.DStudyDescription,
			&i.DPatientID,
			&i.DPatient,
			&i.DModality,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
