// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package dbgen

import (
	"context"
)

const assignUnfiledDoc = `-- name: AssignUnfiledDoc :exec
UPDATE unfiled_docs
SET assigned_to = ?,
    updated_at = NOW()
WHERE id = ?
  AND active = 'active'
  AND deleted_at IS NULL
`

type AssignUnfiledDocParams struct {
	AssignedTo int64 `json:"assigned_to"`
	ID         int64 `json:"id"`
}

func (q *Queries) AssignUnfiledDoc(ctx context.Context, arg AssignUnfiledDocParams) error {
	_, err := q.db.ExecContext(ctx, assignUnfiledDoc, arg.AssignedTo, arg.ID)
	return err
}

const countUnfiledDocs = `-- name: CountUnfiledDocs :one
SELECT COUNT(*) AS total FROM unfiled_docs
WHERE active = 'active'
  AND deleted_at IS NULL
`

func (q *Queries) CountUnfiledDocs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnfiledDocs)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countUnreadDocs = `-- name: CountUnreadDocs :one
SELECT COUNT(*) AS total FROM unread_docs
WHERE active = 'active'
  AND deleted_at IS NULL
`

func (q *Queries) CountUnreadDocs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadDocs)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const listUnfiledDocs = `-- name: ListUnfiledDocs :many

SELECT id, created_at, updated_at, deleted_at, filename, page_count, file_type, received_date, assigned_to, status, notes, user, active FROM unfiled_docs
WHERE active = 'active'
  AND deleted_at IS NULL
ORDER BY received_date DESC
`

// ============================================================================
// Unfiled Documents
// ============================================================================
func (q *Queries) ListUnfiledDocs(ctx context.Context) ([]UnfiledDoc, error) {
	rows, err := q.db.QueryContext(ctx, listUnfiledDocs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UnfiledDoc
	for rows.Next() {
		var i UnfiledDoc
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Filename,
			&i.PageCount,
			&i.FileType,
			&i.ReceivedDate,
			&i.AssignedTo,
			&i.Status,
			&i.Notes,
			&i.User,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadDocs = `-- name: ListUnreadDocs :many

SELECT id, created_at, updated_at, deleted_at, document_type, patient, filename, page_count, sent_date, sending_provider, assigned_to, reviewed, review_date, notes, user, active FROM unread_docs
WHERE active = 'active'
  AND deleted_at IS NULL
ORDER BY sent_date DESC
`

// ============================================================================
// Unread Documents
// ============================================================================
func (q *Queries) ListUnreadDocs(ctx context.Context) ([]UnreadDoc, error) {
	rows, err := q.db.QueryContext(ctx, listUnreadDocs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UnreadDoc
	for rows.Next() {
		var i UnreadDoc
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DocumentType,
			&i.Patient,
			&i.Filename,
			&i.PageCount,
			&i.SentDate,
			&i.SendingProvider,
			&i.AssignedTo,
			&i.Reviewed,
			&i.ReviewDate,
			&i.Notes,
			&i.User,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reassignUnreadDoc = `-- name: ReassignUnreadDoc :exec
UPDATE unread_docs
SET assigned_to = ?,
    updated_at = NOW()
WHERE id = ?
  AND active = 'active'
  AND deleted_at IS NULL
`

type ReassignUnreadDocParams struct {
	AssignedTo int64 `json:"assigned_to"`
	ID         int64 `json:"id"`
}

func (q *Queries) ReassignUnreadDoc(ctx context.Context, arg ReassignUnreadDocParams) error {
	_, err := q.db.ExecContext(ctx, reassignUnreadDoc, arg.AssignedTo, arg.ID)
	return err
}

const reviewUnreadDoc = `-- name: ReviewUnreadDoc :exec
UPDATE unread_docs
SET reviewed = true,
    review_date = NOW(),
    updated_at = NOW()
WHERE id = ?
  AND active = 'active'
  AND deleted_at IS NULL
`

func (q *Queries) ReviewUnreadDoc(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, reviewUnreadDoc, id)
	return err
}
