// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: drug_samples.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createDrugSample = `-- name: CreateDrugSample :execresult
INSERT INTO drugsampleinv (
  drugcode, drugndc, drugclass, packagecount, location,
  drugco, drugrep, invoice, samplecount, samplecountremain,
  lot, expiration, received, assignedto, loguser, logdate
) VALUES (
  ?, ?, ?,
  ?, ?, ?,
  ?, ?, ?,
  ?, ?, ?,
  ?, ?, ?,
  ?
)
`

type CreateDrugSampleParams struct {
	Drugcode          string       `json:"drugcode"`
	Drugndc           string       `json:"drugndc"`
	Drugclass         string       `json:"drugclass"`
	Packagecount      int64        `json:"packagecount"`
	Location          string       `json:"location"`
	Drugco            string       `json:"drugco"`
	Drugrep           string       `json:"drugrep"`
	Invoice           string       `json:"invoice"`
	Samplecount       int64        `json:"samplecount"`
	Samplecountremain int64        `json:"samplecountremain"`
	Lot               string       `json:"lot"`
	Expiration        sql.NullTime `json:"expiration"`
	Received          sql.NullTime `json:"received"`
	Assignedto        string       `json:"assignedto"`
	Loguser           int64        `json:"loguser"`
	Logdate           time.Time    `json:"logdate"`
}

// Create drug sample entry
func (q *Queries) CreateDrugSample(ctx context.Context, arg CreateDrugSampleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createDrugSample,
		arg.Drugcode,
		arg.Drugndc,
		arg.Drugclass,
		arg.Packagecount,
		arg.Location,
		arg.Drugco,
		arg.Drugrep,
		arg.Invoice,
		arg.Samplecount,
		arg.Samplecountremain,
		arg.Lot,
		arg.Expiration,
		arg.Received,
		arg.Assignedto,
		arg.Loguser,
		arg.Logdate,
	)
}

const listDrugSamples = `-- name: ListDrugSamples :many
SELECT id, created_at, updated_at, deleted_at, drugcode, drugndc, drugclass, packagecount, location, drugco, drugrep, invoice, samplecount, samplecountremain, lot, expiration, received, assignedto, loguser, logdate, disposeby, disposedate, disposemethod, disposereason, witness FROM drugsampleinv
ORDER BY created_at DESC
`

// List all drug samples
func (q *Queries) ListDrugSamples(ctx context.Context) ([]Drugsampleinv, error) {
	rows, err := q.db.QueryContext(ctx, listDrugSamples)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Drugsampleinv
	for rows.Next() {
		var i Drugsampleinv
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Drugcode,
			&i.Drugndc,
			&i.Drugclass,
			&i.Packagecount,
			&i.Location,
			&i.Drugco,
			&i.Drugrep,
			&i.Invoice,
			&i.Samplecount,
			&i.Samplecountremain,
			&i.Lot,
			&i.Expiration,
			&i.Received,
			&i.Assignedto,
			&i.Loguser,
			&i.Logdate,
			&i.Disposeby,
			&i.Disposedate,
			&i.Disposemethod,
			&i.Disposereason,
			&i.Witness,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
