// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: encounters.sql

package dbgen

import (
	"context"
)

const getEncounter = `-- name: GetEncounter :one
SELECT id, created_at, updated_at, deleted_at, patient, module, oid, stamp, summary, locked, annotation, user, provider, language, status
FROM patient_emr
WHERE patient = ?
  AND module = 'encounters'
  AND id = ?
`

type GetEncounterParams struct {
	PatientID   int64 `json:"patient_id"`
	EncounterID int64 `json:"encounter_id"`
}

// Encounter detail: single encounter by patient and encounter ID
func (q *Queries) GetEncounter(ctx context.Context, arg GetEncounterParams) (PatientEmr, error) {
	row := q.db.QueryRowContext(ctx, getEncounter, arg.PatientID, arg.EncounterID)
	var i PatientEmr
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Patient,
		&i.Module,
		&i.Oid,
		&i.Stamp,
		&i.Summary,
		&i.Locked,
		&i.Annotation,
		&i.User,
		&i.Provider,
		&i.Language,
		&i.Status,
	)
	return i, err
}

const listEncounters = `-- name: ListEncounters :many
SELECT id, created_at, updated_at, deleted_at, patient, module, oid, stamp, summary, locked, annotation, user, provider, language, status
FROM patient_emr
WHERE patient = ?
  AND module = 'encounters'
ORDER BY stamp DESC
`

// Encounter list: all encounters for a patient
func (q *Queries) ListEncounters(ctx context.Context, patientID int64) ([]PatientEmr, error) {
	rows, err := q.db.QueryContext(ctx, listEncounters, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatientEmr
	for rows.Next() {
		var i PatientEmr
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Patient,
			&i.Module,
			&i.Oid,
			&i.Stamp,
			&i.Summary,
			&i.Locked,
			&i.Annotation,
			&i.User,
			&i.Provider,
			&i.Language,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
