// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: eoc.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createEOC = `-- name: CreateEOC :execresult
INSERT INTO episode_of_care (
  patient, start_date, end_date, description,
  status, provider, notes, user,
  created_at, updated_at, active
) VALUES (
  ?, ?, ?,
  ?, ?, ?,
  ?, ?,
  NOW(), NOW(), 'active'
)
`

type CreateEOCParams struct {
	PatientID   int64        `json:"patient_id"`
	StartDate   time.Time    `json:"start_date"`
	EndDate     sql.NullTime `json:"end_date"`
	Description string       `json:"description"`
	Status      string       `json:"status"`
	ProviderID  int64        `json:"provider_id"`
	Notes       string       `json:"notes"`
	UserID      int64        `json:"user_id"`
}

func (q *Queries) CreateEOC(ctx context.Context, arg CreateEOCParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createEOC,
		arg.PatientID,
		arg.StartDate,
		arg.EndDate,
		arg.Description,
		arg.Status,
		arg.ProviderID,
		arg.Notes,
		arg.UserID,
	)
}

const listEOCs = `-- name: ListEOCs :many
SELECT id, created_at, updated_at, deleted_at, patient, start_date, end_date, description, status, provider, notes, user, active
FROM episode_of_care
WHERE patient = ?
  AND active = 'active'
ORDER BY start_date DESC
`

func (q *Queries) ListEOCs(ctx context.Context, patientID int64) ([]EpisodeOfCare, error) {
	rows, err := q.db.QueryContext(ctx, listEOCs, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EpisodeOfCare
	for rows.Next() {
		var i EpisodeOfCare
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Patient,
			&i.StartDate,
			&i.EndDate,
			&i.Description,
			&i.Status,
			&i.Provider,
			&i.Notes,
			&i.User,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
