// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package dbgen

import (
	"context"
)

const getEvent = `-- name: GetEvent :one
SELECT id, created_at, updated_at, deleted_at, patient, event_date, event_type, description, module, reference_id, user, active FROM events WHERE id = ? LIMIT 1
`

func (q *Queries) GetEvent(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Patient,
		&i.EventDate,
		&i.EventType,
		&i.Description,
		&i.Module,
		&i.ReferenceID,
		&i.User,
		&i.Active,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, created_at, updated_at, deleted_at, patient, event_date, event_type, description, module, reference_id, user, active FROM events ORDER BY event_date DESC
`

func (q *Queries) ListEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Patient,
			&i.EventDate,
			&i.EventType,
			&i.Description,
			&i.Module,
			&i.ReferenceID,
			&i.User,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
