// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: family_history.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createFamilyHistory = `-- name: CreateFamilyHistory :execresult
INSERT INTO family_history (patient, relationship, condition_name, icd10_code, onset_age, deceased, notes, user, active, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'active', NOW(), NOW())
`

type CreateFamilyHistoryParams struct {
	Patient       int64          `json:"patient"`
	Relationship  string         `json:"relationship"`
	ConditionName string         `json:"condition_name"`
	Icd10Code     string         `json:"icd10_code"`
	OnsetAge      int32          `json:"onset_age"`
	Deceased      bool           `json:"deceased"`
	Notes         sql.NullString `json:"notes"`
	User          int64          `json:"user"`
}

func (q *Queries) CreateFamilyHistory(ctx context.Context, arg CreateFamilyHistoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createFamilyHistory,
		arg.Patient,
		arg.Relationship,
		arg.ConditionName,
		arg.Icd10Code,
		arg.OnsetAge,
		arg.Deceased,
		arg.Notes,
		arg.User,
	)
}

const listFamilyHistory = `-- name: ListFamilyHistory :many
SELECT id, patient, relationship, condition_name, icd10_code, onset_age, deceased, notes, user, active, created_at, updated_at, deleted_at FROM family_history
WHERE patient = ? AND active = 'active'
ORDER BY created_at DESC
`

func (q *Queries) ListFamilyHistory(ctx context.Context, patient int64) ([]FamilyHistory, error) {
	rows, err := q.db.QueryContext(ctx, listFamilyHistory, patient)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FamilyHistory
	for rows.Next() {
		var i FamilyHistory
		if err := rows.Scan(
			&i.ID,
			&i.Patient,
			&i.Relationship,
			&i.ConditionName,
			&i.Icd10Code,
			&i.OnsetAge,
			&i.Deceased,
			&i.Notes,
			&i.User,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFamilyHistory = `-- name: RemoveFamilyHistory :exec
UPDATE family_history SET active = 'inactive', deleted_at = NOW(), updated_at = NOW()
WHERE id = ? AND patient = ?
`

type RemoveFamilyHistoryParams struct {
	ID      int64 `json:"id"`
	Patient int64 `json:"patient"`
}

func (q *Queries) RemoveFamilyHistory(ctx context.Context, arg RemoveFamilyHistoryParams) error {
	_, err := q.db.ExecContext(ctx, removeFamilyHistory, arg.ID, arg.Patient)
	return err
}

const updateFamilyHistory = `-- name: UpdateFamilyHistory :exec
UPDATE family_history
SET relationship = ?, condition_name = ?, icd10_code = ?, onset_age = ?, deceased = ?, notes = ?, updated_at = NOW()
WHERE id = ? AND patient = ? AND active = 'active'
`

type UpdateFamilyHistoryParams struct {
	Relationship  string         `json:"relationship"`
	ConditionName string         `json:"condition_name"`
	Icd10Code     string         `json:"icd10_code"`
	OnsetAge      int32          `json:"onset_age"`
	Deceased      bool           `json:"deceased"`
	Notes         sql.NullString `json:"notes"`
	ID            int64          `json:"id"`
	Patient       int64          `json:"patient"`
}

func (q *Queries) UpdateFamilyHistory(ctx context.Context, arg UpdateFamilyHistoryParams) error {
	_, err := q.db.ExecContext(ctx, updateFamilyHistory,
		arg.Relationship,
		arg.ConditionName,
		arg.Icd10Code,
		arg.OnsetAge,
		arg.Deceased,
		arg.Notes,
		arg.ID,
		arg.Patient,
	)
	return err
}
