// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fhir_vitals.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const fhirVitalsAll = `-- name: FhirVitalsAll :many
SELECT
  id,
  patient,
  date_taken,
  systolic,
  diastolic,
  heart_rate,
  respiratory_rate,
  temperature,
  oxygen_saturation,
  height_cm,
  weight_kg,
  bmi,
  notes,
  created_at,
  updated_at
FROM vitals
WHERE (? IS NULL OR patient = ?)
ORDER BY date_taken DESC
LIMIT 100
`

type FhirVitalsAllParams struct {
	PatientID sql.NullInt64 `json:"patient_id"`
}

type FhirVitalsAllRow struct {
	ID               int64          `json:"id"`
	Patient          int64          `json:"patient"`
	DateTaken        time.Time      `json:"date_taken"`
	Systolic         sql.NullInt32  `json:"systolic"`
	Diastolic        sql.NullInt32  `json:"diastolic"`
	HeartRate        sql.NullInt32  `json:"heart_rate"`
	RespiratoryRate  sql.NullInt32  `json:"respiratory_rate"`
	Temperature      sql.NullString `json:"temperature"`
	OxygenSaturation sql.NullInt32  `json:"oxygen_saturation"`
	HeightCm         sql.NullString `json:"height_cm"`
	WeightKg         sql.NullString `json:"weight_kg"`
	Bmi              sql.NullString `json:"bmi"`
	Notes            sql.NullString `json:"notes"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

// FHIR Observation: list all vitals (optionally filtered by patient)
func (q *Queries) FhirVitalsAll(ctx context.Context, arg FhirVitalsAllParams) ([]FhirVitalsAllRow, error) {
	rows, err := q.db.QueryContext(ctx, fhirVitalsAll, arg.PatientID, arg.PatientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FhirVitalsAllRow
	for rows.Next() {
		var i FhirVitalsAllRow
		if err := rows.Scan(
			&i.ID,
			&i.Patient,
			&i.DateTaken,
			&i.Systolic,
			&i.Diastolic,
			&i.HeartRate,
			&i.RespiratoryRate,
			&i.Temperature,
			&i.OxygenSaturation,
			&i.HeightCm,
			&i.WeightKg,
			&i.Bmi,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fhirVitalsByPatient = `-- name: FhirVitalsByPatient :many
SELECT
  id,
  patient,
  date_taken,
  systolic,
  diastolic,
  heart_rate,
  respiratory_rate,
  temperature,
  oxygen_saturation,
  height_cm,
  weight_kg,
  bmi,
  notes,
  created_at,
  updated_at
FROM vitals
WHERE patient = ?
ORDER BY date_taken DESC
`

type FhirVitalsByPatientRow struct {
	ID               int64          `json:"id"`
	Patient          int64          `json:"patient"`
	DateTaken        time.Time      `json:"date_taken"`
	Systolic         sql.NullInt32  `json:"systolic"`
	Diastolic        sql.NullInt32  `json:"diastolic"`
	HeartRate        sql.NullInt32  `json:"heart_rate"`
	RespiratoryRate  sql.NullInt32  `json:"respiratory_rate"`
	Temperature      sql.NullString `json:"temperature"`
	OxygenSaturation sql.NullInt32  `json:"oxygen_saturation"`
	HeightCm         sql.NullString `json:"height_cm"`
	WeightKg         sql.NullString `json:"weight_kg"`
	Bmi              sql.NullString `json:"bmi"`
	Notes            sql.NullString `json:"notes"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

// FHIR Observation: list vitals by patient ID
func (q *Queries) FhirVitalsByPatient(ctx context.Context, patientID int64) ([]FhirVitalsByPatientRow, error) {
	rows, err := q.db.QueryContext(ctx, fhirVitalsByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FhirVitalsByPatientRow
	for rows.Next() {
		var i FhirVitalsByPatientRow
		if err := rows.Scan(
			&i.ID,
			&i.Patient,
			&i.DateTaken,
			&i.Systolic,
			&i.Diastolic,
			&i.HeartRate,
			&i.RespiratoryRate,
			&i.Temperature,
			&i.OxygenSaturation,
			&i.HeightCm,
			&i.WeightKg,
			&i.Bmi,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
