// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fhir_family_history.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const fhirFamilyHistoryById = `-- name: FhirFamilyHistoryById :one
SELECT
  id,
  patient,
  relationship,
  condition_name,
  icd10_code,
  onset_age,
  deceased,
  notes,
  user,
  active,
  created_at,
  updated_at
FROM family_history
WHERE id = ?
  AND active = 'active'
  AND deleted_at IS NULL
`

type FhirFamilyHistoryByIdRow struct {
	ID            int64          `json:"id"`
	Patient       int64          `json:"patient"`
	Relationship  string         `json:"relationship"`
	ConditionName string         `json:"condition_name"`
	Icd10Code     string         `json:"icd10_code"`
	OnsetAge      int32          `json:"onset_age"`
	Deceased      bool           `json:"deceased"`
	Notes         sql.NullString `json:"notes"`
	User          int64          `json:"user"`
	Active        string         `json:"active"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

// FHIR FamilyMemberHistory: get a single family history record by ID
func (q *Queries) FhirFamilyHistoryById(ctx context.Context, familyHistoryID int64) (FhirFamilyHistoryByIdRow, error) {
	row := q.db.QueryRowContext(ctx, fhirFamilyHistoryById, familyHistoryID)
	var i FhirFamilyHistoryByIdRow
	err := row.Scan(
		&i.ID,
		&i.Patient,
		&i.Relationship,
		&i.ConditionName,
		&i.Icd10Code,
		&i.OnsetAge,
		&i.Deceased,
		&i.Notes,
		&i.User,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const fhirFamilyHistoryByPatient = `-- name: FhirFamilyHistoryByPatient :many
SELECT
  id,
  patient,
  relationship,
  condition_name,
  icd10_code,
  onset_age,
  deceased,
  notes,
  user,
  active,
  created_at,
  updated_at
FROM family_history
WHERE patient = ?
  AND active = 'active'
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

type FhirFamilyHistoryByPatientRow struct {
	ID            int64          `json:"id"`
	Patient       int64          `json:"patient"`
	Relationship  string         `json:"relationship"`
	ConditionName string         `json:"condition_name"`
	Icd10Code     string         `json:"icd10_code"`
	OnsetAge      int32          `json:"onset_age"`
	Deceased      bool           `json:"deceased"`
	Notes         sql.NullString `json:"notes"`
	User          int64          `json:"user"`
	Active        string         `json:"active"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

// FHIR FamilyMemberHistory: list all family history for a patient
func (q *Queries) FhirFamilyHistoryByPatient(ctx context.Context, patientID int64) ([]FhirFamilyHistoryByPatientRow, error) {
	rows, err := q.db.QueryContext(ctx, fhirFamilyHistoryByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FhirFamilyHistoryByPatientRow
	for rows.Next() {
		var i FhirFamilyHistoryByPatientRow
		if err := rows.Scan(
			&i.ID,
			&i.Patient,
			&i.Relationship,
			&i.ConditionName,
			&i.Icd10Code,
			&i.OnsetAge,
			&i.Deceased,
			&i.Notes,
			&i.User,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
