// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fhir_allergy.sql

package dbgen

import (
	"context"
	"time"
)

const fhirAllergiesByPatient = `-- name: FhirAllergiesByPatient :many
SELECT
  id,
  patient,
  active,
  created_at,
  updated_at
FROM allergies
WHERE patient = ?
  AND active = 'active'
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

type FhirAllergiesByPatientRow struct {
	ID        int64     `json:"id"`
	Patient   int64     `json:"patient"`
	Active    string    `json:"active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// FHIR AllergyIntolerance: list active allergies for a patient
func (q *Queries) FhirAllergiesByPatient(ctx context.Context, patientID int64) ([]FhirAllergiesByPatientRow, error) {
	rows, err := q.db.QueryContext(ctx, fhirAllergiesByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FhirAllergiesByPatientRow
	for rows.Next() {
		var i FhirAllergiesByPatientRow
		if err := rows.Scan(
			&i.ID,
			&i.Patient,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fhirAllergyById = `-- name: FhirAllergyById :one
SELECT
  id,
  patient,
  active,
  created_at,
  updated_at
FROM allergies
WHERE id = ?
  AND deleted_at IS NULL
`

type FhirAllergyByIdRow struct {
	ID        int64     `json:"id"`
	Patient   int64     `json:"patient"`
	Active    string    `json:"active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// FHIR AllergyIntolerance: lookup a single allergy by ID
func (q *Queries) FhirAllergyById(ctx context.Context, allergyID int64) (FhirAllergyByIdRow, error) {
	row := q.db.QueryRowContext(ctx, fhirAllergyById, allergyID)
	var i FhirAllergyByIdRow
	err := row.Scan(
		&i.ID,
		&i.Patient,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
