// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fhir_social_history.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const fhirSocialHistoryObservations = `-- name: FhirSocialHistoryObservations :many
SELECT
  id,
  patient,
  smoking_status,
  smoking_detail,
  alcohol_use,
  alcohol_detail,
  drug_use,
  drug_detail,
  exercise_frequency,
  occupation,
  living_situation,
  food_insecurity,
  transportation_access,
  notes,
  recorded_date,
  user,
  active,
  created_at,
  updated_at
FROM social_history
WHERE patient = ?
  AND active = 'active'
  AND deleted_at IS NULL
ORDER BY recorded_date DESC
`

type FhirSocialHistoryObservationsRow struct {
	ID                   int64          `json:"id"`
	Patient              int64          `json:"patient"`
	SmokingStatus        string         `json:"smoking_status"`
	SmokingDetail        string         `json:"smoking_detail"`
	AlcoholUse           string         `json:"alcohol_use"`
	AlcoholDetail        string         `json:"alcohol_detail"`
	DrugUse              string         `json:"drug_use"`
	DrugDetail           string         `json:"drug_detail"`
	ExerciseFrequency    string         `json:"exercise_frequency"`
	Occupation           string         `json:"occupation"`
	LivingSituation      string         `json:"living_situation"`
	FoodInsecurity       bool           `json:"food_insecurity"`
	TransportationAccess bool           `json:"transportation_access"`
	Notes                sql.NullString `json:"notes"`
	RecordedDate         time.Time      `json:"recorded_date"`
	User                 int64          `json:"user"`
	Active               string         `json:"active"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
}

// FHIR Observation: social history observations for a patient
func (q *Queries) FhirSocialHistoryObservations(ctx context.Context, patientID int64) ([]FhirSocialHistoryObservationsRow, error) {
	rows, err := q.db.QueryContext(ctx, fhirSocialHistoryObservations, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FhirSocialHistoryObservationsRow
	for rows.Next() {
		var i FhirSocialHistoryObservationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Patient,
			&i.SmokingStatus,
			&i.SmokingDetail,
			&i.AlcoholUse,
			&i.AlcoholDetail,
			&i.DrugUse,
			&i.DrugDetail,
			&i.ExerciseFrequency,
			&i.Occupation,
			&i.LivingSituation,
			&i.FoodInsecurity,
			&i.TransportationAccess,
			&i.Notes,
			&i.RecordedDate,
			&i.User,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
