// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fhir_medication_request.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const fhirMedicationRequestById = `-- name: FhirMedicationRequestById :one
SELECT
  id,
  patient,
  drug_name,
  dosage,
  frequency,
  quantity,
  refills,
  date_written,
  prescribing_provider,
  pharmacy,
  status,
  notes,
  created_at,
  updated_at
FROM prescriptions
WHERE id = ?
  AND deleted_at IS NULL
`

type FhirMedicationRequestByIdRow struct {
	ID                  int64          `json:"id"`
	Patient             int64          `json:"patient"`
	DrugName            string         `json:"drug_name"`
	Dosage              string         `json:"dosage"`
	Frequency           string         `json:"frequency"`
	Quantity            string         `json:"quantity"`
	Refills             int64          `json:"refills"`
	DateWritten         time.Time      `json:"date_written"`
	PrescribingProvider int64          `json:"prescribing_provider"`
	Pharmacy            string         `json:"pharmacy"`
	Status              string         `json:"status"`
	Notes               sql.NullString `json:"notes"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
}

// FHIR MedicationRequest: lookup a single prescription by ID
func (q *Queries) FhirMedicationRequestById(ctx context.Context, prescriptionID int64) (FhirMedicationRequestByIdRow, error) {
	row := q.db.QueryRowContext(ctx, fhirMedicationRequestById, prescriptionID)
	var i FhirMedicationRequestByIdRow
	err := row.Scan(
		&i.ID,
		&i.Patient,
		&i.DrugName,
		&i.Dosage,
		&i.Frequency,
		&i.Quantity,
		&i.Refills,
		&i.DateWritten,
		&i.PrescribingProvider,
		&i.Pharmacy,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const fhirMedicationRequestsByPatient = `-- name: FhirMedicationRequestsByPatient :many
SELECT
  id,
  patient,
  drug_name,
  dosage,
  frequency,
  quantity,
  refills,
  date_written,
  prescribing_provider,
  pharmacy,
  status,
  notes,
  created_at,
  updated_at
FROM prescriptions
WHERE patient = ?
  AND deleted_at IS NULL
ORDER BY date_written DESC
`

type FhirMedicationRequestsByPatientRow struct {
	ID                  int64          `json:"id"`
	Patient             int64          `json:"patient"`
	DrugName            string         `json:"drug_name"`
	Dosage              string         `json:"dosage"`
	Frequency           string         `json:"frequency"`
	Quantity            string         `json:"quantity"`
	Refills             int64          `json:"refills"`
	DateWritten         time.Time      `json:"date_written"`
	PrescribingProvider int64          `json:"prescribing_provider"`
	Pharmacy            string         `json:"pharmacy"`
	Status              string         `json:"status"`
	Notes               sql.NullString `json:"notes"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
}

// FHIR MedicationRequest: list prescriptions for a patient
func (q *Queries) FhirMedicationRequestsByPatient(ctx context.Context, patientID int64) ([]FhirMedicationRequestsByPatientRow, error) {
	rows, err := q.db.QueryContext(ctx, fhirMedicationRequestsByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FhirMedicationRequestsByPatientRow
	for rows.Next() {
		var i FhirMedicationRequestsByPatientRow
		if err := rows.Scan(
			&i.ID,
			&i.Patient,
			&i.DrugName,
			&i.Dosage,
			&i.Frequency,
			&i.Quantity,
			&i.Refills,
			&i.DateWritten,
			&i.PrescribingProvider,
			&i.Pharmacy,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
