// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fhir_procedure.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const fhirProcedureById = `-- name: FhirProcedureById :one
SELECT
  id,
  patient,
  operation_date,
  operation,
  user,
  created_at,
  updated_at
FROM previous_operations
WHERE id = ?
  AND deleted_at IS NULL
`

type FhirProcedureByIdRow struct {
	ID            int64        `json:"id"`
	Patient       int64        `json:"patient"`
	OperationDate sql.NullTime `json:"operation_date"`
	Operation     string       `json:"operation"`
	User          int64        `json:"user"`
	CreatedAt     time.Time    `json:"created_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
}

// FHIR Procedure: lookup a single procedure by ID
func (q *Queries) FhirProcedureById(ctx context.Context, procedureID int64) (FhirProcedureByIdRow, error) {
	row := q.db.QueryRowContext(ctx, fhirProcedureById, procedureID)
	var i FhirProcedureByIdRow
	err := row.Scan(
		&i.ID,
		&i.Patient,
		&i.OperationDate,
		&i.Operation,
		&i.User,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const fhirProceduresByPatient = `-- name: FhirProceduresByPatient :many
SELECT
  id,
  patient,
  operation_date,
  operation,
  user,
  created_at,
  updated_at
FROM previous_operations
WHERE patient = ?
  AND deleted_at IS NULL
ORDER BY operation_date DESC
`

type FhirProceduresByPatientRow struct {
	ID            int64        `json:"id"`
	Patient       int64        `json:"patient"`
	OperationDate sql.NullTime `json:"operation_date"`
	Operation     string       `json:"operation"`
	User          int64        `json:"user"`
	CreatedAt     time.Time    `json:"created_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
}

// FHIR Procedure: list procedures (previous_operations) for a patient
func (q *Queries) FhirProceduresByPatient(ctx context.Context, patientID int64) ([]FhirProceduresByPatientRow, error) {
	rows, err := q.db.QueryContext(ctx, fhirProceduresByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FhirProceduresByPatientRow
	for rows.Next() {
		var i FhirProceduresByPatientRow
		if err := rows.Scan(
			&i.ID,
			&i.Patient,
			&i.OperationDate,
			&i.Operation,
			&i.User,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
