// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fhir_immunization.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const fhirImmunizationById = `-- name: FhirImmunizationById :one
SELECT
  id,
  patient,
  dateof,
  provider,
  admin_provider,
  eoc,
  immunization,
  route,
  body_site,
  manufacturer,
  lot_number,
  previous_doses,
  recovered,
  notes,
  orderid,
  locked,
  user,
  active,
  created_at,
  updated_at
FROM immunization
WHERE id = ?
  AND deleted_at IS NULL
`

type FhirImmunizationByIdRow struct {
	ID            int64          `json:"id"`
	Patient       int64          `json:"patient"`
	Dateof        time.Time      `json:"dateof"`
	Provider      int64          `json:"provider"`
	AdminProvider int64          `json:"admin_provider"`
	Eoc           sql.NullInt64  `json:"eoc"`
	Immunization  int64          `json:"immunization"`
	Route         int64          `json:"route"`
	BodySite      int64          `json:"body_site"`
	Manufacturer  sql.NullString `json:"manufacturer"`
	LotNumber     sql.NullString `json:"lot_number"`
	PreviousDoses int64          `json:"previous_doses"`
	Recovered     bool           `json:"recovered"`
	Notes         sql.NullString `json:"notes"`
	Orderid       int64          `json:"orderid"`
	Locked        int64          `json:"locked"`
	User          int64          `json:"user"`
	Active        string         `json:"active"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

// FHIR Immunization: lookup a single immunization by ID
func (q *Queries) FhirImmunizationById(ctx context.Context, immunizationID int64) (FhirImmunizationByIdRow, error) {
	row := q.db.QueryRowContext(ctx, fhirImmunizationById, immunizationID)
	var i FhirImmunizationByIdRow
	err := row.Scan(
		&i.ID,
		&i.Patient,
		&i.Dateof,
		&i.Provider,
		&i.AdminProvider,
		&i.Eoc,
		&i.Immunization,
		&i.Route,
		&i.BodySite,
		&i.Manufacturer,
		&i.LotNumber,
		&i.PreviousDoses,
		&i.Recovered,
		&i.Notes,
		&i.Orderid,
		&i.Locked,
		&i.User,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const fhirImmunizationsByPatient = `-- name: FhirImmunizationsByPatient :many
SELECT
  id,
  patient,
  dateof,
  provider,
  admin_provider,
  eoc,
  immunization,
  route,
  body_site,
  manufacturer,
  lot_number,
  previous_doses,
  recovered,
  notes,
  orderid,
  locked,
  user,
  active,
  created_at,
  updated_at
FROM immunization
WHERE patient = ?
  AND active = 'active'
  AND deleted_at IS NULL
ORDER BY dateof DESC
`

type FhirImmunizationsByPatientRow struct {
	ID            int64          `json:"id"`
	Patient       int64          `json:"patient"`
	Dateof        time.Time      `json:"dateof"`
	Provider      int64          `json:"provider"`
	AdminProvider int64          `json:"admin_provider"`
	Eoc           sql.NullInt64  `json:"eoc"`
	Immunization  int64          `json:"immunization"`
	Route         int64          `json:"route"`
	BodySite      int64          `json:"body_site"`
	Manufacturer  sql.NullString `json:"manufacturer"`
	LotNumber     sql.NullString `json:"lot_number"`
	PreviousDoses int64          `json:"previous_doses"`
	Recovered     bool           `json:"recovered"`
	Notes         sql.NullString `json:"notes"`
	Orderid       int64          `json:"orderid"`
	Locked        int64          `json:"locked"`
	User          int64          `json:"user"`
	Active        string         `json:"active"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

// FHIR Immunization: list immunizations for a patient
func (q *Queries) FhirImmunizationsByPatient(ctx context.Context, patientID int64) ([]FhirImmunizationsByPatientRow, error) {
	rows, err := q.db.QueryContext(ctx, fhirImmunizationsByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FhirImmunizationsByPatientRow
	for rows.Next() {
		var i FhirImmunizationsByPatientRow
		if err := rows.Scan(
			&i.ID,
			&i.Patient,
			&i.Dateof,
			&i.Provider,
			&i.AdminProvider,
			&i.Eoc,
			&i.Immunization,
			&i.Route,
			&i.BodySite,
			&i.Manufacturer,
			&i.LotNumber,
			&i.PreviousDoses,
			&i.Recovered,
			&i.Notes,
			&i.Orderid,
			&i.Locked,
			&i.User,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
