// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fhir_encounter.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const fhirEncounterById = `-- name: FhirEncounterById :one
SELECT
  id,
  procpatient AS patient,
  proceoc AS eoc,
  proccpt AS cpt,
  proccptmod AS cpt_mod,
  procphysician AS physician,
  procdt AS encounter_date,
  procdtend AS encounter_end_date,
  procpos AS place_of_service,
  proccomment AS comment,
  created_at,
  updated_at
FROM procrec
WHERE id = ?
  AND deleted_at IS NULL
`

type FhirEncounterByIdRow struct {
	ID               int64          `json:"id"`
	Patient          int64          `json:"patient"`
	Eoc              sql.NullString `json:"eoc"`
	Cpt              int64          `json:"cpt"`
	CptMod           int64          `json:"cpt_mod"`
	Physician        int64          `json:"physician"`
	EncounterDate    time.Time      `json:"encounter_date"`
	EncounterEndDate sql.NullTime   `json:"encounter_end_date"`
	PlaceOfService   int64          `json:"place_of_service"`
	Comment          sql.NullString `json:"comment"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

// FHIR Encounter: lookup a single encounter by ID
func (q *Queries) FhirEncounterById(ctx context.Context, encounterID int64) (FhirEncounterByIdRow, error) {
	row := q.db.QueryRowContext(ctx, fhirEncounterById, encounterID)
	var i FhirEncounterByIdRow
	err := row.Scan(
		&i.ID,
		&i.Patient,
		&i.Eoc,
		&i.Cpt,
		&i.CptMod,
		&i.Physician,
		&i.EncounterDate,
		&i.EncounterEndDate,
		&i.PlaceOfService,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const fhirEncountersByPatient = `-- name: FhirEncountersByPatient :many
SELECT
  id,
  procpatient AS patient,
  proceoc AS eoc,
  proccpt AS cpt,
  proccptmod AS cpt_mod,
  procphysician AS physician,
  procdt AS encounter_date,
  procdtend AS encounter_end_date,
  procpos AS place_of_service,
  proccomment AS comment,
  created_at,
  updated_at
FROM procrec
WHERE procpatient = ?
  AND deleted_at IS NULL
ORDER BY procdt DESC
`

type FhirEncountersByPatientRow struct {
	ID               int64          `json:"id"`
	Patient          int64          `json:"patient"`
	Eoc              sql.NullString `json:"eoc"`
	Cpt              int64          `json:"cpt"`
	CptMod           int64          `json:"cpt_mod"`
	Physician        int64          `json:"physician"`
	EncounterDate    time.Time      `json:"encounter_date"`
	EncounterEndDate sql.NullTime   `json:"encounter_end_date"`
	PlaceOfService   int64          `json:"place_of_service"`
	Comment          sql.NullString `json:"comment"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

// FHIR Encounter: list encounters (procrec) for a patient
func (q *Queries) FhirEncountersByPatient(ctx context.Context, patientID int64) ([]FhirEncountersByPatientRow, error) {
	rows, err := q.db.QueryContext(ctx, fhirEncountersByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FhirEncountersByPatientRow
	for rows.Next() {
		var i FhirEncountersByPatientRow
		if err := rows.Scan(
			&i.ID,
			&i.Patient,
			&i.Eoc,
			&i.Cpt,
			&i.CptMod,
			&i.Physician,
			&i.EncounterDate,
			&i.EncounterEndDate,
			&i.PlaceOfService,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
