// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fhir_condition.sql

package dbgen

import (
	"context"
	"time"
)

const fhirConditionById = `-- name: FhirConditionById :one
SELECT
  cp.id AS condition_id,
  cp.patient AS condition_patient,
  cp.date AS condition_date,
  cp.problem AS condition_text,
  'current' AS condition_type,
  cp.active AS condition_active,
  cp.updated_at AS condition_updated
FROM current_problems cp
WHERE cp.id = ?
  AND cp.deleted_at IS NULL
UNION ALL
SELECT
  ch.id AS condition_id,
  ch.patient AS condition_patient,
  ch.date AS condition_date,
  ch.problem AS condition_text,
  'chronic' AS condition_type,
  NULL AS condition_active,
  ch.updated_at AS condition_updated
FROM chronic_problems ch
WHERE ch.id = ?
  AND ch.deleted_at IS NULL
LIMIT 1
`

type FhirConditionByIdParams struct {
	ConditionID int64 `json:"condition_id"`
}

type FhirConditionByIdRow struct {
	ConditionID      int64     `json:"condition_id"`
	ConditionPatient int64     `json:"condition_patient"`
	ConditionDate    time.Time `json:"condition_date"`
	ConditionText    string    `json:"condition_text"`
	ConditionType    string    `json:"condition_type"`
	ConditionActive  string    `json:"condition_active"`
	ConditionUpdated time.Time `json:"condition_updated"`
}

// FHIR Condition: lookup a single problem by ID (check current first, then chronic)
func (q *Queries) FhirConditionById(ctx context.Context, arg FhirConditionByIdParams) (FhirConditionByIdRow, error) {
	row := q.db.QueryRowContext(ctx, fhirConditionById, arg.ConditionID, arg.ConditionID)
	var i FhirConditionByIdRow
	err := row.Scan(
		&i.ConditionID,
		&i.ConditionPatient,
		&i.ConditionDate,
		&i.ConditionText,
		&i.ConditionType,
		&i.ConditionActive,
		&i.ConditionUpdated,
	)
	return i, err
}

const fhirConditionsByPatient = `-- name: FhirConditionsByPatient :many
SELECT
  cp.id AS condition_id,
  cp.patient AS condition_patient,
  cp.date AS condition_date,
  cp.problem AS condition_text,
  'current' AS condition_type,
  cp.active AS condition_active,
  cp.updated_at AS condition_updated
FROM current_problems cp
WHERE cp.patient = ?
  AND cp.deleted_at IS NULL
UNION ALL
SELECT
  ch.id AS condition_id,
  ch.patient AS condition_patient,
  ch.date AS condition_date,
  ch.problem AS condition_text,
  'chronic' AS condition_type,
  NULL AS condition_active,
  ch.updated_at AS condition_updated
FROM chronic_problems ch
WHERE ch.patient = ?
  AND ch.deleted_at IS NULL
ORDER BY condition_date DESC
`

type FhirConditionsByPatientParams struct {
	PatientID int64 `json:"patient_id"`
}

type FhirConditionsByPatientRow struct {
	ConditionID      int64     `json:"condition_id"`
	ConditionPatient int64     `json:"condition_patient"`
	ConditionDate    time.Time `json:"condition_date"`
	ConditionText    string    `json:"condition_text"`
	ConditionType    string    `json:"condition_type"`
	ConditionActive  string    `json:"condition_active"`
	ConditionUpdated time.Time `json:"condition_updated"`
}

// FHIR Condition: list all problems (current + chronic) for a patient
func (q *Queries) FhirConditionsByPatient(ctx context.Context, arg FhirConditionsByPatientParams) ([]FhirConditionsByPatientRow, error) {
	rows, err := q.db.QueryContext(ctx, fhirConditionsByPatient, arg.PatientID, arg.PatientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FhirConditionsByPatientRow
	for rows.Next() {
		var i FhirConditionsByPatientRow
		if err := rows.Scan(
			&i.ConditionID,
			&i.ConditionPatient,
			&i.ConditionDate,
			&i.ConditionText,
			&i.ConditionType,
			&i.ConditionActive,
			&i.ConditionUpdated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
