// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fhir_patient.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const fhirPatientById = `-- name: FhirPatientById :one
SELECT
  p.id,
  p.ptlname,
  p.ptfname,
  p.ptmname,
  p.ptsuffix,
  p.ptsalut,
  p.ptsex,
  p.ptdob,
  p.ptid,
  p.pemail,
  p.ptblood,
  p.ssn,
  p.ptprimarylanguage,
  p.ptdead,
  p.ptdeaddt,
  p.ptpcp,
  p.created_at,
  p.updated_at,
  pa.line1   AS address_line1,
  pa.line2   AS address_line2,
  pa.city    AS address_city,
  pa.stpr    AS address_state,
  pa.postal  AS address_postal
FROM patient p
LEFT OUTER JOIN patient_address pa ON pa.patient = p.id AND pa.active = 1
WHERE p.id = ?
  AND p.ptarchive = 0
`

type FhirPatientByIdRow struct {
	ID                int64          `json:"id"`
	Ptlname           string         `json:"ptlname"`
	Ptfname           string         `json:"ptfname"`
	Ptmname           sql.NullString `json:"ptmname"`
	Ptsuffix          string         `json:"ptsuffix"`
	Ptsalut           string         `json:"ptsalut"`
	Ptsex             string         `json:"ptsex"`
	Ptdob             sql.NullTime   `json:"ptdob"`
	Ptid              string         `json:"ptid"`
	Pemail            sql.NullString `json:"pemail"`
	Ptblood           string         `json:"ptblood"`
	Ssn               sql.NullString `json:"ssn"`
	Ptprimarylanguage string         `json:"ptprimarylanguage"`
	Ptdead            int64          `json:"ptdead"`
	Ptdeaddt          sql.NullTime   `json:"ptdeaddt"`
	Ptpcp             int64          `json:"ptpcp"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	AddressLine1      sql.NullString `json:"address_line1"`
	AddressLine2      sql.NullString `json:"address_line2"`
	AddressCity       sql.NullString `json:"address_city"`
	AddressState      sql.NullString `json:"address_state"`
	AddressPostal     sql.NullString `json:"address_postal"`
}

// FHIR Patient: get patient by ID with address join for FHIR Patient resource
func (q *Queries) FhirPatientById(ctx context.Context, patientID int64) (FhirPatientByIdRow, error) {
	row := q.db.QueryRowContext(ctx, fhirPatientById, patientID)
	var i FhirPatientByIdRow
	err := row.Scan(
		&i.ID,
		&i.Ptlname,
		&i.Ptfname,
		&i.Ptmname,
		&i.Ptsuffix,
		&i.Ptsalut,
		&i.Ptsex,
		&i.Ptdob,
		&i.Ptid,
		&i.Pemail,
		&i.Ptblood,
		&i.Ssn,
		&i.Ptprimarylanguage,
		&i.Ptdead,
		&i.Ptdeaddt,
		&i.Ptpcp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.AddressCity,
		&i.AddressState,
		&i.AddressPostal,
	)
	return i, err
}
