// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: financial_demographics.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createFinancialDemographics = `-- name: CreateFinancialDemographics :execresult
INSERT INTO financial_demographics (
  created_at, updated_at, patient, income, id_type,
  id_issuer, id_number, id_expire, household_size,
  spouse, children, other_dependents, free_text,
  entry_desc, entry_ts, user, active
) VALUES (
  NOW(), NOW(), ?, ?, ?,
  ?, ?, ?,
  ?,
  ?, ?, ?,
  ?,
  ?, NOW(), ?, 'active'
)
`

type CreateFinancialDemographicsParams struct {
	PatientID       int64          `json:"patient_id"`
	Income          int32          `json:"income"`
	IDType          string         `json:"id_type"`
	IDIssuer        string         `json:"id_issuer"`
	IDNumber        string         `json:"id_number"`
	IDExpire        string         `json:"id_expire"`
	HouseholdSize   int32          `json:"household_size"`
	Spouse          int32          `json:"spouse"`
	Children        int32          `json:"children"`
	OtherDependents int32          `json:"other_dependents"`
	FreeText        sql.NullString `json:"free_text"`
	EntryDesc       string         `json:"entry_desc"`
	UserID          int64          `json:"user_id"`
}

func (q *Queries) CreateFinancialDemographics(ctx context.Context, arg CreateFinancialDemographicsParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createFinancialDemographics,
		arg.PatientID,
		arg.Income,
		arg.IDType,
		arg.IDIssuer,
		arg.IDNumber,
		arg.IDExpire,
		arg.HouseholdSize,
		arg.Spouse,
		arg.Children,
		arg.OtherDependents,
		arg.FreeText,
		arg.EntryDesc,
		arg.UserID,
	)
}

const listFinancialDemographicsByPatient = `-- name: ListFinancialDemographicsByPatient :many
SELECT id, created_at, updated_at, deleted_at, patient, income, id_type, id_issuer, id_number, id_expire, household_size, spouse, children, other_dependents, free_text, entry_desc, entry_ts, user, active FROM financial_demographics
WHERE patient = ?
  AND active = 'active'
  AND deleted_at IS NULL
ORDER BY id DESC
`

func (q *Queries) ListFinancialDemographicsByPatient(ctx context.Context, patientID int64) ([]FinancialDemographic, error) {
	rows, err := q.db.QueryContext(ctx, listFinancialDemographicsByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FinancialDemographic
	for rows.Next() {
		var i FinancialDemographic
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Patient,
			&i.Income,
			&i.IDType,
			&i.IDIssuer,
			&i.IDNumber,
			&i.IDExpire,
			&i.HouseholdSize,
			&i.Spouse,
			&i.Children,
			&i.OtherDependents,
			&i.FreeText,
			&i.EntryDesc,
			&i.EntryTs,
			&i.User,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
