// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: form_record.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createFormRecord = `-- name: CreateFormRecord :execresult
INSERT INTO form_record (created_at, updated_at, fr_id, fr_uuid, fr_name, fr_value)
VALUES (NOW(), NOW(), ?, ?, ?, ?)
`

type CreateFormRecordParams struct {
	FrID    int64          `json:"fr_id"`
	FrUuid  string         `json:"fr_uuid"`
	FrName  string         `json:"fr_name"`
	FrValue sql.NullString `json:"fr_value"`
}

func (q *Queries) CreateFormRecord(ctx context.Context, arg CreateFormRecordParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createFormRecord,
		arg.FrID,
		arg.FrUuid,
		arg.FrName,
		arg.FrValue,
	)
}

const deleteFormRecords = `-- name: DeleteFormRecords :exec
UPDATE form_record SET updated_at = NOW(), deleted_at = NOW() WHERE fr_id = ? AND deleted_at IS NULL
`

func (q *Queries) DeleteFormRecords(ctx context.Context, frID int64) error {
	_, err := q.db.ExecContext(ctx, deleteFormRecords, frID)
	return err
}

const listFormRecords = `-- name: ListFormRecords :many
SELECT id, created_at, updated_at, deleted_at, fr_id, fr_uuid, fr_name, fr_value FROM form_record WHERE fr_id = ? AND deleted_at IS NULL ORDER BY id
`

func (q *Queries) ListFormRecords(ctx context.Context, formID int64) ([]FormRecord, error) {
	rows, err := q.db.QueryContext(ctx, listFormRecords, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FormRecord
	for rows.Next() {
		var i FormRecord
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.FrID,
			&i.FrUuid,
			&i.FrName,
			&i.FrValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFormRecord = `-- name: UpdateFormRecord :exec
UPDATE form_record SET updated_at = NOW(), fr_value = ? WHERE fr_id = ? AND fr_uuid = ? AND deleted_at IS NULL
`

type UpdateFormRecordParams struct {
	FrValue sql.NullString `json:"fr_value"`
	FrID    int64          `json:"fr_id"`
	FrUuid  string         `json:"fr_uuid"`
}

func (q *Queries) UpdateFormRecord(ctx context.Context, arg UpdateFormRecordParams) error {
	_, err := q.db.ExecContext(ctx, updateFormRecord, arg.FrValue, arg.FrID, arg.FrUuid)
	return err
}
