// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: form_templates.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createFormTemplate = `-- name: CreateFormTemplate :execresult
INSERT INTO form_templates (
  name, description, form_type, template_data, is_default, user,
  created_at, updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?,
  NOW(), NOW()
)
`

type CreateFormTemplateParams struct {
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	FormType     string         `json:"form_type"`
	TemplateData sql.NullString `json:"template_data"`
	IsDefault    bool           `json:"is_default"`
	User         int64          `json:"user"`
}

func (q *Queries) CreateFormTemplate(ctx context.Context, arg CreateFormTemplateParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createFormTemplate,
		arg.Name,
		arg.Description,
		arg.FormType,
		arg.TemplateData,
		arg.IsDefault,
		arg.User,
	)
}

const deleteFormTemplate = `-- name: DeleteFormTemplate :exec
DELETE FROM form_templates WHERE id = ?
`

func (q *Queries) DeleteFormTemplate(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFormTemplate, id)
	return err
}

const getFormTemplate = `-- name: GetFormTemplate :one
SELECT id, created_at, updated_at, deleted_at, name, description, form_type, template_data, is_default, user FROM form_templates WHERE id = ?
`

func (q *Queries) GetFormTemplate(ctx context.Context, id int64) (FormTemplate, error) {
	row := q.db.QueryRowContext(ctx, getFormTemplate, id)
	var i FormTemplate
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Description,
		&i.FormType,
		&i.TemplateData,
		&i.IsDefault,
		&i.User,
	)
	return i, err
}

const listFormTemplates = `-- name: ListFormTemplates :many
SELECT id, created_at, updated_at, deleted_at, name, description, form_type, template_data, is_default, user FROM form_templates ORDER BY name
`

func (q *Queries) ListFormTemplates(ctx context.Context) ([]FormTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listFormTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FormTemplate
	for rows.Next() {
		var i FormTemplate
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.Description,
			&i.FormType,
			&i.TemplateData,
			&i.IsDefault,
			&i.User,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFormTemplate = `-- name: UpdateFormTemplate :exec
UPDATE form_templates SET
  name = ?,
  description = ?,
  form_type = ?,
  template_data = ?,
  is_default = ?,
  updated_at = NOW()
WHERE id = ?
`

type UpdateFormTemplateParams struct {
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	FormType     string         `json:"form_type"`
	TemplateData sql.NullString `json:"template_data"`
	IsDefault    bool           `json:"is_default"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateFormTemplate(ctx context.Context, arg UpdateFormTemplateParams) error {
	_, err := q.db.ExecContext(ctx, updateFormTemplate,
		arg.Name,
		arg.Description,
		arg.FormType,
		arg.TemplateData,
		arg.IsDefault,
		arg.ID,
	)
	return err
}
