// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: history.sql

package dbgen

import (
	"context"
	"time"
)

const patientHistory = `-- name: PatientHistory :many
SELECT 'encounter' AS entry_type, pe.stamp AS event_date, pe.summary AS description, pe.id
FROM patient_emr pe WHERE pe.patient = ?
UNION ALL
SELECT 'procedure' AS entry_type, pr.procdt AS event_date, c.cptnameext AS description, pr.id
FROM procrec pr LEFT JOIN cpt c ON pr.proccpt = c.id WHERE pr.procpatient = ?
UNION ALL
SELECT 'note' AS entry_type, pn.pnotesdt AS event_date, pn.pnotesdescrip AS description, pn.id
FROM pnotes pn WHERE pn.pnotespat = ?
ORDER BY event_date DESC LIMIT 50
`

type PatientHistoryParams struct {
	PatientID int64 `json:"patient_id"`
}

type PatientHistoryRow struct {
	EntryType   string    `json:"entry_type"`
	EventDate   time.Time `json:"event_date"`
	Description string    `json:"description"`
	ID          int64     `json:"id"`
}

// Combined timeline of encounters, procedures, and notes for a patient
func (q *Queries) PatientHistory(ctx context.Context, arg PatientHistoryParams) ([]PatientHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, patientHistory, arg.PatientID, arg.PatientID, arg.PatientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatientHistoryRow
	for rows.Next() {
		var i PatientHistoryRow
		if err := rows.Scan(
			&i.EntryType,
			&i.EventDate,
			&i.Description,
			&i.ID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
