// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: holiday.sql

package dbgen

import (
	"context"
	"time"
)

const checkHoliday = `-- name: CheckHoliday :one
SELECT id, created_at, updated_at, deleted_at, holiday_date, holiday_name, description, active FROM holiday WHERE holiday_date = ? LIMIT 1
`

func (q *Queries) CheckHoliday(ctx context.Context, holidayDate time.Time) (Holiday, error) {
	row := q.db.QueryRowContext(ctx, checkHoliday, holidayDate)
	var i Holiday
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HolidayDate,
		&i.HolidayName,
		&i.Description,
		&i.Active,
	)
	return i, err
}

const listHolidays = `-- name: ListHolidays :many
SELECT id, created_at, updated_at, deleted_at, holiday_date, holiday_name, description, active FROM holiday ORDER BY holiday_date
`

func (q *Queries) ListHolidays(ctx context.Context) ([]Holiday, error) {
	rows, err := q.db.QueryContext(ctx, listHolidays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Holiday
	for rows.Next() {
		var i Holiday
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.HolidayDate,
			&i.HolidayName,
			&i.Description,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
