// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: immunizations.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createImmunization = `-- name: CreateImmunization :execresult
INSERT INTO immunization (
  created_at, updated_at, dateof, patient, provider,
  admin_provider, immunization, route, body_site,
  manufacturer, lot_number, previous_doses, recovered, notes, user, active
) VALUES (
  NOW(), NOW(), ?, ?,
  ?, ?,
  ?, ?, ?,
  ?, ?,
  ?, ?,
  ?, ?, 'active'
)
`

type CreateImmunizationParams struct {
	Dateof        time.Time      `json:"dateof"`
	PatientID     int64          `json:"patient_id"`
	Provider      int64          `json:"provider"`
	AdminProvider int64          `json:"admin_provider"`
	Immunization  int64          `json:"immunization"`
	Route         int64          `json:"route"`
	BodySite      int64          `json:"body_site"`
	Manufacturer  sql.NullString `json:"manufacturer"`
	LotNumber     sql.NullString `json:"lot_number"`
	PreviousDoses int64          `json:"previous_doses"`
	Recovered     bool           `json:"recovered"`
	Notes         sql.NullString `json:"notes"`
	UserID        int64          `json:"user_id"`
}

func (q *Queries) CreateImmunization(ctx context.Context, arg CreateImmunizationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createImmunization,
		arg.Dateof,
		arg.PatientID,
		arg.Provider,
		arg.AdminProvider,
		arg.Immunization,
		arg.Route,
		arg.BodySite,
		arg.Manufacturer,
		arg.LotNumber,
		arg.PreviousDoses,
		arg.Recovered,
		arg.Notes,
		arg.UserID,
	)
}

const listImmunizations = `-- name: ListImmunizations :many
SELECT id, created_at, updated_at, deleted_at, dateof, patient, provider, admin_provider, eoc, immunization, route, body_site, manufacturer, lot_number, previous_doses, recovered, notes, orderid, locked, user, active FROM immunization
WHERE patient = ?
  AND active = 'active'
  AND deleted_at IS NULL
ORDER BY dateof DESC
`

func (q *Queries) ListImmunizations(ctx context.Context, patientID int64) ([]Immunization, error) {
	rows, err := q.db.QueryContext(ctx, listImmunizations, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Immunization
	for rows.Next() {
		var i Immunization
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Dateof,
			&i.Patient,
			&i.Provider,
			&i.AdminProvider,
			&i.Eoc,
			&i.Immunization,
			&i.Route,
			&i.BodySite,
			&i.Manufacturer,
			&i.LotNumber,
			&i.PreviousDoses,
			&i.Recovered,
			&i.Notes,
			&i.Orderid,
			&i.Locked,
			&i.User,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
