// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: letters.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createLetter = `-- name: CreateLetter :execresult
INSERT INTO letters (
  patient, letter_type, recipient, subject, body, date_sent,
  user, active, created_at, updated_at
) VALUES (
  ?, ?, ?,
  ?, ?, ?,
  ?, 'active', NOW(), NOW()
)
`

type CreateLetterParams struct {
	PatientID  int64          `json:"patient_id"`
	LetterType string         `json:"letter_type"`
	Recipient  string         `json:"recipient"`
	Subject    string         `json:"subject"`
	Body       sql.NullString `json:"body"`
	DateSent   sql.NullTime   `json:"date_sent"`
	UserID     int64          `json:"user_id"`
}

// Create a new letter entry
func (q *Queries) CreateLetter(ctx context.Context, arg CreateLetterParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createLetter,
		arg.PatientID,
		arg.LetterType,
		arg.Recipient,
		arg.Subject,
		arg.Body,
		arg.DateSent,
		arg.UserID,
	)
}

const listLetters = `-- name: ListLetters :many
SELECT id, created_at, updated_at, deleted_at, patient, letter_type, recipient, subject, body, date_sent, user, active FROM letters
WHERE patient = ?
  AND active = 'active'
ORDER BY date_sent DESC
`

// List letters for a patient, ordered by date sent descending
func (q *Queries) ListLetters(ctx context.Context, patientID int64) ([]Letter, error) {
	rows, err := q.db.QueryContext(ctx, listLetters, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Letter
	for rows.Next() {
		var i Letter
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Patient,
			&i.LetterType,
			&i.Recipient,
			&i.Subject,
			&i.Body,
			&i.DateSent,
			&i.User,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
