// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: medications.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createMedication = `-- name: CreateMedication :execresult
INSERT INTO medications (
  patient, drug_name, dosage, frequency, start_date,
  end_date, prescribing_provider, active
) VALUES (
  ?, ?, ?,
  ?, ?, ?,
  ?, ?
)
`

type CreateMedicationParams struct {
	Patient             int64        `json:"patient"`
	DrugName            string       `json:"drug_name"`
	Dosage              string       `json:"dosage"`
	Frequency           string       `json:"frequency"`
	StartDate           sql.NullTime `json:"start_date"`
	EndDate             sql.NullTime `json:"end_date"`
	PrescribingProvider int64        `json:"prescribing_provider"`
	Active              string       `json:"active"`
}

// Create medication
func (q *Queries) CreateMedication(ctx context.Context, arg CreateMedicationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMedication,
		arg.Patient,
		arg.DrugName,
		arg.Dosage,
		arg.Frequency,
		arg.StartDate,
		arg.EndDate,
		arg.PrescribingProvider,
		arg.Active,
	)
}

const discontinueMedication = `-- name: DiscontinueMedication :exec
UPDATE medications SET
  active = 'inactive',
  end_date = ?
WHERE id = ?
  AND deleted_at IS NULL
`

type DiscontinueMedicationParams struct {
	EndDate sql.NullTime `json:"end_date"`
	ID      int64        `json:"id"`
}

// Discontinue medication (set inactive and end_date)
func (q *Queries) DiscontinueMedication(ctx context.Context, arg DiscontinueMedicationParams) error {
	_, err := q.db.ExecContext(ctx, discontinueMedication, arg.EndDate, arg.ID)
	return err
}

const getMedicationById = `-- name: GetMedicationById :one
SELECT id, created_at, updated_at, deleted_at, patient, drug_name, dosage, frequency, start_date, end_date, prescribing_provider, active FROM medications
WHERE id = ?
  AND deleted_at IS NULL
`

// Get medication by id
func (q *Queries) GetMedicationById(ctx context.Context, id int64) (Medication, error) {
	row := q.db.QueryRowContext(ctx, getMedicationById, id)
	var i Medication
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Patient,
		&i.DrugName,
		&i.Dosage,
		&i.Frequency,
		&i.StartDate,
		&i.EndDate,
		&i.PrescribingProvider,
		&i.Active,
	)
	return i, err
}

const listAllMedications = `-- name: ListAllMedications :many
SELECT id, created_at, updated_at, deleted_at, patient, drug_name, dosage, frequency, start_date, end_date, prescribing_provider, active FROM medications
WHERE patient = ?
  AND deleted_at IS NULL
ORDER BY start_date DESC
`

// List all medications (including inactive) for a patient
func (q *Queries) ListAllMedications(ctx context.Context, patientID int64) ([]Medication, error) {
	rows, err := q.db.QueryContext(ctx, listAllMedications, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medication
	for rows.Next() {
		var i Medication
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Patient,
			&i.DrugName,
			&i.Dosage,
			&i.Frequency,
			&i.StartDate,
			&i.EndDate,
			&i.PrescribingProvider,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMedications = `-- name: ListMedications :many
SELECT id, created_at, updated_at, deleted_at, patient, drug_name, dosage, frequency, start_date, end_date, prescribing_provider, active FROM medications
WHERE patient = ?
  AND active = 'active'
  AND deleted_at IS NULL
ORDER BY start_date DESC
`

// List medications: active meds for a patient
func (q *Queries) ListMedications(ctx context.Context, patientID int64) ([]Medication, error) {
	rows, err := q.db.QueryContext(ctx, listMedications, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medication
	for rows.Next() {
		var i Medication
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Patient,
			&i.DrugName,
			&i.Dosage,
			&i.Frequency,
			&i.StartDate,
			&i.EndDate,
			&i.PrescribingProvider,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMedication = `-- name: UpdateMedication :exec
UPDATE medications SET
  drug_name = ?,
  dosage = ?,
  frequency = ?,
  start_date = ?,
  end_date = ?,
  prescribing_provider = ?
WHERE id = ?
  AND deleted_at IS NULL
`

type UpdateMedicationParams struct {
	DrugName            string       `json:"drug_name"`
	Dosage              string       `json:"dosage"`
	Frequency           string       `json:"frequency"`
	StartDate           sql.NullTime `json:"start_date"`
	EndDate             sql.NullTime `json:"end_date"`
	PrescribingProvider int64        `json:"prescribing_provider"`
	ID                  int64        `json:"id"`
}

// Update medication
func (q *Queries) UpdateMedication(ctx context.Context, arg UpdateMedicationParams) error {
	_, err := q.db.ExecContext(ctx, updateMedication,
		arg.DrugName,
		arg.Dosage,
		arg.Frequency,
		arg.StartDate,
		arg.EndDate,
		arg.PrescribingProvider,
		arg.ID,
	)
	return err
}
