// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages_crud.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createMessage = `-- name: CreateMessage :execresult
INSERT INTO messages (
  msgby, msgtime, msgfor, msgrecip, msgpatient, msgperson,
  msgurgency, msgsubject, msgtext, msgread, msgunique, msgtag, active
) VALUES (
  ?, ?, ?, ?,
  ?, ?, ?,
  ?, ?, ?,
  ?, ?, ?
)
`

type CreateMessageParams struct {
	Msgby      int64          `json:"msgby"`
	Msgtime    time.Time      `json:"msgtime"`
	Msgfor     int64          `json:"msgfor"`
	Msgrecip   string         `json:"msgrecip"`
	Msgpatient int64          `json:"msgpatient"`
	Msgperson  string         `json:"msgperson"`
	Msgurgency int64          `json:"msgurgency"`
	Msgsubject string         `json:"msgsubject"`
	Msgtext    string         `json:"msgtext"`
	Msgread    int64          `json:"msgread"`
	Msgunique  sql.NullString `json:"msgunique"`
	Msgtag     sql.NullString `json:"msgtag"`
	Active     string         `json:"active"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMessage,
		arg.Msgby,
		arg.Msgtime,
		arg.Msgfor,
		arg.Msgrecip,
		arg.Msgpatient,
		arg.Msgperson,
		arg.Msgurgency,
		arg.Msgsubject,
		arg.Msgtext,
		arg.Msgread,
		arg.Msgunique,
		arg.Msgtag,
		arg.Active,
	)
}

const getMessageById = `-- name: GetMessageById :one
SELECT id, created_at, updated_at, deleted_at, msgby, sender, msgtime, msgfor, msgrecip, msgpatient, msgperson, msgurgency, msgsubject, msgtext, msgread, msgunique, msgtag, active FROM messages WHERE id = ?
`

func (q *Queries) GetMessageById(ctx context.Context, id int64) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessageById, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Msgby,
		&i.Sender,
		&i.Msgtime,
		&i.Msgfor,
		&i.Msgrecip,
		&i.Msgpatient,
		&i.Msgperson,
		&i.Msgurgency,
		&i.Msgsubject,
		&i.Msgtext,
		&i.Msgread,
		&i.Msgunique,
		&i.Msgtag,
		&i.Active,
	)
	return i, err
}
