// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package dbgen

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const deleteMessages = `-- name: DeleteMessages :exec
DELETE FROM messages WHERE id IN (/*SLICE:ids*/?)
`

// Delete messages by IDs
func (q *Queries) DeleteMessages(ctx context.Context, ids []int64) error {
	query := deleteMessages
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const listMessageTags = `-- name: ListMessageTags :many
SELECT DISTINCT msgtag FROM messages WHERE msgtag IS NOT NULL AND msgtag != '' ORDER BY msgtag
`

// List all distinct message tags
func (q *Queries) ListMessageTags(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, listMessageTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var msgtag sql.NullString
		if err := rows.Scan(&msgtag); err != nil {
			return nil, err
		}
		items = append(items, msgtag)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messagesByTag = `-- name: MessagesByTag :many
SELECT id, created_at, updated_at, deleted_at, msgby, sender, msgtime, msgfor, msgrecip, msgpatient, msgperson, msgurgency, msgsubject, msgtext, msgread, msgunique, msgtag, active FROM messages WHERE msgtag = ? ORDER BY msgtime DESC
`

// Get messages by tag
func (q *Queries) MessagesByTag(ctx context.Context, tag sql.NullString) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, messagesByTag, tag)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Msgby,
			&i.Sender,
			&i.Msgtime,
			&i.Msgfor,
			&i.Msgrecip,
			&i.Msgpatient,
			&i.Msgperson,
			&i.Msgurgency,
			&i.Msgsubject,
			&i.Msgtext,
			&i.Msgread,
			&i.Msgunique,
			&i.Msgtag,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messagesListUsers = `-- name: MessagesListUsers :many
SELECT username, id FROM user
`

type MessagesListUsersRow struct {
	Username string `json:"username"`
	ID       int64  `json:"id"`
}

// List all users (id and username) for message picker
func (q *Queries) MessagesListUsers(ctx context.Context) ([]MessagesListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, messagesListUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessagesListUsersRow
	for rows.Next() {
		var i MessagesListUsersRow
		if err := rows.Scan(&i.Username, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messagesViewForPatient = `-- name: MessagesViewForPatient :many
SELECT
  m.id, m.created_at, m.updated_at, m.deleted_at, m.msgby, m.sender, m.msgtime, m.msgfor, m.msgrecip, m.msgpatient, m.msgperson, m.msgurgency, m.msgsubject, m.msgtext, m.msgread, m.msgunique, m.msgtag, m.active,
  u.userdescrip AS sender
FROM messages m
LEFT OUTER JOIN user u ON u.id = m.msgby
WHERE (m.msgtag IS NULL OR LENGTH(m.msgtag) < 1)
  AND m.msgpatient = ?
  AND m.msgfor = ?
`

type MessagesViewForPatientParams struct {
	PatientID int64 `json:"patient_id"`
	UserID    int64 `json:"user_id"`
}

type MessagesViewForPatientRow struct {
	ID         int64          `json:"id"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
	DeletedAt  sql.NullTime   `json:"deleted_at"`
	Msgby      int64          `json:"msgby"`
	Sender     string         `json:"sender"`
	Msgtime    time.Time      `json:"msgtime"`
	Msgfor     int64          `json:"msgfor"`
	Msgrecip   string         `json:"msgrecip"`
	Msgpatient int64          `json:"msgpatient"`
	Msgperson  string         `json:"msgperson"`
	Msgurgency int64          `json:"msgurgency"`
	Msgsubject string         `json:"msgsubject"`
	Msgtext    string         `json:"msgtext"`
	Msgread    int64          `json:"msgread"`
	Msgunique  sql.NullString `json:"msgunique"`
	Msgtag     sql.NullString `json:"msgtag"`
	Active     string         `json:"active"`
	Sender_2   sql.NullString `json:"sender_2"`
}

// View messages: all messages for a specific patient/user
func (q *Queries) MessagesViewForPatient(ctx context.Context, arg MessagesViewForPatientParams) ([]MessagesViewForPatientRow, error) {
	rows, err := q.db.QueryContext(ctx, messagesViewForPatient, arg.PatientID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessagesViewForPatientRow
	for rows.Next() {
		var i MessagesViewForPatientRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Msgby,
			&i.Sender,
			&i.Msgtime,
			&i.Msgfor,
			&i.Msgrecip,
			&i.Msgpatient,
			&i.Msgperson,
			&i.Msgurgency,
			&i.Msgsubject,
			&i.Msgtext,
			&i.Msgread,
			&i.Msgunique,
			&i.Msgtag,
			&i.Active,
			&i.Sender_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messagesViewForUser = `-- name: MessagesViewForUser :many
SELECT
  m.id, m.created_at, m.updated_at, m.deleted_at, m.msgby, m.sender, m.msgtime, m.msgfor, m.msgrecip, m.msgpatient, m.msgperson, m.msgurgency, m.msgsubject, m.msgtext, m.msgread, m.msgunique, m.msgtag, m.active,
  u.userdescrip AS sender
FROM messages m
LEFT OUTER JOIN user u ON u.id = m.msgby
WHERE (m.msgtag IS NULL OR LENGTH(m.msgtag) < 1)
  AND m.msgfor = ?
`

type MessagesViewForUserRow struct {
	ID         int64          `json:"id"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
	DeletedAt  sql.NullTime   `json:"deleted_at"`
	Msgby      int64          `json:"msgby"`
	Sender     string         `json:"sender"`
	Msgtime    time.Time      `json:"msgtime"`
	Msgfor     int64          `json:"msgfor"`
	Msgrecip   string         `json:"msgrecip"`
	Msgpatient int64          `json:"msgpatient"`
	Msgperson  string         `json:"msgperson"`
	Msgurgency int64          `json:"msgurgency"`
	Msgsubject string         `json:"msgsubject"`
	Msgtext    string         `json:"msgtext"`
	Msgread    int64          `json:"msgread"`
	Msgunique  sql.NullString `json:"msgunique"`
	Msgtag     sql.NullString `json:"msgtag"`
	Active     string         `json:"active"`
	Sender_2   sql.NullString `json:"sender_2"`
}

// View messages: all messages for a user (non-patient, all read states)
func (q *Queries) MessagesViewForUser(ctx context.Context, userID int64) ([]MessagesViewForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, messagesViewForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessagesViewForUserRow
	for rows.Next() {
		var i MessagesViewForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Msgby,
			&i.Sender,
			&i.Msgtime,
			&i.Msgfor,
			&i.Msgrecip,
			&i.Msgpatient,
			&i.Msgperson,
			&i.Msgurgency,
			&i.Msgsubject,
			&i.Msgtext,
			&i.Msgread,
			&i.Msgunique,
			&i.Msgtag,
			&i.Active,
			&i.Sender_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messagesViewUnreadForPatient = `-- name: MessagesViewUnreadForPatient :many
SELECT
  m.id, m.created_at, m.updated_at, m.deleted_at, m.msgby, m.sender, m.msgtime, m.msgfor, m.msgrecip, m.msgpatient, m.msgperson, m.msgurgency, m.msgsubject, m.msgtext, m.msgread, m.msgunique, m.msgtag, m.active,
  u.userdescrip AS sender
FROM messages m
LEFT OUTER JOIN user u ON u.id = m.msgby
WHERE (m.msgtag IS NULL OR LENGTH(m.msgtag) < 1)
  AND m.msgpatient = ?
  AND m.msgread = 0
  AND m.msgby = ?
`

type MessagesViewUnreadForPatientParams struct {
	PatientID int64 `json:"patient_id"`
	UserID    int64 `json:"user_id"`
}

type MessagesViewUnreadForPatientRow struct {
	ID         int64          `json:"id"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
	DeletedAt  sql.NullTime   `json:"deleted_at"`
	Msgby      int64          `json:"msgby"`
	Sender     string         `json:"sender"`
	Msgtime    time.Time      `json:"msgtime"`
	Msgfor     int64          `json:"msgfor"`
	Msgrecip   string         `json:"msgrecip"`
	Msgpatient int64          `json:"msgpatient"`
	Msgperson  string         `json:"msgperson"`
	Msgurgency int64          `json:"msgurgency"`
	Msgsubject string         `json:"msgsubject"`
	Msgtext    string         `json:"msgtext"`
	Msgread    int64          `json:"msgread"`
	Msgunique  sql.NullString `json:"msgunique"`
	Msgtag     sql.NullString `json:"msgtag"`
	Active     string         `json:"active"`
	Sender_2   sql.NullString `json:"sender_2"`
}

// View messages: unread messages for a specific patient/user
func (q *Queries) MessagesViewUnreadForPatient(ctx context.Context, arg MessagesViewUnreadForPatientParams) ([]MessagesViewUnreadForPatientRow, error) {
	rows, err := q.db.QueryContext(ctx, messagesViewUnreadForPatient, arg.PatientID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessagesViewUnreadForPatientRow
	for rows.Next() {
		var i MessagesViewUnreadForPatientRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Msgby,
			&i.Sender,
			&i.Msgtime,
			&i.Msgfor,
			&i.Msgrecip,
			&i.Msgpatient,
			&i.Msgperson,
			&i.Msgurgency,
			&i.Msgsubject,
			&i.Msgtext,
			&i.Msgread,
			&i.Msgunique,
			&i.Msgtag,
			&i.Active,
			&i.Sender_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messagesViewUnreadForUser = `-- name: MessagesViewUnreadForUser :many
SELECT
  m.id, m.created_at, m.updated_at, m.deleted_at, m.msgby, m.sender, m.msgtime, m.msgfor, m.msgrecip, m.msgpatient, m.msgperson, m.msgurgency, m.msgsubject, m.msgtext, m.msgread, m.msgunique, m.msgtag, m.active,
  u.userdescrip AS sender
FROM messages m
LEFT OUTER JOIN user u ON u.id = m.msgby
WHERE (m.msgtag IS NULL OR LENGTH(m.msgtag) < 1)
  AND m.msgfor = ?
  AND m.msgread = 0
`

type MessagesViewUnreadForUserRow struct {
	ID         int64          `json:"id"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
	DeletedAt  sql.NullTime   `json:"deleted_at"`
	Msgby      int64          `json:"msgby"`
	Sender     string         `json:"sender"`
	Msgtime    time.Time      `json:"msgtime"`
	Msgfor     int64          `json:"msgfor"`
	Msgrecip   string         `json:"msgrecip"`
	Msgpatient int64          `json:"msgpatient"`
	Msgperson  string         `json:"msgperson"`
	Msgurgency int64          `json:"msgurgency"`
	Msgsubject string         `json:"msgsubject"`
	Msgtext    string         `json:"msgtext"`
	Msgread    int64          `json:"msgread"`
	Msgunique  sql.NullString `json:"msgunique"`
	Msgtag     sql.NullString `json:"msgtag"`
	Active     string         `json:"active"`
	Sender_2   sql.NullString `json:"sender_2"`
}

// View messages: unread messages for a user (non-patient, unread only)
func (q *Queries) MessagesViewUnreadForUser(ctx context.Context, userID int64) ([]MessagesViewUnreadForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, messagesViewUnreadForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessagesViewUnreadForUserRow
	for rows.Next() {
		var i MessagesViewUnreadForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Msgby,
			&i.Sender,
			&i.Msgtime,
			&i.Msgfor,
			&i.Msgrecip,
			&i.Msgpatient,
			&i.Msgperson,
			&i.Msgurgency,
			&i.Msgsubject,
			&i.Msgtext,
			&i.Msgread,
			&i.Msgunique,
			&i.Msgtag,
			&i.Active,
			&i.Sender_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
