// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql"
	"time"
)

type AclPermission struct {
	ID             int64        `json:"id"`
	CreatedAt      time.Time    `json:"created_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
	DeletedAt      sql.NullTime `json:"deleted_at"`
	PermissionName string       `json:"permission_name"`
	PermissionDesc string       `json:"permission_desc"`
}

type Allergy struct {
	ID        int64        `json:"id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	Patient   int64        `json:"patient"`
	Active    string       `json:"active"`
}

type Annotation struct {
	ID         int64        `json:"id"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	DeletedAt  sql.NullTime `json:"deleted_at"`
	Atimestamp time.Time    `json:"atimestamp"`
	Apatient   int64        `json:"apatient"`
	Amodule    string       `json:"amodule"`
	Atable     string       `json:"atable"`
	Aid        int64        `json:"aid"`
	Auser      int64        `json:"auser"`
	Annotation string       `json:"annotation"`
}

type Appttemplate struct {
	ID          int64          `json:"id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
	Atname      string         `json:"atname"`
	Atduration  int64          `json:"atduration"`
	Atequipment sql.NullString `json:"atequipment"`
	Atcolor     string         `json:"atcolor"`
}

type Authorization struct {
	ID               int64        `json:"id"`
	CreatedAt        time.Time    `json:"created_at"`
	UpdatedAt        time.Time    `json:"updated_at"`
	DeletedAt        sql.NullTime `json:"deleted_at"`
	Authdtadd        time.Time    `json:"authdtadd"`
	Authdtmod        time.Time    `json:"authdtmod"`
	Authpatient      int64        `json:"authpatient"`
	Authdtbegin      time.Time    `json:"authdtbegin"`
	Authdtend        time.Time    `json:"authdtend"`
	Authnum          string       `json:"authnum"`
	Authtype         int64        `json:"authtype"`
	Authprov         int64        `json:"authprov"`
	Authprovid       string       `json:"authprovid"`
	Authinsco        int64        `json:"authinsco"`
	Authvisits       int64        `json:"authvisits"`
	Authvisitsused   int64        `json:"authvisitsused"`
	Authvisitsremain int64        `json:"authvisitsremain"`
	User             int64        `json:"user"`
	Active           string       `json:"active"`
}

type Bccdc struct {
	ID          int64        `json:"id"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
	AgentCode   string       `json:"agent_code"`
	Description string       `json:"description"`
}

type Bcontact struct {
	ID        int64        `json:"id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	Bcfname   string       `json:"bcfname"`
	Bcmname   string       `json:"bcmname"`
	Bclname   string       `json:"bclname"`
	Bcaddr    string       `json:"bcaddr"`
	Bccity    string       `json:"bccity"`
	Bcstate   string       `json:"bcstate"`
	Bczip     string       `json:"bczip"`
	Bcphone   string       `json:"bcphone"`
	Stamp     time.Time    `json:"stamp"`
	User      int64        `json:"user"`
}

type Billkey struct {
	ID          int64          `json:"id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
	Billkeydate time.Time      `json:"billkeydate"`
	Billkey     sql.NullString `json:"billkey"`
	Bkprocs     string         `json:"bkprocs"`
}

type Bodysite struct {
	ID           int64        `json:"id"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
	Abbrev       string       `json:"abbrev"`
	DisplayValue string       `json:"display_value"`
}

type Bservice struct {
	ID        int64        `json:"id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	Bsname    string       `json:"bsname"`
	Bsaddr    string       `json:"bsaddr"`
	Bscity    string       `json:"bscity"`
	Bsstate   string       `json:"bsstate"`
	Bszip     string       `json:"bszip"`
	Bsphone   string       `json:"bsphone"`
	Bsetin    string       `json:"bsetin"`
	Bstin     string       `json:"bstin"`
	Stamp     time.Time    `json:"stamp"`
	User      int64        `json:"user"`
}

type Calgroup struct {
	ID             int64        `json:"id"`
	CreatedAt      time.Time    `json:"created_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
	DeletedAt      sql.NullTime `json:"deleted_at"`
	Groupname      string       `json:"groupname"`
	Groupfacility  int64        `json:"groupfacility"`
	Groupfrequency int64        `json:"groupfrequency"`
	Grouplength    int64        `json:"grouplength"`
	Groupmembers   string       `json:"groupmembers"`
}

type Calgroupattend struct {
	ID         int64        `json:"id"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	DeletedAt  sql.NullTime `json:"deleted_at"`
	Calgroupid int64        `json:"calgroupid"`
	Calid      int64        `json:"calid"`
	Patient    int64        `json:"patient"`
	Calstatus  string       `json:"calstatus"`
	Stamp      time.Time    `json:"stamp"`
}

type Callin struct {
	ID          int64        `json:"id"`
	Cilname     string       `json:"cilname"`
	Cifname     string       `json:"cifname"`
	Cicomplaint string       `json:"cicomplaint"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
}

type Certification struct {
	ID           int64          `json:"id"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
	Patient      int64          `json:"patient"`
	CertType     int64          `json:"cert_type"`
	CertFormNum  sql.NullInt64  `json:"cert_form_num"`
	CertDesc     string         `json:"cert_desc"`
	CertFormData sql.NullString `json:"cert_form_data"`
	User         int64          `json:"user"`
	Active       string         `json:"active"`
}

type ChronicProblem struct {
	ID        int64        `json:"id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	Patient   int64        `json:"patient"`
	Date      time.Time    `json:"date"`
	Problem   string       `json:"problem"`
	User      int64        `json:"user"`
}

type Claimlog struct {
	ID          int64        `json:"id"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
	Cltimestamp time.Time    `json:"cltimestamp"`
	Cluser      int64        `json:"cluser"`
	Clprocedure int64        `json:"clprocedure"`
	Clpayrec    int64        `json:"clpayrec"`
	Claction    string       `json:"claction"`
	Clcomment   string       `json:"clcomment"`
	Clformat    string       `json:"clformat"`
	Cltarget    string       `json:"cltarget"`
	Cltargetopt string       `json:"cltargetopt"`
	Clbillkey   int64        `json:"clbillkey"`
}

type Claimtype struct {
	ID           int64        `json:"id"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
	Clmtpname    string       `json:"clmtpname"`
	Clmtpdescrip string       `json:"clmtpdescrip"`
	Clmtpadd     time.Time    `json:"clmtpadd"`
	Clmtpmod     time.Time    `json:"clmtpmod"`
}

type Clearinghouse struct {
	ID              int64        `json:"id"`
	CreatedAt       time.Time    `json:"created_at"`
	UpdatedAt       time.Time    `json:"updated_at"`
	DeletedAt       sql.NullTime `json:"deleted_at"`
	Chname          string       `json:"chname"`
	Chaddr          string       `json:"chaddr"`
	Chcity          string       `json:"chcity"`
	Chstate         string       `json:"chstate"`
	Chzip           string       `json:"chzip"`
	Chphone         string       `json:"chphone"`
	Chetin          string       `json:"chetin"`
	Chx12gssender   string       `json:"chx12gssender"`
	Chx12gsreceiver string       `json:"chx12gsreceiver"`
	Stamp           time.Time    `json:"stamp"`
	User            int64        `json:"user"`
}

type ClinicalOrder struct {
	ID               int64          `json:"id"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	DeletedAt        sql.NullTime   `json:"deleted_at"`
	Patient          int64          `json:"patient"`
	OrderType        string         `json:"order_type"`
	Description      string         `json:"description"`
	Status           string         `json:"status"`
	DateOrdered      sql.NullTime   `json:"date_ordered"`
	OrderingProvider int64          `json:"ordering_provider"`
	Notes            sql.NullString `json:"notes"`
	User             int64          `json:"user"`
	Active           string         `json:"active"`
}

type Config struct {
	ID        int64          `json:"id"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
	COption   string         `json:"c_option"`
	CValue    sql.NullString `json:"c_value"`
	CTitle    sql.NullString `json:"c_title"`
	CSection  sql.NullString `json:"c_section"`
	CType     string         `json:"c_type"`
	COptions  sql.NullString `json:"c_options"`
}

type Covtype struct {
	ID           int64        `json:"id"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
	Covtpname    string       `json:"covtpname"`
	Covtpdescrip string       `json:"covtpdescrip"`
	Covtpdtadd   time.Time    `json:"covtpdtadd"`
	Covtpdtmod   time.Time    `json:"covtpdtmod"`
}

type Cpt struct {
	ID           int64          `json:"id"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
	Abbrev       string         `json:"abbrev"`
	Cptnameint   sql.NullString `json:"cptnameint"`
	Cptnameext   sql.NullString `json:"cptnameext"`
	Cptgender    string         `json:"cptgender"`
	Cpttaxed     string         `json:"cpttaxed"`
	Cpttype      int64          `json:"cpttype"`
	Cptreqcpt    sql.NullString `json:"cptreqcpt"`
	Cptexccpt    sql.NullString `json:"cptexccpt"`
	Cptreqicd    sql.NullString `json:"cptreqicd"`
	Cptrexcicd   sql.NullString `json:"cptrexcicd"`
	Cptrelval    float64        `json:"cptrelval"`
	Cptdeftos    int64          `json:"cptdeftos"`
	Cptdefstdfee float64        `json:"cptdefstdfee"`
	Cptstdfee    string         `json:"cptstdfee"`
	Cpttos       string         `json:"cpttos"`
	Cpttosprfx   string         `json:"cpttosprfx"`
}

type Cptmod struct {
	ID            int64        `json:"id"`
	CreatedAt     time.Time    `json:"created_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
	DeletedAt     sql.NullTime `json:"deleted_at"`
	Cptmod        string       `json:"cptmod"`
	Cptmoddescrip string       `json:"cptmoddescrip"`
}

type CurrentProblem struct {
	ID        int64        `json:"id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	Patient   int64        `json:"patient"`
	Date      time.Time    `json:"date"`
	Problem   string       `json:"problem"`
	User      int64        `json:"user"`
	Active    string       `json:"active"`
}

type DocumentsTc struct {
	ID          int64        `json:"id"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
	Type        string       `json:"type"`
	Category    string       `json:"category"`
	Description string       `json:"description"`
}

type Drugform struct {
	ID          int64        `json:"id"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
	Code        string       `json:"code"`
	Description string       `json:"description"`
}

type Drugquantityqual struct {
	ID          int64        `json:"id"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
	Code        string       `json:"code"`
	Description string       `json:"description"`
}

type Drugsampleinv struct {
	ID                int64        `json:"id"`
	CreatedAt         time.Time    `json:"created_at"`
	UpdatedAt         time.Time    `json:"updated_at"`
	DeletedAt         sql.NullTime `json:"deleted_at"`
	Drugcode          string       `json:"drugcode"`
	Drugndc           string       `json:"drugndc"`
	Drugclass         string       `json:"drugclass"`
	Packagecount      int64        `json:"packagecount"`
	Location          string       `json:"location"`
	Drugco            string       `json:"drugco"`
	Drugrep           string       `json:"drugrep"`
	Invoice           string       `json:"invoice"`
	Samplecount       int64        `json:"samplecount"`
	Samplecountremain int64        `json:"samplecountremain"`
	Lot               string       `json:"lot"`
	Expiration        sql.NullTime `json:"expiration"`
	Received          sql.NullTime `json:"received"`
	Assignedto        string       `json:"assignedto"`
	Loguser           int64        `json:"loguser"`
	Logdate           time.Time    `json:"logdate"`
	Disposeby         string       `json:"disposeby"`
	Disposedate       sql.NullTime `json:"disposedate"`
	Disposemethod     string       `json:"disposemethod"`
	Disposereason     string       `json:"disposereason"`
	Witness           string       `json:"witness"`
}

type Enctype struct {
	ID        int64        `json:"id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	Enclosure string       `json:"enclosure"`
}

type EpisodeOfCare struct {
	ID          int64        `json:"id"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
	Patient     int64        `json:"patient"`
	StartDate   time.Time    `json:"start_date"`
	EndDate     sql.NullTime `json:"end_date"`
	Description string       `json:"description"`
	Status      string       `json:"status"`
	Provider    int64        `json:"provider"`
	Notes       string       `json:"notes"`
	User        int64        `json:"user"`
	Active      string       `json:"active"`
}

type Event struct {
	ID          int64        `json:"id"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
	Patient     int64        `json:"patient"`
	EventDate   time.Time    `json:"event_date"`
	EventType   string       `json:"event_type"`
	Description string       `json:"description"`
	Module      string       `json:"module"`
	ReferenceID int64        `json:"reference_id"`
	User        int64        `json:"user"`
	Active      string       `json:"active"`
}

type Facility struct {
	ID           int64          `json:"id"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
	Psrname      string         `json:"psrname"`
	Psraddr1     sql.NullString `json:"psraddr1"`
	Psraddr2     sql.NullString `json:"psraddr2"`
	Psrcity      sql.NullString `json:"psrcity"`
	Psrstate     sql.NullString `json:"psrstate"`
	Psrzip       sql.NullString `json:"psrzip"`
	Psrcountry   sql.NullString `json:"psrcountry"`
	Psrnote      sql.NullString `json:"psrnote"`
	Psrphone     sql.NullString `json:"psrphone"`
	Psrfax       sql.NullString `json:"psrfax"`
	Psremail     sql.NullString `json:"psremail"`
	Psrein       sql.NullString `json:"psrein"`
	Psrnpi       sql.NullString `json:"psrnpi"`
	Psrtaxonomy  sql.NullString `json:"psrtaxonomy"`
	Psrintext    sql.NullString `json:"psrintext"`
	Psrpos       int64          `json:"psrpos"`
	Psrx12id     sql.NullString `json:"psrx12id"`
	Psrx12idtype sql.NullString `json:"psrx12idtype"`
}

type FinancialDemographic struct {
	ID              int64          `json:"id"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
	Patient         int64          `json:"patient"`
	Income          int32          `json:"income"`
	IDType          string         `json:"id_type"`
	IDIssuer        string         `json:"id_issuer"`
	IDNumber        string         `json:"id_number"`
	IDExpire        string         `json:"id_expire"`
	HouseholdSize   int32          `json:"household_size"`
	Spouse          int32          `json:"spouse"`
	Children        int32          `json:"children"`
	OtherDependents int32          `json:"other_dependents"`
	FreeText        sql.NullString `json:"free_text"`
	EntryDesc       string         `json:"entry_desc"`
	EntryTs         time.Time      `json:"entry_ts"`
	User            int64          `json:"user"`
	Active          string         `json:"active"`
}

type FormTemplate struct {
	ID           int64          `json:"id"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	FormType     string         `json:"form_type"`
	TemplateData sql.NullString `json:"template_data"`
	IsDefault    bool           `json:"is_default"`
	User         int64          `json:"user"`
}

type GroupPermission struct {
	ID           int64        `json:"id"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
	GroupID      int64        `json:"group_id"`
	PermissionID int64        `json:"permission_id"`
}

type Growthchart struct {
	ID                  int64          `json:"id"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
	DeletedAt           sql.NullTime   `json:"deleted_at"`
	Patient             int64          `json:"patient"`
	RecordDate          time.Time      `json:"record_date"`
	AgeMonths           sql.NullString `json:"age_months"`
	HeightCm            sql.NullString `json:"height_cm"`
	WeightKg            sql.NullString `json:"weight_kg"`
	HeadCircumferenceCm sql.NullString `json:"head_circumference_cm"`
	Bmi                 sql.NullString `json:"bmi"`
	Notes               string         `json:"notes"`
	User                int64          `json:"user"`
	Active              string         `json:"active"`
}

type Holiday struct {
	ID          int64        `json:"id"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
	HolidayDate time.Time    `json:"holiday_date"`
	HolidayName string       `json:"holiday_name"`
	Description string       `json:"description"`
	Active      string       `json:"active"`
}

type I18nlanguage struct {
	ID        int64        `json:"id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	Abbrev    string       `json:"abbrev"`
	Language  string       `json:"language"`
}

type Icd9 struct {
	ID           int64          `json:"id"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
	Abbrev       string         `json:"abbrev"`
	Language     string         `json:"language"`
	Icd9code     string         `json:"icd9code"`
	Icd10code    sql.NullString `json:"icd10code"`
	Icd9descrip  string         `json:"icd9descrip"`
	Icd10descrip sql.NullString `json:"icd10descrip"`
	Icdmetadesc  sql.NullString `json:"icdmetadesc"`
	Icdng        sql.NullTime   `json:"icdng"`
	Icddrg       string         `json:"icddrg"`
	Icdnum       int64          `json:"icdnum"`
	Icdamt       sql.NullString `json:"icdamt"`
	Icdcoll      float64        `json:"icdcoll"`
}

type Immunization struct {
	ID            int64          `json:"id"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	DeletedAt     sql.NullTime   `json:"deleted_at"`
	Dateof        time.Time      `json:"dateof"`
	Patient       int64          `json:"patient"`
	Provider      int64          `json:"provider"`
	AdminProvider int64          `json:"admin_provider"`
	Eoc           sql.NullInt64  `json:"eoc"`
	Immunization  int64          `json:"immunization"`
	Route         int64          `json:"route"`
	BodySite      int64          `json:"body_site"`
	Manufacturer  sql.NullString `json:"manufacturer"`
	LotNumber     sql.NullString `json:"lot_number"`
	PreviousDoses int64          `json:"previous_doses"`
	Recovered     bool           `json:"recovered"`
	Notes         sql.NullString `json:"notes"`
	Orderid       int64          `json:"orderid"`
	Locked        int64          `json:"locked"`
	User          int64          `json:"user"`
	Active        string         `json:"active"`
}

type Insco struct {
	ID                 int64        `json:"id"`
	CreatedAt          time.Time    `json:"created_at"`
	UpdatedAt          time.Time    `json:"updated_at"`
	DeletedAt          sql.NullTime `json:"deleted_at"`
	Inscodtadd         time.Time    `json:"inscodtadd"`
	Inscodtmod         time.Time    `json:"inscodtmod"`
	Insconame          string       `json:"insconame"`
	Inscoalias         string       `json:"inscoalias"`
	Inscoaddr1         string       `json:"inscoaddr1"`
	Inscoaddr2         string       `json:"inscoaddr2"`
	Inscocity          string       `json:"inscocity"`
	Inscostate         string       `json:"inscostate"`
	Inscozip           string       `json:"inscozip"`
	Inscophone         string       `json:"inscophone"`
	Inscofax           string       `json:"inscofax"`
	Inscogroup         int64        `json:"inscogroup"`
	Inscotype          int64        `json:"inscotype"`
	Inscoassign        int64        `json:"inscoassign"`
	Inscomod           string       `json:"inscomod"`
	Inscoidmap         string       `json:"inscoidmap"`
	Inscox12id         string       `json:"inscox12id"`
	Inscodefformat     string       `json:"inscodefformat"`
	Inscodeftarget     string       `json:"inscodeftarget"`
	Inscodeftargetopt  string       `json:"inscodeftargetopt"`
	Inscodefformate    string       `json:"inscodefformate"`
	Inscodeftargete    string       `json:"inscodeftargete"`
	Inscodeftargetopte string       `json:"inscodeftargetopte"`
	Inscoarchive       int64        `json:"inscoarchive"`
}

type Inscogroup struct {
	ID         int64        `json:"id"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	DeletedAt  sql.NullTime `json:"deleted_at"`
	Inscogroup string       `json:"inscogroup"`
}

type Insmod struct {
	ID         int64        `json:"id"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	DeletedAt  sql.NullTime `json:"deleted_at"`
	Insmod     string       `json:"insmod"`
	Insmoddesc string       `json:"insmoddesc"`
}

type Intservtype struct {
	ID          int64        `json:"id"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
	Intservtype string       `json:"intservtype"`
}

type Lab struct {
	ID             int64          `json:"id"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
	Patient        int64          `json:"patient"`
	LabName        string         `json:"lab_name"`
	LabDate        time.Time      `json:"lab_date"`
	Result         string         `json:"result"`
	Unit           string         `json:"unit"`
	ReferenceRange string         `json:"reference_range"`
	Status         string         `json:"status"`
	Notes          sql.NullString `json:"notes"`
	User           int64          `json:"user"`
	Active         string         `json:"active"`
}

type Letter struct {
	ID         int64          `json:"id"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
	DeletedAt  sql.NullTime   `json:"deleted_at"`
	Patient    int64          `json:"patient"`
	LetterType string         `json:"letter_type"`
	Recipient  string         `json:"recipient"`
	Subject    string         `json:"subject"`
	Body       sql.NullString `json:"body"`
	DateSent   sql.NullTime   `json:"date_sent"`
	User       int64          `json:"user"`
	Active     string         `json:"active"`
}

type Loinc struct {
	ID                      int64        `json:"id"`
	CreatedAt               time.Time    `json:"created_at"`
	UpdatedAt               time.Time    `json:"updated_at"`
	DeletedAt               sql.NullTime `json:"deleted_at"`
	LoincNum                string       `json:"loinc_num"`
	Component               string       `json:"component"`
	Property                string       `json:"property"`
	TypeAspct               string       `json:"type_aspct"`
	System                  string       `json:"system"`
	ScaleTyp                string       `json:"scale_typ"`
	MethodTyp               string       `json:"method_typ"`
	Answerlist              string       `json:"answerlist"`
	Status                  string       `json:"status"`
	Shortname               string       `json:"shortname"`
	ExternalCopyrightNotice string       `json:"external_copyright_notice"`
}

type Medication struct {
	ID                  int64        `json:"id"`
	CreatedAt           time.Time    `json:"created_at"`
	UpdatedAt           time.Time    `json:"updated_at"`
	DeletedAt           sql.NullTime `json:"deleted_at"`
	Patient             int64        `json:"patient"`
	DrugName            string       `json:"drug_name"`
	Dosage              string       `json:"dosage"`
	Frequency           string       `json:"frequency"`
	StartDate           sql.NullTime `json:"start_date"`
	EndDate             sql.NullTime `json:"end_date"`
	PrescribingProvider int64        `json:"prescribing_provider"`
	Active              string       `json:"active"`
}

type Message struct {
	ID         int64          `json:"id"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
	DeletedAt  sql.NullTime   `json:"deleted_at"`
	Msgby      int64          `json:"msgby"`
	Sender     string         `json:"sender"`
	Msgtime    time.Time      `json:"msgtime"`
	Msgfor     int64          `json:"msgfor"`
	Msgrecip   string         `json:"msgrecip"`
	Msgpatient int64          `json:"msgpatient"`
	Msgperson  string         `json:"msgperson"`
	Msgurgency int64          `json:"msgurgency"`
	Msgsubject string         `json:"msgsubject"`
	Msgtext    string         `json:"msgtext"`
	Msgread    int64          `json:"msgread"`
	Msgunique  sql.NullString `json:"msgunique"`
	Msgtag     sql.NullString `json:"msgtag"`
	Active     string         `json:"active"`
}

type Module struct {
	ID           int64        `json:"id"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
	ModuleName   string       `json:"module_name"`
	ModuleClass  string       `json:"module_class"`
	ModuleTable  string       `json:"module_table"`
	ModuleHidden bool         `json:"module_hidden"`
}

type Patient struct {
	ID                   int64          `json:"id"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	DeletedAt            sql.NullTime   `json:"deleted_at"`
	Ptdtadd              time.Time      `json:"ptdtadd"`
	Ptdtmod              sql.NullTime   `json:"ptdtmod"`
	Ptsalut              string         `json:"ptsalut"`
	Ptlname              string         `json:"ptlname"`
	Ptmaidenname         sql.NullString `json:"ptmaidenname"`
	Ptfname              string         `json:"ptfname"`
	Ptmname              sql.NullString `json:"ptmname"`
	Ptsuffix             string         `json:"ptsuffix"`
	Ptsex                string         `json:"ptsex"`
	Ptid                 string         `json:"ptid"`
	Ptdiag1              sql.NullInt64  `json:"ptdiag1"`
	Ptdiag2              sql.NullInt64  `json:"ptdiag2"`
	Ptdiag3              sql.NullInt64  `json:"ptdiag3"`
	Ptdiag4              sql.NullInt64  `json:"ptdiag4"`
	Ptdiagset            string         `json:"ptdiagset"`
	Ptarchive            int64          `json:"ptarchive"`
	Iso                  string         `json:"iso"`
	Ptblood              string         `json:"ptblood"`
	Ptdead               int64          `json:"ptdead"`
	Ptdeaddt             sql.NullTime   `json:"ptdeaddt"`
	Ptbudg               float64        `json:"ptbudg"`
	Ptbilltype           string         `json:"ptbilltype"`
	Ptprimaryfacility    int64          `json:"ptprimaryfacility"`
	Ptprimarylanguage    string         `json:"ptprimarylanguage"`
	Ptdob                sql.NullTime   `json:"ptdob"`
	Ptpcp                int64          `json:"ptpcp"`
	Ptpharmacy           int64          `json:"ptpharmacy"`
	Ssn                  sql.NullString `json:"ssn"`
	Pemail               sql.NullString `json:"pemail"`
	PortalPassword       string         `json:"portal_password"`
	PortalPin            string         `json:"portal_pin"`
	PortalEnabled        bool           `json:"portal_enabled"`
	PortalLastLogin      sql.NullTime   `json:"portal_last_login"`
	PortalFailedAttempts int32          `json:"portal_failed_attempts"`
	Dmv                  sql.NullString `json:"dmv"`
	Patient              int64          `json:"patient"`
	Module               string         `json:"module"`
	Oid                  int64          `json:"oid"`
	Stamp                time.Time      `json:"stamp"`
	Summary              string         `json:"summary"`
	Locked               bool           `json:"locked"`
	Annotation           sql.NullString `json:"annotation"`
	User                 int64          `json:"user"`
	Provider             int64          `json:"provider"`
	Status               string         `json:"status"`
}

type PatientAddress struct {
	ID        int64          `json:"id"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
	Patient   int64          `json:"patient"`
	Line1     sql.NullString `json:"line1"`
	Line2     sql.NullString `json:"line2"`
	City      sql.NullString `json:"city"`
	Stpr      sql.NullString `json:"stpr"`
	Postal    sql.NullString `json:"postal"`
	Zip       sql.NullString `json:"zip"`
	Active    bool           `json:"active"`
}

type PatientCorrespondence struct {
	ID                 int64          `json:"id"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
	DeletedAt          sql.NullTime   `json:"deleted_at"`
	Patient            int64          `json:"patient"`
	CorrespondenceType string         `json:"correspondence_type"`
	Direction          string         `json:"direction"`
	ContactName        string         `json:"contact_name"`
	ContactMethod      string         `json:"contact_method"`
	Summary            sql.NullString `json:"summary"`
	Date               sql.NullTime   `json:"date"`
	User               int64          `json:"user"`
	Active             string         `json:"active"`
}

type PatientCoverage struct {
	ID               int64        `json:"id"`
	CreatedAt        time.Time    `json:"created_at"`
	UpdatedAt        time.Time    `json:"updated_at"`
	DeletedAt        sql.NullTime `json:"deleted_at"`
	Patient          int64        `json:"patient"`
	InsuranceCompany int64        `json:"insurance_company"`
	CoverageType     int64        `json:"coverage_type"`
	PolicyNumber     string       `json:"policy_number"`
	GroupNumber      string       `json:"group_number"`
	EffectiveDate    sql.NullTime `json:"effective_date"`
	TerminationDate  sql.NullTime `json:"termination_date"`
	PrimaryCoverage  bool         `json:"primary_coverage"`
	Active           string       `json:"active"`
}

type PatientEmr struct {
	ID         int64          `json:"id"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
	DeletedAt  sql.NullTime   `json:"deleted_at"`
	Patient    int64          `json:"patient"`
	Module     string         `json:"module"`
	Oid        int64          `json:"oid"`
	Stamp      time.Time      `json:"stamp"`
	Summary    string         `json:"summary"`
	Locked     bool           `json:"locked"`
	Annotation sql.NullString `json:"annotation"`
	User       int64          `json:"user"`
	Provider   int64          `json:"provider"`
	Language   string         `json:"language"`
	Status     string         `json:"status"`
}

type PatientID struct {
	ID        int64        `json:"id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	Patient   int64        `json:"patient"`
	ForeignID string       `json:"foreign_id"`
	Facility  int64        `json:"facility"`
	Practice  int64        `json:"practice"`
	User      int64        `json:"user"`
	Stamp     time.Time    `json:"stamp"`
	Active    string       `json:"active"`
}

type PatientReporting struct {
	ID                  int64          `json:"id"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
	DeletedAt           sql.NullTime   `json:"deleted_at"`
	ReportName          string         `json:"report_name"`
	ReportUuid          string         `json:"report_uuid"`
	ReportLocale        string         `json:"report_locale"`
	ReportDesc          sql.NullString `json:"report_desc"`
	ReportType          string         `json:"report_type"`
	ReportSp            string         `json:"report_sp"`
	ReportParamCount    int8           `json:"report_param_count"`
	ReportParamNames    sql.NullString `json:"report_param_names"`
	ReportParamTypes    sql.NullString `json:"report_param_types"`
	ReportParamOptions  sql.NullString `json:"report_param_options"`
	ReportParamOptional sql.NullString `json:"report_param_optional"`
	ReportAcl           sql.NullString `json:"report_acl"`
	ReportFormatting    sql.NullString `json:"report_formatting"`
}

type Patienttag struct {
	ID         int64        `json:"id"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	DeletedAt  sql.NullTime `json:"deleted_at"`
	Tag        string       `json:"tag"`
	Patient    int64        `json:"patient"`
	User       int64        `json:"user"`
	Datecreate time.Time    `json:"datecreate"`
	Dateexpire sql.NullTime `json:"dateexpire"`
}

type Payrec struct {
	ID            int64          `json:"id"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	DeletedAt     sql.NullTime   `json:"deleted_at"`
	Payrecdtadd   sql.NullTime   `json:"payrecdtadd"`
	Payrecdtmod   sql.NullTime   `json:"payrecdtmod"`
	Payrecpatient int64          `json:"payrecpatient"`
	Payreccat     int64          `json:"payreccat"`
	Payrecproc    int64          `json:"payrecproc"`
	Payrecsource  int64          `json:"payrecsource"`
	Payreclink    int64          `json:"payreclink"`
	Payrectype    int64          `json:"payrectype"`
	Payrecnum     sql.NullString `json:"payrecnum"`
	Payrecamt     float64        `json:"payrecamt"`
	Payreclock    sql.NullString `json:"payreclock"`
	Payrecdescrip string         `json:"payrecdescrip"`
	User          int64          `json:"user"`
	Active        string         `json:"active"`
}

type Pd struct {
	ID        int64          `json:"id"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
	Patient   int64          `json:"patient"`
	Module    string         `json:"module"`
	Contents  sql.NullString `json:"contents"`
}

type Pharmacy struct {
	ID        int64          `json:"id"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
	Phname    string         `json:"phname"`
	Phcity    sql.NullString `json:"phcity"`
	Phstate   sql.NullString `json:"phstate"`
}

type Phone struct {
	ID        int64        `json:"id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	Patient   int64        `json:"patient"`
	Type      string       `json:"type"`
	Number    string       `json:"number"`
	Active    string       `json:"active"`
	User      int64        `json:"user"`
}

type Photoid struct {
	ID          int64          `json:"id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
	Patient     int64          `json:"patient"`
	Photo       sql.NullString `json:"photo"`
	PhotoMime   string         `json:"photo_mime"`
	PageCount   int64          `json:"page_count"`
	Description string         `json:"description"`
	User        int64          `json:"user"`
	Active      string         `json:"active"`
}

type Physician struct {
	ID             int64         `json:"id"`
	CreatedAt      time.Time     `json:"created_at"`
	UpdatedAt      time.Time     `json:"updated_at"`
	DeletedAt      sql.NullTime  `json:"deleted_at"`
	Phylname       string        `json:"phylname"`
	Phyfname       string        `json:"phyfname"`
	Phymname       string        `json:"phymname"`
	Phytitle       string        `json:"phytitle"`
	Phypractice    int64         `json:"phypractice"`
	Phypracein     string        `json:"phypracein"`
	Phyaddr1a      string        `json:"phyaddr1a"`
	Phyaddr2a      string        `json:"phyaddr2a"`
	Phycitya       string        `json:"phycitya"`
	Phystatea      string        `json:"phystatea"`
	Phyzipa        string        `json:"phyzipa"`
	Phyphonea      string        `json:"phyphonea"`
	Phyfaxa        string        `json:"phyfaxa"`
	Phyaddr1b      string        `json:"phyaddr1b"`
	Phyaddr2b      string        `json:"phyaddr2b"`
	Phycityb       string        `json:"phycityb"`
	Phystateb      string        `json:"phystateb"`
	Phyzipb        string        `json:"phyzipb"`
	Phyphoneb      string        `json:"phyphoneb"`
	Phyfaxb        string        `json:"phyfaxb"`
	Phyemail       string        `json:"phyemail"`
	Phypager       string        `json:"phypager"`
	Phyupin        string        `json:"phyupin"`
	Physsn         string        `json:"physsn"`
	Phydegrees     string        `json:"phydegrees"`
	Physpecialties string        `json:"physpecialties"`
	Phyid1         string        `json:"phyid1"`
	Phystatus      int64         `json:"phystatus"`
	Phyref         string        `json:"phyref"`
	Phyrefcount    int64         `json:"phyrefcount"`
	Phyrefamt      float64       `json:"phyrefamt"`
	Phyrefcoll     float64       `json:"phyrefcoll"`
	Phychargemap   string        `json:"phychargemap"`
	Phyidmap       string        `json:"phyidmap"`
	Phygrpprac     sql.NullInt64 `json:"phygrpprac"`
	Phyanesth      int64         `json:"phyanesth"`
	Phyhl7id       string        `json:"phyhl7id"`
	Phydea         string        `json:"phydea"`
	Phyclia        string        `json:"phyclia"`
	Phynpi         string        `json:"phynpi"`
}

type Pnote struct {
	ID              int64          `json:"id"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
	Pnotesdt        sql.NullString `json:"pnotesdt"`
	Pnotesdtadd     sql.NullString `json:"pnotesdtadd"`
	Pnotesdtmod     sql.NullString `json:"pnotesdtmod"`
	Pnotespat       int64          `json:"pnotespat"`
	Pnotesdescrip   string         `json:"pnotesdescrip"`
	Pnotesdoc       int64          `json:"pnotesdoc"`
	Pnoteseoc       sql.NullString `json:"pnoteseoc"`
	PnotesS         string         `json:"pnotes_s"`
	PnotesO         string         `json:"pnotes_o"`
	PnotesA         string         `json:"pnotes_a"`
	PnotesP         string         `json:"pnotes_p"`
	PnotesI         string         `json:"pnotes_i"`
	PnotesE         string         `json:"pnotes_e"`
	PnotesR         string         `json:"pnotes_r"`
	Pnotessbp       sql.NullString `json:"pnotessbp"`
	Pnotesdbp       sql.NullString `json:"pnotesdbp"`
	Pnotestemp      sql.NullString `json:"pnotestemp"`
	Pnotesheartrate sql.NullString `json:"pnotesheartrate"`
	Pnotesresprate  sql.NullString `json:"pnotesresprate"`
	Weight          sql.NullString `json:"weight"`
	Height          sql.NullString `json:"height"`
	Bmi             sql.NullString `json:"bmi"`
	Iso             sql.NullString `json:"iso"`
	Locked          int64          `json:"locked"`
	User            int64          `json:"user"`
	Active          string         `json:"active"`
}

type Po struct {
	ID         int64        `json:"id"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	DeletedAt  sql.NullTime `json:"deleted_at"`
	Posname    string       `json:"posname"`
	Posdescrip string       `json:"posdescrip"`
	Posdtadd   sql.NullTime `json:"posdtadd"`
	Posdtmod   sql.NullTime `json:"posdtmod"`
}

type PortalAuditLog struct {
	ID        int64        `json:"id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	PatientID int64        `json:"patient_id"`
	Action    string       `json:"action"`
	IpAddress string       `json:"ip_address"`
	UserAgent string       `json:"user_agent"`
	Success   bool         `json:"success"`
}

type Practice struct {
	ID        int64          `json:"id"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
	Pracname  string         `json:"pracname"`
	Pracein   sql.NullString `json:"pracein"`
	Addr1a    sql.NullString `json:"addr1a"`
	Addr2a    sql.NullString `json:"addr2a"`
	Citya     sql.NullString `json:"citya"`
	Statea    sql.NullString `json:"statea"`
	Zipa      sql.NullString `json:"zipa"`
	Phonea    sql.NullString `json:"phonea"`
	Faxa      sql.NullString `json:"faxa"`
	Addr1b    sql.NullString `json:"addr1b"`
	Addr2b    sql.NullString `json:"addr2b"`
	Cityb     sql.NullString `json:"cityb"`
	Stateb    sql.NullString `json:"stateb"`
	Zipb      sql.NullString `json:"zipb"`
	Phoneb    sql.NullString `json:"phoneb"`
	Faxb      sql.NullString `json:"faxb"`
	Email     sql.NullString `json:"email"`
	Cellular  sql.NullString `json:"cellular"`
	Pracnpi   string         `json:"pracnpi"`
}

type Prescription struct {
	ID                  int64          `json:"id"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
	DeletedAt           sql.NullTime   `json:"deleted_at"`
	Patient             int64          `json:"patient"`
	DrugName            string         `json:"drug_name"`
	Dosage              string         `json:"dosage"`
	Frequency           string         `json:"frequency"`
	Quantity            string         `json:"quantity"`
	Refills             int64          `json:"refills"`
	DateWritten         time.Time      `json:"date_written"`
	PrescribingProvider int64          `json:"prescribing_provider"`
	Pharmacy            string         `json:"pharmacy"`
	Status              string         `json:"status"`
	Notes               sql.NullString `json:"notes"`
	User                int64          `json:"user"`
}

type PreviousOperation struct {
	ID            int64        `json:"id"`
	CreatedAt     time.Time    `json:"created_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
	DeletedAt     sql.NullTime `json:"deleted_at"`
	Patient       int64        `json:"patient"`
	OperationDate sql.NullTime `json:"operation_date"`
	Operation     string       `json:"operation"`
	User          int64        `json:"user"`
}

type Procrec struct {
	ID                int64          `json:"id"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	DeletedAt         sql.NullTime   `json:"deleted_at"`
	Procpatient       int64          `json:"procpatient"`
	Proceoc           sql.NullString `json:"proceoc"`
	Proccpt           int64          `json:"proccpt"`
	Proccptmod        int64          `json:"proccptmod"`
	Proccptmod2       int64          `json:"proccptmod2"`
	Proccptmod3       int64          `json:"proccptmod3"`
	Procdiag1         int64          `json:"procdiag1"`
	Procdiag2         int64          `json:"procdiag2"`
	Procdiag3         int64          `json:"procdiag3"`
	Procdiag4         int64          `json:"procdiag4"`
	Procdiagset       string         `json:"procdiagset"`
	Proccharges       float64        `json:"proccharges"`
	Procunits         float64        `json:"procunits"`
	Procvoucher       sql.NullString `json:"procvoucher"`
	Procphysician     int64          `json:"procphysician"`
	Procdt            time.Time      `json:"procdt"`
	Procdtend         sql.NullTime   `json:"procdtend"`
	Procpos           int64          `json:"procpos"`
	Proccomment       sql.NullString `json:"proccomment"`
	Procbalorig       float64        `json:"procbalorig"`
	Procbalcurrent    float64        `json:"procbalcurrent"`
	Procamtpain       float64        `json:"procamtpain"`
	Procbilled        int64          `json:"procbilled"`
	Procbillable      int64          `json:"procbillable"`
	Procauth          int64          `json:"procauth"`
	Procrefdoc        int64          `json:"procrefdoc"`
	Procrefdt         sql.NullTime   `json:"procrefdt"`
	Procamtallowed    sql.NullString `json:"procamtallowed"`
	Procdtbilled      sql.NullTime   `json:"procdtbilled"`
	Proccurcovid      int64          `json:"proccurcovid"`
	Proccurcovtp      int64          `json:"proccurcovtp"`
	Proccov1          int64          `json:"proccov1"`
	Proccov2          int64          `json:"proccov2"`
	Proccov3          int64          `json:"proccov3"`
	Proccov4          int64          `json:"proccov4"`
	Procmedicaidref   sql.NullString `json:"procmedicaidref"`
	Procmedicaidresub sql.NullString `json:"procmedicaidresub"`
	Proclabcharges    float64        `json:"proclabcharges"`
	Procstatus        sql.NullString `json:"procstatus"`
	Procslidingscale  sql.NullString `json:"procslidingscale"`
	Proctosoverride   int64          `json:"proctosoverride"`
	Orderid           int64          `json:"orderid"`
	User              int64          `json:"user"`
	Active            string         `json:"active"`
}

type Referral struct {
	ID                int64        `json:"id"`
	CreatedAt         time.Time    `json:"created_at"`
	UpdatedAt         time.Time    `json:"updated_at"`
	DeletedAt         sql.NullTime `json:"deleted_at"`
	Patient           int64        `json:"patient"`
	ReferringProvider int64        `json:"referring_provider"`
	ReferralTo        int64        `json:"referral_to"`
	ReferralType      string       `json:"referral_type"`
	Reason            string       `json:"reason"`
	Status            string       `json:"status"`
	DateReferred      time.Time    `json:"date_referred"`
	DateCompleted     sql.NullTime `json:"date_completed"`
	Notes             string       `json:"notes"`
	User              int64        `json:"user"`
	Active            string       `json:"active"`
}

type Reminder struct {
	ID          int64          `json:"id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
	User        int64          `json:"user"`
	Patient     sql.NullInt64  `json:"patient"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	DueDate     sql.NullTime   `json:"due_date"`
	Priority    int32          `json:"priority"`
	Status      string         `json:"status"`
	CompletedAt sql.NullTime   `json:"completed_at"`
}

type Rxrefillrequest struct {
	ID        int64          `json:"id"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
	User      int64          `json:"user"`
	Patient   int64          `json:"patient"`
	Provider  int64          `json:"provider"`
	Rxorig    sql.NullString `json:"rxorig"`
	Note      string         `json:"note"`
	Approved  sql.NullTime   `json:"approved"`
	Locked    int64          `json:"locked"`
}

type ScannedDoc struct {
	ID           int64        `json:"id"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
	Patient      int64        `json:"patient"`
	Filename     string       `json:"filename"`
	Description  string       `json:"description"`
	PageCount    int64        `json:"page_count"`
	DocumentDate sql.NullTime `json:"document_date"`
	User         int64        `json:"user"`
	Active       string       `json:"active"`
}

type Scheduler struct {
	ID              int64          `json:"id"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
	Caldateof       time.Time      `json:"caldateof"`
	Calcreated      time.Time      `json:"calcreated"`
	Calmodified     sql.NullTime   `json:"calmodified"`
	Caltype         string         `json:"caltype"`
	Calhour         int64          `json:"calhour"`
	Calminute       int64          `json:"calminute"`
	Calduration     int64          `json:"calduration"`
	Calfacility     sql.NullInt64  `json:"calfacility"`
	Calroom         sql.NullInt64  `json:"calroom"`
	Calphysician    int64          `json:"calphysician"`
	Calpatient      int64          `json:"calpatient"`
	Calcptcode      sql.NullInt64  `json:"calcptcode"`
	Calstatus       string         `json:"calstatus"`
	Calprenote      string         `json:"calprenote"`
	Calpostnote     sql.NullString `json:"calpostnote"`
	Calmark         int64          `json:"calmark"`
	Calgroupid      int64          `json:"calgroupid"`
	Calgroupmembers sql.NullString `json:"calgroupmembers"`
	Calrecurnote    sql.NullString `json:"calrecurnote"`
	Calrecurid      int64          `json:"calrecurid"`
	Calappttemplate int64          `json:"calappttemplate"`
	Calattendees    sql.NullString `json:"calattendees"`
	User            int64          `json:"user"`
}

type SchedulerStatus struct {
	ID        int64        `json:"id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	Csstamp   time.Time    `json:"csstamp"`
	Cspatient int64        `json:"cspatient"`
	Csappt    int64        `json:"csappt"`
	Csstatus  string       `json:"csstatus"`
	Csenote   string       `json:"csenote"`
	User      int64        `json:"user"`
}

type Schedulerblockslot struct {
	ID          int64        `json:"id"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
	Sbsdate     time.Time    `json:"sbsdate"`
	Sbshour     int64        `json:"sbshour"`
	Sbsminute   int64        `json:"sbsminute"`
	Sbsduration int64        `json:"sbsduration"`
	Sbsprovider int64        `json:"sbsprovider"`
	Sbsreason   string       `json:"sbsreason"`
	User        int64        `json:"user"`
}

type Schedulerstatustype struct {
	ID        int64        `json:"id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	Sname     string       `json:"sname"`
	Sdescrip  string       `json:"sdescrip"`
	Scolor    string       `json:"scolor"`
	Sage      int64        `json:"sage"`
}

type Signature struct {
	ID                int64          `json:"id"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	DeletedAt         sql.NullTime   `json:"deleted_at"`
	Patient           int64          `json:"patient"`
	Module            string         `json:"module"`
	ModuleField       string         `json:"module_field"`
	Oid               int64          `json:"oid"`
	SignatureData     sql.NullString `json:"signature_data"`
	Format            string         `json:"format"`
	CollectorLocation string         `json:"collector_location"`
	CollectorModel    string         `json:"collector_model"`
	CollectorJobid    string         `json:"collector_jobid"`
	CollectorFinished bool           `json:"collector_finished"`
	User              int64          `json:"user"`
}

type Smsprovider struct {
	ID          int64        `json:"id"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
	Name        string       `json:"name"`
	EmailDomain string       `json:"email_domain"`
	Active      string       `json:"active"`
}

type Specialty struct {
	ID           int64        `json:"id"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
	Name         string       `json:"name"`
	DisplayValue string       `json:"display_value"`
	Active       string       `json:"active"`
}

type Superbill struct {
	ID           int64        `json:"id"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
	Patient      int64        `json:"patient"`
	DateFrom     time.Time    `json:"date_from"`
	DateTo       time.Time    `json:"date_to"`
	Provider     int64        `json:"provider"`
	Status       string       `json:"status"`
	TotalCharges float64      `json:"total_charges"`
	DateCreated  time.Time    `json:"date_created"`
	User         int64        `json:"user"`
	Active       string       `json:"active"`
}

type SuperbillTemplate struct {
	ID           int64          `json:"id"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
	Name         string         `json:"name"`
	TemplateData sql.NullString `json:"template_data"`
	Active       string         `json:"active"`
}

type Systemnotification struct {
	ID        int64        `json:"id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	Stamp     time.Time    `json:"stamp"`
	Nuser     int64        `json:"nuser"`
	Ntext     string       `json:"ntext"`
	Naction   string       `json:"naction"`
	Nmodule   string       `json:"nmodule"`
	Npatient  int64        `json:"npatient"`
}

type Tool struct {
	ID              int64          `json:"id"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
	ToolName        string         `json:"tool_name"`
	ToolDescription sql.NullString `json:"tool_description"`
	ToolClass       string         `json:"tool_class"`
	ToolParameters  sql.NullString `json:"tool_parameters"`
	Active          string         `json:"active"`
}

type UnfiledDoc struct {
	ID           int64          `json:"id"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
	Filename     string         `json:"filename"`
	PageCount    int64          `json:"page_count"`
	FileType     string         `json:"file_type"`
	ReceivedDate sql.NullTime   `json:"received_date"`
	AssignedTo   int64          `json:"assigned_to"`
	Status       string         `json:"status"`
	Notes        sql.NullString `json:"notes"`
	User         int64          `json:"user"`
	Active       string         `json:"active"`
}

type UnreadDoc struct {
	ID              int64          `json:"id"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
	DocumentType    string         `json:"document_type"`
	Patient         int64          `json:"patient"`
	Filename        string         `json:"filename"`
	PageCount       int64          `json:"page_count"`
	SentDate        sql.NullTime   `json:"sent_date"`
	SendingProvider int64          `json:"sending_provider"`
	AssignedTo      int64          `json:"assigned_to"`
	Reviewed        bool           `json:"reviewed"`
	ReviewDate      sql.NullTime   `json:"review_date"`
	Notes           sql.NullString `json:"notes"`
	User            int64          `json:"user"`
	Active          string         `json:"active"`
}

type User struct {
	ID                 int64          `json:"id"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
	DeletedAt          sql.NullTime   `json:"deleted_at"`
	Username           string         `json:"username"`
	Userpassword       string         `json:"userpassword"`
	UserpasswordBcrypt string         `json:"userpassword_bcrypt"`
	Usertype           sql.NullString `json:"usertype"`
	Userrealphy        int64          `json:"userrealphy"`
	Userfname          sql.NullString `json:"userfname"`
	Usermname          sql.NullString `json:"usermname"`
	Userlname          sql.NullString `json:"userlname"`
	Userdescrip        sql.NullString `json:"userdescrip"`
	Userlevel          sql.NullString `json:"userlevel"`
	Userfac            sql.NullString `json:"userfac"`
	Userphy            sql.NullString `json:"userphy"`
	Userphygrp         sql.NullString `json:"userphygrp"`
	Usermanageopt      sql.NullString `json:"usermanageopt"`
	Useremail          sql.NullString `json:"useremail"`
	Usersms            sql.NullInt64  `json:"usersms"`
	Usersmsprovider    sql.NullInt64  `json:"usersmsprovider"`
	Usertitle          sql.NullString `json:"usertitle"`
}

type UserGroup struct {
	ID        int64        `json:"id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	UserID    int64        `json:"user_id"`
	GroupID   int64        `json:"group_id"`
}

type UserPreference struct {
	ID           int64          `json:"id"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
	OptionKey    string         `json:"option_key"`
	DefaultValue string         `json:"default_value"`
	Title        string         `json:"title"`
	Section      string         `json:"section"`
	OptionType   string         `json:"option_type"`
	Options      sql.NullString `json:"options"`
}

type Usergroup struct {
	ID           int64        `json:"id"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
	Groupname    string       `json:"groupname"`
	Groupdescrip string       `json:"groupdescrip"`
}

type Vital struct {
	ID               int64          `json:"id"`
	Patient          int64          `json:"patient"`
	DateTaken        time.Time      `json:"date_taken"`
	Systolic         sql.NullInt32  `json:"systolic"`
	Diastolic        sql.NullInt32  `json:"diastolic"`
	HeartRate        sql.NullInt32  `json:"heart_rate"`
	RespiratoryRate  sql.NullInt32  `json:"respiratory_rate"`
	Temperature      sql.NullString `json:"temperature"`
	OxygenSaturation sql.NullInt32  `json:"oxygen_saturation"`
	HeightCm         sql.NullString `json:"height_cm"`
	WeightKg         sql.NullString `json:"weight_kg"`
	Bmi              sql.NullString `json:"bmi"`
	Notes            sql.NullString `json:"notes"`
	User             int64          `json:"user"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	DeletedAt        sql.NullTime   `json:"deleted_at"`
}

type WorkflowStatus struct {
	ID              int64        `json:"id"`
	CreatedAt       time.Time    `json:"created_at"`
	UpdatedAt       time.Time    `json:"updated_at"`
	DeletedAt       sql.NullTime `json:"deleted_at"`
	Stamp           time.Time    `json:"stamp"`
	Patient         int64        `json:"patient"`
	User            int64        `json:"user"`
	StatusType      int64        `json:"status_type"`
	StatusCompleted bool         `json:"status_completed"`
}

type WorkflowStatusType struct {
	ID           int64        `json:"id"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
	StatusName   string       `json:"status_name"`
	StatusOrder  string       `json:"status_order"`
	StatusModule string       `json:"status_module"`
	Active       bool         `json:"active"`
}

type Zipcode struct {
	ID        int64        `json:"id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	Zip       string       `json:"zip"`
	City      string       `json:"city"`
	State     string       `json:"state"`
	Latitude  float64      `json:"latitude"`
	Longitude float64      `json:"longitude"`
	Timezone  int64        `json:"timezone"`
	Dst       int64        `json:"dst"`
	Country   string       `json:"country"`
}
