// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: next_available.sql

package dbgen

import (
	"context"
	"time"
)

const findNextAvailable = `-- name: FindNextAvailable :many
SELECT calhour, calminute, calduration
FROM scheduler
WHERE calphysician = ?
AND caldateof = ?
AND calstatus NOT IN ('cancelled', 'noshow')
ORDER BY calhour, calminute
`

type FindNextAvailableParams struct {
	ProviderID int64     `json:"provider_id"`
	ReqDate    time.Time `json:"req_date"`
}

type FindNextAvailableRow struct {
	Calhour     int64 `json:"calhour"`
	Calminute   int64 `json:"calminute"`
	Calduration int64 `json:"calduration"`
}

func (q *Queries) FindNextAvailable(ctx context.Context, arg FindNextAvailableParams) ([]FindNextAvailableRow, error) {
	rows, err := q.db.QueryContext(ctx, findNextAvailable, arg.ProviderID, arg.ReqDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindNextAvailableRow
	for rows.Next() {
		var i FindNextAvailableRow
		if err := rows.Scan(&i.Calhour, &i.Calminute, &i.Calduration); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
