// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package dbgen

import (
	"context"
)

const patientNotifications = `-- name: PatientNotifications :many
SELECT id, created_at, updated_at, deleted_at, stamp, nuser, ntext, naction, nmodule, npatient FROM systemnotification
WHERE npatient = ?
ORDER BY stamp DESC
`

// PatientNotifications returns notifications for a specific patient
func (q *Queries) PatientNotifications(ctx context.Context, patientID int64) ([]Systemnotification, error) {
	rows, err := q.db.QueryContext(ctx, patientNotifications, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Systemnotification
	for rows.Next() {
		var i Systemnotification
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Stamp,
			&i.Nuser,
			&i.Ntext,
			&i.Naction,
			&i.Nmodule,
			&i.Npatient,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unreadCount = `-- name: UnreadCount :one
SELECT COUNT(*) FROM systemnotification
WHERE nuser = ?
`

// UnreadCount returns the total number of notifications for a user
func (q *Queries) UnreadCount(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, unreadCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const userNotifications = `-- name: UserNotifications :many
SELECT id, created_at, updated_at, deleted_at, stamp, nuser, ntext, naction, nmodule, npatient FROM systemnotification
WHERE nuser = ?
ORDER BY stamp DESC
LIMIT 50
`

// UserNotifications returns the most recent notifications for a user
func (q *Queries) UserNotifications(ctx context.Context, userID int64) ([]Systemnotification, error) {
	rows, err := q.db.QueryContext(ctx, userNotifications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Systemnotification
	for rows.Next() {
		var i Systemnotification
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Stamp,
			&i.Nuser,
			&i.Ntext,
			&i.Naction,
			&i.Nmodule,
			&i.Npatient,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
