// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: patient.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const patientEmrAttachments = `-- name: PatientEmrAttachments :many
SELECT
  p.patient,
  p.module,
  p.oid,
  p.annotation,
  p.summary,
  p.stamp,
  DATE_FORMAT(p.stamp, '%m/%d/%Y') AS date_mdy,
  m.module_name AS type,
  m.module_class AS module_namespace,
  p.locked,
  p.id
FROM patient_emr p
LEFT OUTER JOIN modules m ON m.module_table = p.module
WHERE p.patient = ?
  AND m.module_hidden = 0
`

type PatientEmrAttachmentsRow struct {
	Patient         int64          `json:"patient"`
	Module          string         `json:"module"`
	Oid             int64          `json:"oid"`
	Annotation      sql.NullString `json:"annotation"`
	Summary         string         `json:"summary"`
	Stamp           time.Time      `json:"stamp"`
	DateMdy         string         `json:"date_mdy"`
	Type            sql.NullString `json:"type"`
	ModuleNamespace sql.NullString `json:"module_namespace"`
	Locked          bool           `json:"locked"`
	ID              int64          `json:"id"`
}

// Patient EMR attachments: list all EMR entries for a patient
func (q *Queries) PatientEmrAttachments(ctx context.Context, patientID int64) ([]PatientEmrAttachmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, patientEmrAttachments, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatientEmrAttachmentsRow
	for rows.Next() {
		var i PatientEmrAttachmentsRow
		if err := rows.Scan(
			&i.Patient,
			&i.Module,
			&i.Oid,
			&i.Annotation,
			&i.Summary,
			&i.Stamp,
			&i.DateMdy,
			&i.Type,
			&i.ModuleNamespace,
			&i.Locked,
			&i.ID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patientEmrAttachmentsByModule = `-- name: PatientEmrAttachmentsByModule :many
SELECT
  p.patient,
  p.module,
  p.oid,
  p.annotation,
  p.summary,
  p.stamp,
  DATE_FORMAT(p.stamp, '%m/%d/%Y') AS date_mdy,
  m.module_name AS type,
  m.module_class AS module_namespace,
  p.locked,
  p.id
FROM patient_emr p
LEFT OUTER JOIN modules m ON m.module_table = p.module
WHERE p.patient = ?
  AND p.module = ?
  AND m.module_hidden = 0
`

type PatientEmrAttachmentsByModuleParams struct {
	PatientID int64  `json:"patient_id"`
	Module    string `json:"module"`
}

type PatientEmrAttachmentsByModuleRow struct {
	Patient         int64          `json:"patient"`
	Module          string         `json:"module"`
	Oid             int64          `json:"oid"`
	Annotation      sql.NullString `json:"annotation"`
	Summary         string         `json:"summary"`
	Stamp           time.Time      `json:"stamp"`
	DateMdy         string         `json:"date_mdy"`
	Type            sql.NullString `json:"type"`
	ModuleNamespace sql.NullString `json:"module_namespace"`
	Locked          bool           `json:"locked"`
	ID              int64          `json:"id"`
}

// Patient EMR attachments filtered by module
func (q *Queries) PatientEmrAttachmentsByModule(ctx context.Context, arg PatientEmrAttachmentsByModuleParams) ([]PatientEmrAttachmentsByModuleRow, error) {
	rows, err := q.db.QueryContext(ctx, patientEmrAttachmentsByModule, arg.PatientID, arg.Module)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatientEmrAttachmentsByModuleRow
	for rows.Next() {
		var i PatientEmrAttachmentsByModuleRow
		if err := rows.Scan(
			&i.Patient,
			&i.Module,
			&i.Oid,
			&i.Annotation,
			&i.Summary,
			&i.Stamp,
			&i.DateMdy,
			&i.Type,
			&i.ModuleNamespace,
			&i.Locked,
			&i.ID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patientInformation = `-- name: PatientInformation :one
SELECT
  CONCAT(p.ptlname, ', ', p.ptfname, IF(p.ptmname IS NOT NULL, CONCAT(' ', p.ptmname), '')) AS patient_name,
  p.ptid AS patient_id,
  p.ptdob AS date_of_birth,
  p.ptprimarylanguage AS language,
  DATE_FORMAT(p.ptdob, '%m/%d/%Y') AS date_of_birth_mdy,
  CASE
    WHEN ((TO_DAYS(NOW()) - TO_DAYS(p.ptdob)) / 365) >= 2
    THEN CONCAT(FLOOR((TO_DAYS(NOW()) - TO_DAYS(p.ptdob)) / 365), ' years')
    ELSE CONCAT(FLOOR((TO_DAYS(NOW()) - TO_DAYS(p.ptdob)) / 30), ' months')
  END AS age,
  pa.line1 AS address_line_1,
  pa.line2 AS address_line_2,
  pa.city AS city,
  pa.stpr AS state,
  pa.postal AS postal,
  CONCAT(pa.city, ', ', pa.stpr, ' ', pa.postal) AS csz,
  CASE
    WHEN p.id IN (
      SELECT al.patient FROM allergies al
      WHERE al.patient = ? AND al.active = 'active'
    )
    THEN 'true' ELSE 'false'
  END AS hasallergy,
  CONCAT(phy.phylname, ', ', phy.phyfname, ' ', phy.phymname) AS pcp,
  CONCAT(fac.psrname, ' (', fac.psrcity, ', ', fac.psrstate, ')') AS facility,
  CONCAT(ph.phname, ' (', ph.phcity, ', ', ph.phstate, ')') AS pharmacy
FROM patient p
LEFT OUTER JOIN patient_address pa ON pa.patient = p.id AND pa.active = TRUE
LEFT OUTER JOIN physician phy ON phy.id = p.ptpcp
LEFT OUTER JOIN facility fac ON fac.id = p.ptprimaryfacility
LEFT OUTER JOIN pharmacy ph ON ph.id = p.ptpharmacy
WHERE p.id = ?
GROUP BY p.id
`

type PatientInformationParams struct {
	PatientID int64 `json:"patient_id"`
}

type PatientInformationRow struct {
	PatientName    string         `json:"patient_name"`
	PatientID      string         `json:"patient_id"`
	DateOfBirth    sql.NullTime   `json:"date_of_birth"`
	Language       string         `json:"language"`
	DateOfBirthMdy string         `json:"date_of_birth_mdy"`
	Age            interface{}    `json:"age"`
	AddressLine1   sql.NullString `json:"address_line_1"`
	AddressLine2   sql.NullString `json:"address_line_2"`
	City           sql.NullString `json:"city"`
	State          sql.NullString `json:"state"`
	Postal         sql.NullString `json:"postal"`
	Csz            string         `json:"csz"`
	Hasallergy     string         `json:"hasallergy"`
	Pcp            string         `json:"pcp"`
	Facility       string         `json:"facility"`
	Pharmacy       string         `json:"pharmacy"`
}

// Patient information: full patient details with joins
func (q *Queries) PatientInformation(ctx context.Context, arg PatientInformationParams) (PatientInformationRow, error) {
	row := q.db.QueryRowContext(ctx, patientInformation, arg.PatientID, arg.PatientID)
	var i PatientInformationRow
	err := row.Scan(
		&i.PatientName,
		&i.PatientID,
		&i.DateOfBirth,
		&i.Language,
		&i.DateOfBirthMdy,
		&i.Age,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.Postal,
		&i.Csz,
		&i.Hasallergy,
		&i.Pcp,
		&i.Facility,
		&i.Pharmacy,
	)
	return i, err
}
