// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: patients.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const countPatients = `-- name: CountPatients :one
SELECT COUNT(*) AS total FROM patient WHERE ptarchive = 0
`

// Patient count (non-archived)
func (q *Queries) CountPatients(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPatients)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const listPatients = `-- name: ListPatients :many
SELECT
  id,
  ptlname AS last_name,
  ptfname AS first_name,
  ptmname AS middle_name,
  ptsuffix AS suffix,
  ptsex AS gender,
  ptid AS patient_id,
  ptdob AS date_of_birth,
  ptarchive AS archived,
  created_at,
  updated_at
FROM patient
WHERE ptarchive = 0
ORDER BY ptlname, ptfname, ptmname
LIMIT ? OFFSET ?
`

type ListPatientsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPatientsRow struct {
	ID          int64          `json:"id"`
	LastName    string         `json:"last_name"`
	FirstName   string         `json:"first_name"`
	MiddleName  sql.NullString `json:"middle_name"`
	Suffix      string         `json:"suffix"`
	Gender      string         `json:"gender"`
	PatientID   string         `json:"patient_id"`
	DateOfBirth sql.NullTime   `json:"date_of_birth"`
	Archived    int64          `json:"archived"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

// Patient list with pagination
func (q *Queries) ListPatients(ctx context.Context, arg ListPatientsParams) ([]ListPatientsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPatients, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPatientsRow
	for rows.Next() {
		var i ListPatientsRow
		if err := rows.Scan(
			&i.ID,
			&i.LastName,
			&i.FirstName,
			&i.MiddleName,
			&i.Suffix,
			&i.Gender,
			&i.PatientID,
			&i.DateOfBirth,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patientCreate = `-- name: PatientCreate :execresult
INSERT INTO patient (
  ptlname, ptfname, ptmname, ptsuffix, ptsex, ptid, ptdob,
  ptarchive, ptbilltype, user, stamp
) VALUES (
  ?, ?, ?, ?,
  ?, ?, ?,
  0, '', ?, NOW()
)
`

type PatientCreateParams struct {
	Ptlname  string         `json:"ptlname"`
	Ptfname  string         `json:"ptfname"`
	Ptmname  sql.NullString `json:"ptmname"`
	Ptsuffix string         `json:"ptsuffix"`
	Ptsex    string         `json:"ptsex"`
	Ptid     string         `json:"ptid"`
	Ptdob    sql.NullTime   `json:"ptdob"`
	User     int64          `json:"user"`
}

// Patient create: insert a new patient record
func (q *Queries) PatientCreate(ctx context.Context, arg PatientCreateParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, patientCreate,
		arg.Ptlname,
		arg.Ptfname,
		arg.Ptmname,
		arg.Ptsuffix,
		arg.Ptsex,
		arg.Ptid,
		arg.Ptdob,
		arg.User,
	)
}

const patientPicklistByEither = `-- name: PatientPicklistByEither :many
SELECT
  CONCAT(ptlname, ', ', ptfname, ' (', ptid, ')') AS value,
  id
FROM patient
WHERE (
  ptfname LIKE CONCAT(?, '%')
  OR ptlname LIKE CONCAT(?, '%')
)
  AND (ptarchive IS NULL OR ptarchive = 0)
LIMIT 20
`

type PatientPicklistByEitherParams struct {
	Query interface{} `json:"query"`
}

type PatientPicklistByEitherRow struct {
	Value string `json:"value"`
	ID    int64  `json:"id"`
}

// Patient picklist: search by either first/last name (either mode)
func (q *Queries) PatientPicklistByEither(ctx context.Context, arg PatientPicklistByEitherParams) ([]PatientPicklistByEitherRow, error) {
	rows, err := q.db.QueryContext(ctx, patientPicklistByEither, arg.Query, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatientPicklistByEitherRow
	for rows.Next() {
		var i PatientPicklistByEitherRow
		if err := rows.Scan(&i.Value, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patientPicklistByFirstName = `-- name: PatientPicklistByFirstName :many
SELECT
  CONCAT(ptlname, ', ', ptfname, ' (', ptid, ')') AS value,
  id
FROM patient
WHERE ptfname LIKE CONCAT(?, '%')
  AND (ptarchive IS NULL OR ptarchive = 0)
LIMIT 20
`

type PatientPicklistByFirstNameRow struct {
	Value string `json:"value"`
	ID    int64  `json:"id"`
}

// Patient picklist: search by first name
func (q *Queries) PatientPicklistByFirstName(ctx context.Context, query interface{}) ([]PatientPicklistByFirstNameRow, error) {
	rows, err := q.db.QueryContext(ctx, patientPicklistByFirstName, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatientPicklistByFirstNameRow
	for rows.Next() {
		var i PatientPicklistByFirstNameRow
		if err := rows.Scan(&i.Value, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patientPicklistByFirstNameOrId = `-- name: PatientPicklistByFirstNameOrId :many
SELECT
  CONCAT(ptlname, ', ', ptfname, ' (', ptid, ')') AS value,
  id
FROM patient
WHERE (
  ptfname LIKE CONCAT(?, '%')
  OR ptid LIKE CONCAT(?, '%')
)
  AND (ptarchive IS NULL OR ptarchive = 0)
LIMIT 20
`

type PatientPicklistByFirstNameOrIdParams struct {
	Query interface{} `json:"query"`
}

type PatientPicklistByFirstNameOrIdRow struct {
	Value string `json:"value"`
	ID    int64  `json:"id"`
}

// Patient picklist: search by first name OR patient ID
func (q *Queries) PatientPicklistByFirstNameOrId(ctx context.Context, arg PatientPicklistByFirstNameOrIdParams) ([]PatientPicklistByFirstNameOrIdRow, error) {
	rows, err := q.db.QueryContext(ctx, patientPicklistByFirstNameOrId, arg.Query, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatientPicklistByFirstNameOrIdRow
	for rows.Next() {
		var i PatientPicklistByFirstNameOrIdRow
		if err := rows.Scan(&i.Value, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patientPicklistByLastName = `-- name: PatientPicklistByLastName :many
SELECT
  CONCAT(ptlname, ', ', ptfname, ' (', ptid, ')') AS value,
  id
FROM patient
WHERE ptlname LIKE CONCAT(?, '%')
  AND (ptarchive IS NULL OR ptarchive = 0)
LIMIT 20
`

type PatientPicklistByLastNameRow struct {
	Value string `json:"value"`
	ID    int64  `json:"id"`
}

// Patient picklist: search by last name
func (q *Queries) PatientPicklistByLastName(ctx context.Context, query interface{}) ([]PatientPicklistByLastNameRow, error) {
	rows, err := q.db.QueryContext(ctx, patientPicklistByLastName, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatientPicklistByLastNameRow
	for rows.Next() {
		var i PatientPicklistByLastNameRow
		if err := rows.Scan(&i.Value, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patientPicklistByLastNameOrId = `-- name: PatientPicklistByLastNameOrId :many
SELECT
  CONCAT(ptlname, ', ', ptfname, ' (', ptid, ')') AS value,
  id
FROM patient
WHERE (
  ptlname LIKE CONCAT(?, '%')
  OR ptid LIKE CONCAT(?, '%')
)
  AND (ptarchive IS NULL OR ptarchive = 0)
LIMIT 20
`

type PatientPicklistByLastNameOrIdParams struct {
	Query interface{} `json:"query"`
}

type PatientPicklistByLastNameOrIdRow struct {
	Value string `json:"value"`
	ID    int64  `json:"id"`
}

// Patient picklist: search by last name OR patient ID
func (q *Queries) PatientPicklistByLastNameOrId(ctx context.Context, arg PatientPicklistByLastNameOrIdParams) ([]PatientPicklistByLastNameOrIdRow, error) {
	rows, err := q.db.QueryContext(ctx, patientPicklistByLastNameOrId, arg.Query, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatientPicklistByLastNameOrIdRow
	for rows.Next() {
		var i PatientPicklistByLastNameOrIdRow
		if err := rows.Scan(&i.Value, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patientPicklistByName = `-- name: PatientPicklistByName :many
SELECT
  CONCAT(ptlname, ', ', ptfname, ' (', ptid, ')') AS value,
  id
FROM patient
WHERE ptlname LIKE CONCAT(?, '%')
  AND ptfname LIKE CONCAT(?, '%')
  AND (ptarchive IS NULL OR ptarchive = 0)
LIMIT 20
`

type PatientPicklistByNameParams struct {
	LastName  interface{} `json:"last_name"`
	FirstName interface{} `json:"first_name"`
}

type PatientPicklistByNameRow struct {
	Value string `json:"value"`
	ID    int64  `json:"id"`
}

// Patient picklist: search by first AND last name
func (q *Queries) PatientPicklistByName(ctx context.Context, arg PatientPicklistByNameParams) ([]PatientPicklistByNameRow, error) {
	rows, err := q.db.QueryContext(ctx, patientPicklistByName, arg.LastName, arg.FirstName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatientPicklistByNameRow
	for rows.Next() {
		var i PatientPicklistByNameRow
		if err := rows.Scan(&i.Value, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patientPicklistByPatientId = `-- name: PatientPicklistByPatientId :many
SELECT
  CONCAT(ptlname, ', ', ptfname, ' (', ptid, ')') AS value,
  id
FROM patient
WHERE ptid LIKE CONCAT(?, '%')
  AND (ptarchive IS NULL OR ptarchive = 0)
LIMIT 20
`

type PatientPicklistByPatientIdRow struct {
	Value string `json:"value"`
	ID    int64  `json:"id"`
}

// Patient picklist: search by patient ID
func (q *Queries) PatientPicklistByPatientId(ctx context.Context, query interface{}) ([]PatientPicklistByPatientIdRow, error) {
	rows, err := q.db.QueryContext(ctx, patientPicklistByPatientId, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatientPicklistByPatientIdRow
	for rows.Next() {
		var i PatientPicklistByPatientIdRow
		if err := rows.Scan(&i.Value, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patientSearch = `-- name: PatientSearch :many
SELECT
  p.ptlname AS last_name,
  p.ptfname AS first_name,
  p.ptmname AS middle_name,
  p.ptid AS patient_id,
  FLOOR((TO_DAYS(NOW()) - TO_DAYS(p.ptdob)) / 365) AS age,
  p.ptdob AS date_of_birth,
  p.id AS id
FROM patient p
LEFT OUTER JOIN patient_address pa ON p.id = pa.patient
WHERE pa.active = 1
  AND (? IS NULL OR p.ptfname LIKE CONCAT('%', ?, '%'))
  AND (? IS NULL OR p.ptlname LIKE CONCAT('%', ?, '%'))
  AND (? IS NULL OR p.ptid LIKE CONCAT('%', ?, '%'))
  AND (? IS NULL OR pa.city LIKE CONCAT('%', ?, '%'))
  AND (? IS NULL OR pa.zip LIKE CONCAT('%', ?, '%'))
  AND (? IS NULL OR p.dmv LIKE CONCAT('%', ?, '%'))
  AND (? IS NULL OR p.pemail LIKE CONCAT('%', ?, '%'))
  AND (? IS NULL OR p.ssn LIKE CONCAT('%', ?, '%'))
  AND p.ptarchive = 0
ORDER BY p.ptlname, p.ptfname, p.ptmname
LIMIT 20
`

type PatientSearchParams struct {
	FirstName interface{} `json:"first_name"`
	LastName  interface{} `json:"last_name"`
	PatientID interface{} `json:"patient_id"`
	City      interface{} `json:"city"`
	Zip       interface{} `json:"zip"`
	Dmv       interface{} `json:"dmv"`
	Email     interface{} `json:"email"`
	Ssn       interface{} `json:"ssn"`
}

type PatientSearchRow struct {
	LastName    string         `json:"last_name"`
	FirstName   string         `json:"first_name"`
	MiddleName  sql.NullString `json:"middle_name"`
	PatientID   string         `json:"patient_id"`
	Age         int32          `json:"age"`
	DateOfBirth sql.NullTime   `json:"date_of_birth"`
	ID          int64          `json:"id"`
}

// Patient search with optional filters
func (q *Queries) PatientSearch(ctx context.Context, arg PatientSearchParams) ([]PatientSearchRow, error) {
	rows, err := q.db.QueryContext(ctx, patientSearch,
		arg.FirstName,
		arg.FirstName,
		arg.LastName,
		arg.LastName,
		arg.PatientID,
		arg.PatientID,
		arg.City,
		arg.City,
		arg.Zip,
		arg.Zip,
		arg.Dmv,
		arg.Dmv,
		arg.Email,
		arg.Email,
		arg.Ssn,
		arg.Ssn,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatientSearchRow
	for rows.Next() {
		var i PatientSearchRow
		if err := rows.Scan(
			&i.LastName,
			&i.FirstName,
			&i.MiddleName,
			&i.PatientID,
			&i.Age,
			&i.DateOfBirth,
			&i.ID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patientSearchDuplicates = `-- name: PatientSearchDuplicates :many
SELECT ptid FROM patient p
WHERE ptlname = ?
  AND ptfname = ?
  AND (? IS NULL OR ptmname = ?)
  AND (? IS NULL OR ptsuffix = ?)
  AND (? IS NULL OR ptdob = ?)
  AND ptarchive = 0
`

type PatientSearchDuplicatesParams struct {
	Ptlname  string         `json:"ptlname"`
	Ptfname  string         `json:"ptfname"`
	Ptmname  sql.NullString `json:"ptmname"`
	Ptsuffix sql.NullString `json:"ptsuffix"`
	Ptdob    sql.NullTime   `json:"ptdob"`
}

// Patient duplicate search (with optional middle name, suffix, DOB)
func (q *Queries) PatientSearchDuplicates(ctx context.Context, arg PatientSearchDuplicatesParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, patientSearchDuplicates,
		arg.Ptlname,
		arg.Ptfname,
		arg.Ptmname,
		arg.Ptmname,
		arg.Ptsuffix,
		arg.Ptsuffix,
		arg.Ptdob,
		arg.Ptdob,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var ptid string
		if err := rows.Scan(&ptid); err != nil {
			return nil, err
		}
		items = append(items, ptid)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patientTotalInSystem = `-- name: PatientTotalInSystem :one
SELECT COUNT(*) AS total FROM patient WHERE ptarchive = 0
`

// Patient total count (non-archived)
func (q *Queries) PatientTotalInSystem(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, patientTotalInSystem)
	var total int64
	err := row.Scan(&total)
	return total, err
}
