// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: patient_correspondence.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createCorrespondence = `-- name: CreateCorrespondence :execresult
INSERT INTO patient_correspondence (
  patient, correspondence_type, direction, contact_name, contact_method,
  summary, date, user, active, created_at, updated_at
) VALUES (
  ?, ?, ?,
  ?, ?,
  ?, ?,
  ?, 'active', NOW(), NOW()
)
`

type CreateCorrespondenceParams struct {
	PatientID          int64          `json:"patient_id"`
	CorrespondenceType string         `json:"correspondence_type"`
	Direction          string         `json:"direction"`
	ContactName        string         `json:"contact_name"`
	ContactMethod      string         `json:"contact_method"`
	Summary            sql.NullString `json:"summary"`
	Date               sql.NullTime   `json:"date"`
	UserID             int64          `json:"user_id"`
}

// Create a new correspondence entry
func (q *Queries) CreateCorrespondence(ctx context.Context, arg CreateCorrespondenceParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCorrespondence,
		arg.PatientID,
		arg.CorrespondenceType,
		arg.Direction,
		arg.ContactName,
		arg.ContactMethod,
		arg.Summary,
		arg.Date,
		arg.UserID,
	)
}

const listCorrespondence = `-- name: ListCorrespondence :many
SELECT id, created_at, updated_at, deleted_at, patient, correspondence_type, direction, contact_name, contact_method, summary, date, user, active FROM patient_correspondence
WHERE patient = ?
  AND active = 'active'
ORDER BY date DESC
`

// List correspondence for a patient, ordered by date descending
func (q *Queries) ListCorrespondence(ctx context.Context, patientID int64) ([]PatientCorrespondence, error) {
	rows, err := q.db.QueryContext(ctx, listCorrespondence, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatientCorrespondence
	for rows.Next() {
		var i PatientCorrespondence
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Patient,
			&i.CorrespondenceType,
			&i.Direction,
			&i.ContactName,
			&i.ContactMethod,
			&i.Summary,
			&i.Date,
			&i.User,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
