// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const patientLedger = `-- name: PatientLedger :many
SELECT
  'charge' AS entry_type,
  p.id,
  p.procdt AS date,
  p.proccharges AS amount,
  p.procbalcurrent AS balance,
  cpt.abbrev AS cpt_code,
  p.proccomment AS description,
  p.procstatus AS status
FROM procrec p
LEFT OUTER JOIN cpt cpt ON cpt.id = p.proccpt
WHERE p.procpatient = ?
UNION ALL
SELECT
  'payment' AS entry_type,
  pr.id,
  pr.payrecdtadd AS date,
  pr.payrecamt AS amount,
  0.0 AS balance,
  '' AS cpt_code,
  pr.payrecdescrip AS description,
  '' AS status
FROM payrec pr
WHERE pr.payrecpatient = ?
  AND pr.active = 'active'
ORDER BY date DESC
`

type PatientLedgerParams struct {
	PatientID int64 `json:"patient_id"`
}

type PatientLedgerRow struct {
	EntryType   string         `json:"entry_type"`
	ID          int64          `json:"id"`
	Date        time.Time      `json:"date"`
	Amount      float64        `json:"amount"`
	Balance     float64        `json:"balance"`
	CptCode     sql.NullString `json:"cpt_code"`
	Description sql.NullString `json:"description"`
	Status      sql.NullString `json:"status"`
}

// Patient ledger: combined procedure charges + payments view (simplified)
func (q *Queries) PatientLedger(ctx context.Context, arg PatientLedgerParams) ([]PatientLedgerRow, error) {
	rows, err := q.db.QueryContext(ctx, patientLedger, arg.PatientID, arg.PatientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatientLedgerRow
	for rows.Next() {
		var i PatientLedgerRow
		if err := rows.Scan(
			&i.EntryType,
			&i.ID,
			&i.Date,
			&i.Amount,
			&i.Balance,
			&i.CptCode,
			&i.Description,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patientPayments = `-- name: PatientPayments :many
SELECT
  pr.id,
  pr.payrecdtadd AS date,
  pr.payrecamt AS amount,
  pr.payrectype AS type,
  pr.payrecdescrip AS description,
  pr.payrecproc AS procedure_id
FROM payrec pr
WHERE pr.payrecpatient = ?
  AND pr.active = 'active'
ORDER BY pr.payrecdtadd DESC
`

type PatientPaymentsRow struct {
	ID          int64        `json:"id"`
	Date        sql.NullTime `json:"date"`
	Amount      float64      `json:"amount"`
	Type        int64        `json:"type"`
	Description string       `json:"description"`
	ProcedureID int64        `json:"procedure_id"`
}

// Patient payments: list all payments for a patient
func (q *Queries) PatientPayments(ctx context.Context, patientID int64) ([]PatientPaymentsRow, error) {
	rows, err := q.db.QueryContext(ctx, patientPayments, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatientPaymentsRow
	for rows.Next() {
		var i PatientPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Amount,
			&i.Type,
			&i.Description,
			&i.ProcedureID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
