// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: phones.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createPhone = `-- name: CreatePhone :execresult
INSERT INTO phone (patient, type, number, active, user)
VALUES (
  ?,
  ?,
  ?,
  'active',
  ?
)
`

type CreatePhoneParams struct {
	PatientID int64  `json:"patient_id"`
	PhoneType string `json:"phone_type"`
	Number    string `json:"number"`
	UserID    int64  `json:"user_id"`
}

// Phone: insert a new phone for a patient
func (q *Queries) CreatePhone(ctx context.Context, arg CreatePhoneParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPhone,
		arg.PatientID,
		arg.PhoneType,
		arg.Number,
		arg.UserID,
	)
}

const listPhones = `-- name: ListPhones :many
SELECT
  id,
  patient,
  type,
  number,
  active,
  created_at,
  updated_at
FROM phone
WHERE patient = ? AND active = 'active'
ORDER BY id ASC
`

type ListPhonesRow struct {
	ID        int64     `json:"id"`
	Patient   int64     `json:"patient"`
	Type      string    `json:"type"`
	Number    string    `json:"number"`
	Active    string    `json:"active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Phone: list all active phones for a patient
func (q *Queries) ListPhones(ctx context.Context, patientID int64) ([]ListPhonesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPhones, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPhonesRow
	for rows.Next() {
		var i ListPhonesRow
		if err := rows.Scan(
			&i.ID,
			&i.Patient,
			&i.Type,
			&i.Number,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
