// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: photo_id.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createPhotoID = `-- name: CreatePhotoID :execresult
INSERT INTO photoid (
  patient, photo, photo_mime, page_count, description, user
) VALUES (
  ?, ?, ?,
  ?, ?, ?
)
`

type CreatePhotoIDParams struct {
	Patient     int64          `json:"patient"`
	Photo       sql.NullString `json:"photo"`
	PhotoMime   string         `json:"photo_mime"`
	PageCount   int64          `json:"page_count"`
	Description string         `json:"description"`
	User        int64          `json:"user"`
}

func (q *Queries) CreatePhotoID(ctx context.Context, arg CreatePhotoIDParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPhotoID,
		arg.Patient,
		arg.Photo,
		arg.PhotoMime,
		arg.PageCount,
		arg.Description,
		arg.User,
	)
}

const getPhotoID = `-- name: GetPhotoID :many
SELECT id, created_at, updated_at, deleted_at, patient, photo, photo_mime, page_count, description, user, active FROM photoid
WHERE patient = ?
  AND active = 'active'
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetPhotoID(ctx context.Context, patientID int64) ([]Photoid, error) {
	rows, err := q.db.QueryContext(ctx, getPhotoID, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Photoid
	for rows.Next() {
		var i Photoid
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Patient,
			&i.Photo,
			&i.PhotoMime,
			&i.PageCount,
			&i.Description,
			&i.User,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
