// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: portal.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createPortalAppointmentRequest = `-- name: CreatePortalAppointmentRequest :execresult
INSERT INTO scheduler (
  caldateof, calhour, calminute, calduration, caltype,
  calphysician, calpatient, calstatus, calprenote,
  calcreated, calappttemplate, user,
  created_at, updated_at
) VALUES (
  ?, ?, ?, 30, 'patient',
  ?, ?, 'requested', ?,
  NOW(), ?, ?,
  NOW(), NOW()
)
`

type CreatePortalAppointmentRequestParams struct {
	DateOf                time.Time     `json:"date_of"`
	Hour                  int64         `json:"hour"`
	Minute                int64         `json:"minute"`
	ProviderID            int64         `json:"provider_id"`
	PatientID             int64         `json:"patient_id"`
	Note                  string        `json:"note"`
	AppointmentTemplateID sql.NullInt64 `json:"appointment_template_id"`
	UserID                int64         `json:"user_id"`
}

// Portal: create an appointment request (status = 'requested')
func (q *Queries) CreatePortalAppointmentRequest(ctx context.Context, arg CreatePortalAppointmentRequestParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPortalAppointmentRequest,
		arg.DateOf,
		arg.Hour,
		arg.Minute,
		arg.ProviderID,
		arg.PatientID,
		arg.Note,
		arg.AppointmentTemplateID,
		arg.UserID,
	)
}

const getPortalPatientDemographics = `-- name: GetPortalPatientDemographics :one
SELECT
  id,
  ptfname AS first_name,
  ptlname AS last_name,
  ptmname AS middle_name,
  ptsuffix AS suffix,
  ptid AS patient_id_display,
  ptdob AS date_of_birth,
  ptsex AS gender,
  ptprimarylanguage AS language,
  pemail AS email,
  portal_enabled
FROM patient
WHERE id = ?
  AND ptarchive = 0
`

type GetPortalPatientDemographicsRow struct {
	ID               int64          `json:"id"`
	FirstName        string         `json:"first_name"`
	LastName         string         `json:"last_name"`
	MiddleName       sql.NullString `json:"middle_name"`
	Suffix           string         `json:"suffix"`
	PatientIDDisplay string         `json:"patient_id_display"`
	DateOfBirth      sql.NullTime   `json:"date_of_birth"`
	Gender           string         `json:"gender"`
	Language         string         `json:"language"`
	Email            sql.NullString `json:"email"`
	PortalEnabled    bool           `json:"portal_enabled"`
}

// Portal: patient demographics for the "me" endpoint
func (q *Queries) GetPortalPatientDemographics(ctx context.Context, patientID int64) (GetPortalPatientDemographicsRow, error) {
	row := q.db.QueryRowContext(ctx, getPortalPatientDemographics, patientID)
	var i GetPortalPatientDemographicsRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.Suffix,
		&i.PatientIDDisplay,
		&i.DateOfBirth,
		&i.Gender,
		&i.Language,
		&i.Email,
		&i.PortalEnabled,
	)
	return i, err
}

const listPortalAppointments = `-- name: ListPortalAppointments :many
SELECT
  s.id,
  s.caldateof AS date_of,
  DATE_FORMAT(s.caldateof, '%m/%d/%Y') AS date_of_mdy,
  s.calhour AS hour,
  s.calminute AS minute,
  CONCAT(LPAD(s.calhour, 2, '0'), ':', LPAD(s.calminute, 2, '0')) AS appointment_time,
  s.calduration AS duration,
  s.calphysician AS provider_id,
  CONCAT(ph.phylname, ', ', ph.phyfname) AS provider_name,
  s.caltype AS appointment_type,
  s.calstatus AS status,
  s.calprenote AS note,
  s.calappttemplate AS appointment_template_id,
  s.calfacility AS facility_id,
  s.calroom AS room_id,
  s.created_at,
  s.updated_at
FROM scheduler s
LEFT JOIN physician ph ON s.calphysician = ph.id
WHERE s.calpatient = ?
  AND s.caltype = 'patient'
ORDER BY s.caldateof DESC, s.calhour DESC, s.calminute DESC
`

type ListPortalAppointmentsRow struct {
	ID                    int64         `json:"id"`
	DateOf                time.Time     `json:"date_of"`
	DateOfMdy             string        `json:"date_of_mdy"`
	Hour                  int64         `json:"hour"`
	Minute                int64         `json:"minute"`
	AppointmentTime       string        `json:"appointment_time"`
	Duration              int64         `json:"duration"`
	ProviderID            int64         `json:"provider_id"`
	ProviderName          string        `json:"provider_name"`
	AppointmentType       string        `json:"appointment_type"`
	Status                string        `json:"status"`
	Note                  string        `json:"note"`
	AppointmentTemplateID int64         `json:"appointment_template_id"`
	FacilityID            sql.NullInt64 `json:"facility_id"`
	RoomID                sql.NullInt64 `json:"room_id"`
	CreatedAt             time.Time     `json:"created_at"`
	UpdatedAt             time.Time     `json:"updated_at"`
}

// Portal: list appointments for a patient from scheduler
func (q *Queries) ListPortalAppointments(ctx context.Context, patientID int64) ([]ListPortalAppointmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPortalAppointments, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPortalAppointmentsRow
	for rows.Next() {
		var i ListPortalAppointmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.DateOf,
			&i.DateOfMdy,
			&i.Hour,
			&i.Minute,
			&i.AppointmentTime,
			&i.Duration,
			&i.ProviderID,
			&i.ProviderName,
			&i.AppointmentType,
			&i.Status,
			&i.Note,
			&i.AppointmentTemplateID,
			&i.FacilityID,
			&i.RoomID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPortalProblems = `-- name: ListPortalProblems :many
SELECT
  'current' AS problem_type,
  cp.id,
  cp.patient,
  cp.date,
  cp.problem AS description,
  cp.active,
  cp.created_at,
  cp.updated_at
FROM current_problems cp
WHERE cp.patient = ?
  AND cp.active = 'active'
  AND cp.deleted_at IS NULL
UNION ALL
SELECT
  'chronic' AS problem_type,
  chp.id,
  chp.patient,
  chp.date,
  chp.problem AS description,
  NULL AS active,
  chp.created_at,
  chp.updated_at
FROM chronic_problems chp
WHERE chp.patient = ?
  AND chp.deleted_at IS NULL
ORDER BY date DESC
`

type ListPortalProblemsParams struct {
	PatientID int64 `json:"patient_id"`
}

type ListPortalProblemsRow struct {
	ProblemType string    `json:"problem_type"`
	ID          int64     `json:"id"`
	Patient     int64     `json:"patient"`
	Date        time.Time `json:"date"`
	Description string    `json:"description"`
	Active      string    `json:"active"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// Portal: list problems (union of current and chronic)
func (q *Queries) ListPortalProblems(ctx context.Context, arg ListPortalProblemsParams) ([]ListPortalProblemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPortalProblems, arg.PatientID, arg.PatientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPortalProblemsRow
	for rows.Next() {
		var i ListPortalProblemsRow
		if err := rows.Scan(
			&i.ProblemType,
			&i.ID,
			&i.Patient,
			&i.Date,
			&i.Description,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
