// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: portal_audit.sql

package dbgen

import (
	"context"
	"database/sql"
)

const insertPortalAuditLog = `-- name: InsertPortalAuditLog :execresult
INSERT INTO portal_audit_log (
  created_at, updated_at, patient_id,
  action, ip_address, user_agent, success
) VALUES (
  NOW(), NOW(), ?,
  ?, ?, ?,
  ?
)
`

type InsertPortalAuditLogParams struct {
	PatientID int64  `json:"patient_id"`
	Action    string `json:"action"`
	IpAddress string `json:"ip_address"`
	UserAgent string `json:"user_agent"`
	Success   bool   `json:"success"`
}

func (q *Queries) InsertPortalAuditLog(ctx context.Context, arg InsertPortalAuditLogParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertPortalAuditLog,
		arg.PatientID,
		arg.Action,
		arg.IpAddress,
		arg.UserAgent,
		arg.Success,
	)
}

const listPortalAuditByPatient = `-- name: ListPortalAuditByPatient :many
SELECT id, created_at, updated_at, deleted_at, patient_id, action, ip_address, user_agent, success FROM portal_audit_log
WHERE patient_id = ?
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListPortalAuditByPatient(ctx context.Context, patientID int64) ([]PortalAuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listPortalAuditByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PortalAuditLog
	for rows.Next() {
		var i PortalAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.PatientID,
			&i.Action,
			&i.IpAddress,
			&i.UserAgent,
			&i.Success,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
