// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: portal_messaging.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const portalCancelAppointment = `-- name: PortalCancelAppointment :exec
UPDATE scheduler
SET calstatus = 'cancelled',
    calprenote = CONCAT(COALESCE(calprenote, ''), ' [CANCELLED: ', ?, ']'),
    updated_at = NOW()
WHERE id = ?
  AND calpatient = ?
  AND calstatus != 'cancelled'
`

type PortalCancelAppointmentParams struct {
	CancelReason interface{} `json:"cancel_reason"`
	ID           int64       `json:"id"`
	PatientID    int64       `json:"patient_id"`
}

// Portal: cancel appointment (set status to cancelled + reason)
func (q *Queries) PortalCancelAppointment(ctx context.Context, arg PortalCancelAppointmentParams) error {
	_, err := q.db.ExecContext(ctx, portalCancelAppointment, arg.CancelReason, arg.ID, arg.PatientID)
	return err
}

const portalCreateMessage = `-- name: PortalCreateMessage :execresult
INSERT INTO messages (
  msgby, sender, msgtime, msgfor, msgrecip, msgpatient, msgperson,
  msgurgency, msgsubject, msgtext, msgread, msgunique, msgtag, active,
  created_at, updated_at
) VALUES (
  0, ?, NOW(), ?, 'Practice',
  ?, ?,
  ?, ?, ?,
  0, '', '', 'active',
  NOW(), NOW()
)
`

type PortalCreateMessageParams struct {
	Sender      string `json:"sender"`
	MsgFor      int64  `json:"msg_for"`
	PatientID   int64  `json:"patient_id"`
	PatientName string `json:"patient_name"`
	Urgency     int64  `json:"urgency"`
	Subject     string `json:"subject"`
	Body        string `json:"body"`
}

// Portal: send a message from patient to practice
func (q *Queries) PortalCreateMessage(ctx context.Context, arg PortalCreateMessageParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, portalCreateMessage,
		arg.Sender,
		arg.MsgFor,
		arg.PatientID,
		arg.PatientName,
		arg.Urgency,
		arg.Subject,
		arg.Body,
	)
}

const portalListMessages = `-- name: PortalListMessages :many
SELECT
  m.id,
  m.msgtime AS message_time,
  m.msgsubject AS subject,
  m.msgtext AS body,
  m.msgby AS sent_by_user_id,
  m.sender,
  m.msgread AS is_read,
  m.msgurgency AS urgency,
  m.msgtag AS tag,
  m.created_at,
  m.updated_at
FROM messages m
WHERE m.msgpatient = ?
  AND (m.msgtag IS NULL OR LENGTH(m.msgtag) < 1)
ORDER BY m.msgtime DESC
`

type PortalListMessagesRow struct {
	ID           int64          `json:"id"`
	MessageTime  time.Time      `json:"message_time"`
	Subject      string         `json:"subject"`
	Body         string         `json:"body"`
	SentByUserID int64          `json:"sent_by_user_id"`
	Sender       string         `json:"sender"`
	IsRead       int64          `json:"is_read"`
	Urgency      int64          `json:"urgency"`
	Tag          sql.NullString `json:"tag"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

// Portal: list messages for a patient (no user_id filter needed for portal)
func (q *Queries) PortalListMessages(ctx context.Context, patientID int64) ([]PortalListMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, portalListMessages, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PortalListMessagesRow
	for rows.Next() {
		var i PortalListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageTime,
			&i.Subject,
			&i.Body,
			&i.SentByUserID,
			&i.Sender,
			&i.IsRead,
			&i.Urgency,
			&i.Tag,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const portalListSuperbills = `-- name: PortalListSuperbills :many
SELECT
  s.id,
  s.created_at,
  s.date_from,
  s.date_to,
  s.provider,
  s.status,
  s.total_charges,
  s.date_created
FROM superbill s
WHERE s.patient = ?
ORDER BY s.created_at DESC
LIMIT 12
`

type PortalListSuperbillsRow struct {
	ID           int64     `json:"id"`
	CreatedAt    time.Time `json:"created_at"`
	DateFrom     time.Time `json:"date_from"`
	DateTo       time.Time `json:"date_to"`
	Provider     int64     `json:"provider"`
	Status       string    `json:"status"`
	TotalCharges float64   `json:"total_charges"`
	DateCreated  time.Time `json:"date_created"`
}

// Portal: list superbills/statements for a patient
func (q *Queries) PortalListSuperbills(ctx context.Context, patientID int64) ([]PortalListSuperbillsRow, error) {
	rows, err := q.db.QueryContext(ctx, portalListSuperbills, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PortalListSuperbillsRow
	for rows.Next() {
		var i PortalListSuperbillsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.DateFrom,
			&i.DateTo,
			&i.Provider,
			&i.Status,
			&i.TotalCharges,
			&i.DateCreated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const portalOutstandingCharges = `-- name: PortalOutstandingCharges :many
SELECT
  p.id,
  p.procdt AS date,
  p.proccharges AS total_charge,
  p.procbalcurrent AS balance,
  cpt.abbrev AS cpt_code,
  p.proccomment AS description,
  p.procstatus AS status
FROM procrec p
LEFT OUTER JOIN cpt cpt ON cpt.id = p.proccpt
WHERE p.procpatient = ?
  AND p.procbalcurrent > 0
ORDER BY p.procdt DESC
`

type PortalOutstandingChargesRow struct {
	ID          int64          `json:"id"`
	Date        time.Time      `json:"date"`
	TotalCharge float64        `json:"total_charge"`
	Balance     float64        `json:"balance"`
	CptCode     sql.NullString `json:"cpt_code"`
	Description sql.NullString `json:"description"`
	Status      sql.NullString `json:"status"`
}

// Portal: list outstanding charges for a patient
func (q *Queries) PortalOutstandingCharges(ctx context.Context, patientID int64) ([]PortalOutstandingChargesRow, error) {
	rows, err := q.db.QueryContext(ctx, portalOutstandingCharges, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PortalOutstandingChargesRow
	for rows.Next() {
		var i PortalOutstandingChargesRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.TotalCharge,
			&i.Balance,
			&i.CptCode,
			&i.Description,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const portalUnappliedCredits = `-- name: PortalUnappliedCredits :many
SELECT
  pr.id,
  pr.payrecdtadd AS date,
  pr.payrecamt AS amount,
  pr.payrectype AS payment_type,
  pr.payrecdescrip AS description,
  pr.payrecproc AS procedure_id
FROM payrec pr
WHERE pr.payrecpatient = ?
  AND pr.active = 'active'
  AND pr.payrecproc = 0
ORDER BY pr.payrecdtadd DESC
`

type PortalUnappliedCreditsRow struct {
	ID          int64        `json:"id"`
	Date        sql.NullTime `json:"date"`
	Amount      float64      `json:"amount"`
	PaymentType int64        `json:"payment_type"`
	Description string       `json:"description"`
	ProcedureID int64        `json:"procedure_id"`
}

// Portal: list unapplied credits for a patient
func (q *Queries) PortalUnappliedCredits(ctx context.Context, patientID int64) ([]PortalUnappliedCreditsRow, error) {
	rows, err := q.db.QueryContext(ctx, portalUnappliedCredits, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PortalUnappliedCreditsRow
	for rows.Next() {
		var i PortalUnappliedCreditsRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Amount,
			&i.PaymentType,
			&i.Description,
			&i.ProcedureID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
