// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prescriptions.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createPrescription = `-- name: CreatePrescription :execresult
INSERT INTO prescriptions (
  patient, drug_name, dosage, frequency, quantity, refills,
  date_written, prescribing_provider, pharmacy, status, notes, user
) VALUES (
  ?, ?, ?,
  ?, ?, ?,
  ?, ?,
  ?, ?, ?,
  ?
)
`

type CreatePrescriptionParams struct {
	Patient             int64          `json:"patient"`
	DrugName            string         `json:"drug_name"`
	Dosage              string         `json:"dosage"`
	Frequency           string         `json:"frequency"`
	Quantity            string         `json:"quantity"`
	Refills             int64          `json:"refills"`
	DateWritten         time.Time      `json:"date_written"`
	PrescribingProvider int64          `json:"prescribing_provider"`
	Pharmacy            string         `json:"pharmacy"`
	Status              string         `json:"status"`
	Notes               sql.NullString `json:"notes"`
	User                int64          `json:"user"`
}

// Create a new prescription
func (q *Queries) CreatePrescription(ctx context.Context, arg CreatePrescriptionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPrescription,
		arg.Patient,
		arg.DrugName,
		arg.Dosage,
		arg.Frequency,
		arg.Quantity,
		arg.Refills,
		arg.DateWritten,
		arg.PrescribingProvider,
		arg.Pharmacy,
		arg.Status,
		arg.Notes,
		arg.User,
	)
}

const discontinuePrescription = `-- name: DiscontinuePrescription :exec
UPDATE prescriptions
SET status = 'discontinued', updated_at = NOW()
WHERE id = ?
  AND deleted_at IS NULL
`

// Discontinue a prescription (set status to 'discontinued')
func (q *Queries) DiscontinuePrescription(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, discontinuePrescription, id)
	return err
}

const listPrescriptions = `-- name: ListPrescriptions :many
SELECT id, created_at, updated_at, deleted_at, patient, drug_name, dosage, frequency, quantity, refills, date_written, prescribing_provider, pharmacy, status, notes, user FROM prescriptions
WHERE patient = ?
  AND status = 'active'
  AND deleted_at IS NULL
ORDER BY date_written DESC
`

// List active prescriptions for a patient, ordered by date
func (q *Queries) ListPrescriptions(ctx context.Context, patientID int64) ([]Prescription, error) {
	rows, err := q.db.QueryContext(ctx, listPrescriptions, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Prescription
	for rows.Next() {
		var i Prescription
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Patient,
			&i.DrugName,
			&i.Dosage,
			&i.Frequency,
			&i.Quantity,
			&i.Refills,
			&i.DateWritten,
			&i.PrescribingProvider,
			&i.Pharmacy,
			&i.Status,
			&i.Notes,
			&i.User,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrescriptionsWithPharmacy = `-- name: ListPrescriptionsWithPharmacy :many
SELECT
  p.id,
  p.created_at,
  p.updated_at,
  p.deleted_at,
  p.patient,
  p.drug_name,
  p.dosage,
  p.frequency,
  p.quantity,
  p.refills,
  p.date_written,
  p.prescribing_provider,
  p.status,
  p.notes,
  p.user,
  ph.id AS pharmacy_id,
  ph.phname AS pharmacy_name,
  ph.phcity AS pharmacy_city,
  ph.phstate AS pharmacy_state,
  (SELECT COUNT(*) FROM rxrefillrequest r
   WHERE r.patient = p.patient
     AND r.rxorig LIKE CONCAT('%', p.id, '%')
     AND r.deleted_at IS NULL) AS refills_used,
  (SELECT MAX(r.approved) FROM rxrefillrequest r
   WHERE r.patient = p.patient
     AND r.rxorig LIKE CONCAT('%', p.id, '%')
     AND r.approved IS NOT NULL
     AND r.deleted_at IS NULL) AS last_fill_date
FROM prescriptions p
LEFT JOIN pharmacy ph ON ph.phname = p.pharmacy AND ph.deleted_at IS NULL
WHERE p.patient = ?
  AND p.status = 'active'
  AND p.deleted_at IS NULL
ORDER BY p.date_written DESC
`

type ListPrescriptionsWithPharmacyRow struct {
	ID                  int64          `json:"id"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
	DeletedAt           sql.NullTime   `json:"deleted_at"`
	Patient             int64          `json:"patient"`
	DrugName            string         `json:"drug_name"`
	Dosage              string         `json:"dosage"`
	Frequency           string         `json:"frequency"`
	Quantity            string         `json:"quantity"`
	Refills             int64          `json:"refills"`
	DateWritten         time.Time      `json:"date_written"`
	PrescribingProvider int64          `json:"prescribing_provider"`
	Status              string         `json:"status"`
	Notes               sql.NullString `json:"notes"`
	User                int64          `json:"user"`
	PharmacyID          sql.NullInt64  `json:"pharmacy_id"`
	PharmacyName        sql.NullString `json:"pharmacy_name"`
	PharmacyCity        sql.NullString `json:"pharmacy_city"`
	PharmacyState       sql.NullString `json:"pharmacy_state"`
	RefillsUsed         int64          `json:"refills_used"`
	LastFillDate        interface{}    `json:"last_fill_date"`
}

// List prescriptions for a patient with pharmacy details and refill info
func (q *Queries) ListPrescriptionsWithPharmacy(ctx context.Context, patientID int64) ([]ListPrescriptionsWithPharmacyRow, error) {
	rows, err := q.db.QueryContext(ctx, listPrescriptionsWithPharmacy, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPrescriptionsWithPharmacyRow
	for rows.Next() {
		var i ListPrescriptionsWithPharmacyRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Patient,
			&i.DrugName,
			&i.Dosage,
			&i.Frequency,
			&i.Quantity,
			&i.Refills,
			&i.DateWritten,
			&i.PrescribingProvider,
			&i.Status,
			&i.Notes,
			&i.User,
			&i.PharmacyID,
			&i.PharmacyName,
			&i.PharmacyCity,
			&i.PharmacyState,
			&i.RefillsUsed,
			&i.LastFillDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
