// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prescriptions.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createPrescription = `-- name: CreatePrescription :execresult
INSERT INTO prescriptions (
  patient, drug_name, dosage, frequency, quantity, refills,
  date_written, prescribing_provider, pharmacy, status, notes, user
) VALUES (
  ?, ?, ?,
  ?, ?, ?,
  ?, ?,
  ?, ?, ?,
  ?
)
`

type CreatePrescriptionParams struct {
	Patient             int64          `json:"patient"`
	DrugName            string         `json:"drug_name"`
	Dosage              string         `json:"dosage"`
	Frequency           string         `json:"frequency"`
	Quantity            string         `json:"quantity"`
	Refills             int64          `json:"refills"`
	DateWritten         time.Time      `json:"date_written"`
	PrescribingProvider int64          `json:"prescribing_provider"`
	Pharmacy            string         `json:"pharmacy"`
	Status              string         `json:"status"`
	Notes               sql.NullString `json:"notes"`
	User                int64          `json:"user"`
}

// Create a new prescription
func (q *Queries) CreatePrescription(ctx context.Context, arg CreatePrescriptionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPrescription,
		arg.Patient,
		arg.DrugName,
		arg.Dosage,
		arg.Frequency,
		arg.Quantity,
		arg.Refills,
		arg.DateWritten,
		arg.PrescribingProvider,
		arg.Pharmacy,
		arg.Status,
		arg.Notes,
		arg.User,
	)
}

const discontinuePrescription = `-- name: DiscontinuePrescription :exec
UPDATE prescriptions
SET status = 'discontinued', updated_at = NOW()
WHERE id = ?
  AND deleted_at IS NULL
`

// Discontinue a prescription (set status to 'discontinued')
func (q *Queries) DiscontinuePrescription(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, discontinuePrescription, id)
	return err
}

const listPrescriptions = `-- name: ListPrescriptions :many
SELECT id, created_at, updated_at, deleted_at, patient, drug_name, dosage, frequency, quantity, refills, date_written, prescribing_provider, pharmacy, status, notes, user FROM prescriptions
WHERE patient = ?
  AND status = 'active'
  AND deleted_at IS NULL
ORDER BY date_written DESC
`

// List active prescriptions for a patient, ordered by date
func (q *Queries) ListPrescriptions(ctx context.Context, patientID int64) ([]Prescription, error) {
	rows, err := q.db.QueryContext(ctx, listPrescriptions, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Prescription
	for rows.Next() {
		var i Prescription
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Patient,
			&i.DrugName,
			&i.Dosage,
			&i.Frequency,
			&i.Quantity,
			&i.Refills,
			&i.DateWritten,
			&i.PrescribingProvider,
			&i.Pharmacy,
			&i.Status,
			&i.Notes,
			&i.User,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
