// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: previous_operations.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createPreviousOperation = `-- name: CreatePreviousOperation :execresult
INSERT INTO previous_operations (
  created_at, updated_at, patient, operation_date, operation, user
) VALUES (
  NOW(), NOW(), ?, ?,
  ?, ?
)
`

type CreatePreviousOperationParams struct {
	PatientID     int64        `json:"patient_id"`
	OperationDate sql.NullTime `json:"operation_date"`
	Operation     string       `json:"operation"`
	UserID        int64        `json:"user_id"`
}

func (q *Queries) CreatePreviousOperation(ctx context.Context, arg CreatePreviousOperationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPreviousOperation,
		arg.PatientID,
		arg.OperationDate,
		arg.Operation,
		arg.UserID,
	)
}

const listPreviousOperationsByPatient = `-- name: ListPreviousOperationsByPatient :many
SELECT id, created_at, updated_at, deleted_at, patient, operation_date, operation, user FROM previous_operations
WHERE patient = ?
  AND deleted_at IS NULL
ORDER BY operation_date DESC
`

func (q *Queries) ListPreviousOperationsByPatient(ctx context.Context, patientID int64) ([]PreviousOperation, error) {
	rows, err := q.db.QueryContext(ctx, listPreviousOperationsByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PreviousOperation
	for rows.Next() {
		var i PreviousOperation
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Patient,
			&i.OperationDate,
			&i.Operation,
			&i.User,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
