// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: procedures.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const getProcedure = `-- name: GetProcedure :one
SELECT
  pr.id,
  pr.created_at,
  pr.updated_at,
  pr.procpatient AS patient_id,
  pr.proceoc AS episode_of_care,
  pr.proccpt AS cpt_id,
  c.cptnameext AS cpt_name,
  c.abbrev AS cpt_code,
  pr.proccptmod AS cpt_modifier_1,
  pr.proccptmod2 AS cpt_modifier_2,
  pr.proccptmod3 AS cpt_modifier_3,
  pr.procdiag1 AS diagnosis_1_id,
  pr.procdiag2 AS diagnosis_2_id,
  pr.procdiag3 AS diagnosis_3_id,
  pr.procdiag4 AS diagnosis_4_id,
  pr.procdiagset AS diagnosis_set,
  pr.proccharges AS charge,
  pr.procunits AS units,
  pr.procvoucher AS voucher,
  pr.procphysician AS provider_id,
  CONCAT(ph.phylname, ', ', ph.phyfname) AS provider_name,
  pr.procdt AS date_of_service,
  pr.procdtend AS date_of_service_end,
  pr.procpos AS place_of_service,
  pr.proccomment AS comment,
  pr.procbalorig AS balance_original,
  pr.procbalcurrent AS balance_current,
  pr.procamtpain AS amount_paid,
  pr.procbilled AS billed,
  pr.procbillable AS billable,
  pr.procauth AS authorization_id,
  pr.procrefdoc AS referring_provider_id,
  pr.procrefdt AS referral_date,
  pr.procamtallowed AS amount_allowed,
  pr.procdtbilled AS billed_date,
  pr.proccurcovid AS current_coverage_id,
  pr.proccurcovtp AS current_coverage_type_id,
  pr.proccov1 AS coverage_id_1,
  pr.proccov2 AS coverage_id_2,
  pr.proccov3 AS coverage_id_3,
  pr.proccov4 AS coverage_id_4,
  pr.procmedicaidref AS medicaid_reference,
  pr.procmedicaidresub AS medicaid_resubmission,
  pr.proclabcharges AS lab_charges,
  pr.procstatus AS status,
  pr.procslidingscale AS sliding_scale,
  pr.proctosoverride AS type_of_service_override,
  pr.orderid AS order_id,
  pr.user AS user_id,
  pr.active
FROM procrec pr
LEFT JOIN cpt c ON c.id = pr.proccpt
LEFT JOIN physician ph ON ph.id = pr.procphysician
WHERE pr.id = ?
`

type GetProcedureRow struct {
	ID                    int64          `json:"id"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
	PatientID             int64          `json:"patient_id"`
	EpisodeOfCare         sql.NullString `json:"episode_of_care"`
	CptID                 int64          `json:"cpt_id"`
	CptName               sql.NullString `json:"cpt_name"`
	CptCode               sql.NullString `json:"cpt_code"`
	CptModifier1          int64          `json:"cpt_modifier_1"`
	CptModifier2          int64          `json:"cpt_modifier_2"`
	CptModifier3          int64          `json:"cpt_modifier_3"`
	Diagnosis1ID          int64          `json:"diagnosis_1_id"`
	Diagnosis2ID          int64          `json:"diagnosis_2_id"`
	Diagnosis3ID          int64          `json:"diagnosis_3_id"`
	Diagnosis4ID          int64          `json:"diagnosis_4_id"`
	DiagnosisSet          string         `json:"diagnosis_set"`
	Charge                float64        `json:"charge"`
	Units                 float64        `json:"units"`
	Voucher               sql.NullString `json:"voucher"`
	ProviderID            int64          `json:"provider_id"`
	ProviderName          string         `json:"provider_name"`
	DateOfService         time.Time      `json:"date_of_service"`
	DateOfServiceEnd      sql.NullTime   `json:"date_of_service_end"`
	PlaceOfService        int64          `json:"place_of_service"`
	Comment               sql.NullString `json:"comment"`
	BalanceOriginal       float64        `json:"balance_original"`
	BalanceCurrent        float64        `json:"balance_current"`
	AmountPaid            float64        `json:"amount_paid"`
	Billed                int64          `json:"billed"`
	Billable              int64          `json:"billable"`
	AuthorizationID       int64          `json:"authorization_id"`
	ReferringProviderID   int64          `json:"referring_provider_id"`
	ReferralDate          sql.NullTime   `json:"referral_date"`
	AmountAllowed         sql.NullString `json:"amount_allowed"`
	BilledDate            sql.NullTime   `json:"billed_date"`
	CurrentCoverageID     int64          `json:"current_coverage_id"`
	CurrentCoverageTypeID int64          `json:"current_coverage_type_id"`
	CoverageID1           int64          `json:"coverage_id_1"`
	CoverageID2           int64          `json:"coverage_id_2"`
	CoverageID3           int64          `json:"coverage_id_3"`
	CoverageID4           int64          `json:"coverage_id_4"`
	MedicaidReference     sql.NullString `json:"medicaid_reference"`
	MedicaidResubmission  sql.NullString `json:"medicaid_resubmission"`
	LabCharges            float64        `json:"lab_charges"`
	Status                sql.NullString `json:"status"`
	SlidingScale          sql.NullString `json:"sliding_scale"`
	TypeOfServiceOverride int64          `json:"type_of_service_override"`
	OrderID               int64          `json:"order_id"`
	UserID                int64          `json:"user_id"`
	Active                string         `json:"active"`
}

// Get single procedure detail with joins
func (q *Queries) GetProcedure(ctx context.Context, id int64) (GetProcedureRow, error) {
	row := q.db.QueryRowContext(ctx, getProcedure, id)
	var i GetProcedureRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PatientID,
		&i.EpisodeOfCare,
		&i.CptID,
		&i.CptName,
		&i.CptCode,
		&i.CptModifier1,
		&i.CptModifier2,
		&i.CptModifier3,
		&i.Diagnosis1ID,
		&i.Diagnosis2ID,
		&i.Diagnosis3ID,
		&i.Diagnosis4ID,
		&i.DiagnosisSet,
		&i.Charge,
		&i.Units,
		&i.Voucher,
		&i.ProviderID,
		&i.ProviderName,
		&i.DateOfService,
		&i.DateOfServiceEnd,
		&i.PlaceOfService,
		&i.Comment,
		&i.BalanceOriginal,
		&i.BalanceCurrent,
		&i.AmountPaid,
		&i.Billed,
		&i.Billable,
		&i.AuthorizationID,
		&i.ReferringProviderID,
		&i.ReferralDate,
		&i.AmountAllowed,
		&i.BilledDate,
		&i.CurrentCoverageID,
		&i.CurrentCoverageTypeID,
		&i.CoverageID1,
		&i.CoverageID2,
		&i.CoverageID3,
		&i.CoverageID4,
		&i.MedicaidReference,
		&i.MedicaidResubmission,
		&i.LabCharges,
		&i.Status,
		&i.SlidingScale,
		&i.TypeOfServiceOverride,
		&i.OrderID,
		&i.UserID,
		&i.Active,
	)
	return i, err
}

const patientProcedures = `-- name: PatientProcedures :many
SELECT
  pr.id,
  pr.procdt AS date_of_service,
  pr.proccpt AS cpt_id,
  c.cptnameext AS cpt_name,
  pr.proccharges AS charge,
  pr.procbalcurrent AS balance,
  pr.procamtpain AS amount_paid,
  pr.procstatus AS status,
  pr.procdiag1 AS diagnosis_id,
  pr.procpos AS place_of_service,
  pr.procphysician AS provider_id,
  pr.procunits AS units,
  pr.procdiagset AS diagnosis_set,
  pr.procbalorig AS balance_original,
  pr.procdtend AS date_of_service_end,
  pr.proccptmod AS cpt_modifier_1,
  pr.proccptmod2 AS cpt_modifier_2,
  pr.proccptmod3 AS cpt_modifier_3
FROM procrec pr
LEFT JOIN cpt c ON c.id = pr.proccpt
WHERE pr.procpatient = ?
  AND pr.active = 'active'
ORDER BY pr.procdt DESC
`

type PatientProceduresRow struct {
	ID               int64          `json:"id"`
	DateOfService    time.Time      `json:"date_of_service"`
	CptID            int64          `json:"cpt_id"`
	CptName          sql.NullString `json:"cpt_name"`
	Charge           float64        `json:"charge"`
	Balance          float64        `json:"balance"`
	AmountPaid       float64        `json:"amount_paid"`
	Status           sql.NullString `json:"status"`
	DiagnosisID      int64          `json:"diagnosis_id"`
	PlaceOfService   int64          `json:"place_of_service"`
	ProviderID       int64          `json:"provider_id"`
	Units            float64        `json:"units"`
	DiagnosisSet     string         `json:"diagnosis_set"`
	BalanceOriginal  float64        `json:"balance_original"`
	DateOfServiceEnd sql.NullTime   `json:"date_of_service_end"`
	CptModifier1     int64          `json:"cpt_modifier_1"`
	CptModifier2     int64          `json:"cpt_modifier_2"`
	CptModifier3     int64          `json:"cpt_modifier_3"`
}

// List procedures for a patient with CPT code name
func (q *Queries) PatientProcedures(ctx context.Context, patientID int64) ([]PatientProceduresRow, error) {
	rows, err := q.db.QueryContext(ctx, patientProcedures, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatientProceduresRow
	for rows.Next() {
		var i PatientProceduresRow
		if err := rows.Scan(
			&i.ID,
			&i.DateOfService,
			&i.CptID,
			&i.CptName,
			&i.Charge,
			&i.Balance,
			&i.AmountPaid,
			&i.Status,
			&i.DiagnosisID,
			&i.PlaceOfService,
			&i.ProviderID,
			&i.Units,
			&i.DiagnosisSet,
			&i.BalanceOriginal,
			&i.DateOfServiceEnd,
			&i.CptModifier1,
			&i.CptModifier2,
			&i.CptModifier3,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
