// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: record_lock.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const acquireRecordLock = `-- name: AcquireRecordLock :execresult
INSERT INTO record_lock (
  created_at, updated_at, table_name, record_id, user_id, locked_at, expires_at
) VALUES (
  NOW(), NOW(), ?, ?,
  ?, NOW(), DATE_ADD(NOW(), INTERVAL 5 MINUTE)
)
`

type AcquireRecordLockParams struct {
	TableName string `json:"table_name"`
	RecordID  int64  `json:"record_id"`
	UserID    int64  `json:"user_id"`
}

func (q *Queries) AcquireRecordLock(ctx context.Context, arg AcquireRecordLockParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, acquireRecordLock, arg.TableName, arg.RecordID, arg.UserID)
}

const checkRecordLock = `-- name: CheckRecordLock :one
SELECT id, table_name, record_id, user_id, locked_at, expires_at
FROM record_lock
WHERE table_name = ?
  AND record_id = ?
  AND expires_at > NOW()
  AND deleted_at IS NULL
LIMIT 1
`

type CheckRecordLockParams struct {
	TableName string `json:"table_name"`
	RecordID  int64  `json:"record_id"`
}

type CheckRecordLockRow struct {
	ID        int64     `json:"id"`
	TableName string    `json:"table_name"`
	RecordID  int64     `json:"record_id"`
	UserID    int64     `json:"user_id"`
	LockedAt  time.Time `json:"locked_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CheckRecordLock(ctx context.Context, arg CheckRecordLockParams) (CheckRecordLockRow, error) {
	row := q.db.QueryRowContext(ctx, checkRecordLock, arg.TableName, arg.RecordID)
	var i CheckRecordLockRow
	err := row.Scan(
		&i.ID,
		&i.TableName,
		&i.RecordID,
		&i.UserID,
		&i.LockedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const expireRecordLocks = `-- name: ExpireRecordLocks :exec
UPDATE record_lock
SET deleted_at = NOW(), updated_at = NOW()
WHERE expires_at <= NOW()
  AND deleted_at IS NULL
`

func (q *Queries) ExpireRecordLocks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, expireRecordLocks)
	return err
}

const releaseRecordLock = `-- name: ReleaseRecordLock :exec
DELETE FROM record_lock
WHERE table_name = ?
  AND record_id = ?
  AND user_id = ?
`

type ReleaseRecordLockParams struct {
	TableName string `json:"table_name"`
	RecordID  int64  `json:"record_id"`
	UserID    int64  `json:"user_id"`
}

func (q *Queries) ReleaseRecordLock(ctx context.Context, arg ReleaseRecordLockParams) error {
	_, err := q.db.ExecContext(ctx, releaseRecordLock, arg.TableName, arg.RecordID, arg.UserID)
	return err
}
