// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: referrals.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createReferral = `-- name: CreateReferral :execresult
INSERT INTO referrals (
  patient, referring_provider, referral_to, referral_type,
  reason, status, date_referred, date_completed, notes, user,
  active, created_at, updated_at
) VALUES (
  ?, ?, ?,
  ?, ?, ?,
  ?, ?, ?,
  ?, 'active', NOW(), NOW()
)
`

type CreateReferralParams struct {
	PatientID         int64        `json:"patient_id"`
	ReferringProvider int64        `json:"referring_provider"`
	ReferralTo        int64        `json:"referral_to"`
	ReferralType      string       `json:"referral_type"`
	Reason            string       `json:"reason"`
	Status            string       `json:"status"`
	DateReferred      time.Time    `json:"date_referred"`
	DateCompleted     sql.NullTime `json:"date_completed"`
	Notes             string       `json:"notes"`
	UserID            int64        `json:"user_id"`
}

// Create a new referral entry
func (q *Queries) CreateReferral(ctx context.Context, arg CreateReferralParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createReferral,
		arg.PatientID,
		arg.ReferringProvider,
		arg.ReferralTo,
		arg.ReferralType,
		arg.Reason,
		arg.Status,
		arg.DateReferred,
		arg.DateCompleted,
		arg.Notes,
		arg.UserID,
	)
}

const listReferrals = `-- name: ListReferrals :many
SELECT id, created_at, updated_at, deleted_at, patient, referring_provider, referral_to, referral_type, reason, status, date_referred, date_completed, notes, user, active FROM referrals
WHERE patient = ?
  AND active = 'active'
ORDER BY date_referred DESC
`

// List active referrals for a patient, ordered by referral date descending
func (q *Queries) ListReferrals(ctx context.Context, patientID int64) ([]Referral, error) {
	rows, err := q.db.QueryContext(ctx, listReferrals, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Referral
	for rows.Next() {
		var i Referral
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Patient,
			&i.ReferringProvider,
			&i.ReferralTo,
			&i.ReferralType,
			&i.Reason,
			&i.Status,
			&i.DateReferred,
			&i.DateCompleted,
			&i.Notes,
			&i.User,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
