// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: remitt.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const getClaimInfo = `-- name: GetClaimInfo :many
SELECT id, created_at, updated_at, deleted_at, billkeydate, billkey, bkprocs FROM billkey ORDER BY billkeydate DESC
`

// Claim info: all billkey entries ordered by date
func (q *Queries) GetClaimInfo(ctx context.Context) ([]Billkey, error) {
	rows, err := q.db.QueryContext(ctx, getClaimInfo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Billkey
	for rows.Next() {
		var i Billkey
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Billkeydate,
			&i.Billkey,
			&i.Bkprocs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRebillList = `-- name: GetRebillList :many
SELECT id, created_at, updated_at, deleted_at, billkeydate, billkey, bkprocs FROM billkey ORDER BY billkeydate DESC
`

// Rebill list: all billkey entries (candidates for rebilling)
func (q *Queries) GetRebillList(ctx context.Context) ([]Billkey, error) {
	rows, err := q.db.QueryContext(ctx, getRebillList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Billkey
	for rows.Next() {
		var i Billkey
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Billkeydate,
			&i.Billkey,
			&i.Bkprocs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAsBilled = `-- name: MarkAsBilled :exec
UPDATE billkey SET updated_at = NOW() WHERE id = ?
`

// Mark a billkey entry as processed (update timestamp)
func (q *Queries) MarkAsBilled(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markAsBilled, id)
	return err
}

const patientsToBill = `-- name: PatientsToBill :many
SELECT DISTINCT p.id, p.ptlname, p.ptfname
FROM procrec pr
JOIN patient p ON pr.procpatient = p.id
WHERE pr.procstatus = 'unbilled'
  AND pr.active = 'active'
`

type PatientsToBillRow struct {
	ID      int64  `json:"id"`
	Ptlname string `json:"ptlname"`
	Ptfname string `json:"ptfname"`
}

// Patients with unbilled procedures
func (q *Queries) PatientsToBill(ctx context.Context) ([]PatientsToBillRow, error) {
	rows, err := q.db.QueryContext(ctx, patientsToBill)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatientsToBillRow
	for rows.Next() {
		var i PatientsToBillRow
		if err := rows.Scan(&i.ID, &i.Ptlname, &i.Ptfname); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const proceduresToBill = `-- name: ProceduresToBill :many
SELECT pr.id, pr.created_at, pr.updated_at, pr.deleted_at, pr.procpatient, pr.proceoc, pr.proccpt, pr.proccptmod, pr.proccptmod2, pr.proccptmod3, pr.procdiag1, pr.procdiag2, pr.procdiag3, pr.procdiag4, pr.procdiagset, pr.proccharges, pr.procunits, pr.procvoucher, pr.procphysician, pr.procdt, pr.procdtend, pr.procpos, pr.proccomment, pr.procbalorig, pr.procbalcurrent, pr.procamtpain, pr.procbilled, pr.procbillable, pr.procauth, pr.procrefdoc, pr.procrefdt, pr.procamtallowed, pr.procdtbilled, pr.proccurcovid, pr.proccurcovtp, pr.proccov1, pr.proccov2, pr.proccov3, pr.proccov4, pr.procmedicaidref, pr.procmedicaidresub, pr.proclabcharges, pr.procstatus, pr.procslidingscale, pr.proctosoverride, pr.orderid, pr.user, pr.active, c.cptnameext
FROM procrec pr
LEFT JOIN cpt c ON pr.proccpt = c.id
WHERE pr.procstatus = 'unbilled'
  AND pr.procpatient = ?
  AND pr.active = 'active'
`

type ProceduresToBillRow struct {
	ID                int64          `json:"id"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	DeletedAt         sql.NullTime   `json:"deleted_at"`
	Procpatient       int64          `json:"procpatient"`
	Proceoc           sql.NullString `json:"proceoc"`
	Proccpt           int64          `json:"proccpt"`
	Proccptmod        int64          `json:"proccptmod"`
	Proccptmod2       int64          `json:"proccptmod2"`
	Proccptmod3       int64          `json:"proccptmod3"`
	Procdiag1         int64          `json:"procdiag1"`
	Procdiag2         int64          `json:"procdiag2"`
	Procdiag3         int64          `json:"procdiag3"`
	Procdiag4         int64          `json:"procdiag4"`
	Procdiagset       string         `json:"procdiagset"`
	Proccharges       float64        `json:"proccharges"`
	Procunits         float64        `json:"procunits"`
	Procvoucher       sql.NullString `json:"procvoucher"`
	Procphysician     int64          `json:"procphysician"`
	Procdt            time.Time      `json:"procdt"`
	Procdtend         sql.NullTime   `json:"procdtend"`
	Procpos           int64          `json:"procpos"`
	Proccomment       sql.NullString `json:"proccomment"`
	Procbalorig       float64        `json:"procbalorig"`
	Procbalcurrent    float64        `json:"procbalcurrent"`
	Procamtpain       float64        `json:"procamtpain"`
	Procbilled        int64          `json:"procbilled"`
	Procbillable      int64          `json:"procbillable"`
	Procauth          int64          `json:"procauth"`
	Procrefdoc        int64          `json:"procrefdoc"`
	Procrefdt         sql.NullTime   `json:"procrefdt"`
	Procamtallowed    sql.NullString `json:"procamtallowed"`
	Procdtbilled      sql.NullTime   `json:"procdtbilled"`
	Proccurcovid      int64          `json:"proccurcovid"`
	Proccurcovtp      int64          `json:"proccurcovtp"`
	Proccov1          int64          `json:"proccov1"`
	Proccov2          int64          `json:"proccov2"`
	Proccov3          int64          `json:"proccov3"`
	Proccov4          int64          `json:"proccov4"`
	Procmedicaidref   sql.NullString `json:"procmedicaidref"`
	Procmedicaidresub sql.NullString `json:"procmedicaidresub"`
	Proclabcharges    float64        `json:"proclabcharges"`
	Procstatus        sql.NullString `json:"procstatus"`
	Procslidingscale  sql.NullString `json:"procslidingscale"`
	Proctosoverride   int64          `json:"proctosoverride"`
	Orderid           int64          `json:"orderid"`
	User              int64          `json:"user"`
	Active            string         `json:"active"`
	Cptnameext        sql.NullString `json:"cptnameext"`
}

// Unbilled procedures for a specific patient
func (q *Queries) ProceduresToBill(ctx context.Context, patientID int64) ([]ProceduresToBillRow, error) {
	rows, err := q.db.QueryContext(ctx, proceduresToBill, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProceduresToBillRow
	for rows.Next() {
		var i ProceduresToBillRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Procpatient,
			&i.Proceoc,
			&i.Proccpt,
			&i.Proccptmod,
			&i.Proccptmod2,
			&i.Proccptmod3,
			&i.Procdiag1,
			&i.Procdiag2,
			&i.Procdiag3,
			&i.Procdiag4,
			&i.Procdiagset,
			&i.Proccharges,
			&i.Procunits,
			&i.Procvoucher,
			&i.Procphysician,
			&i.Procdt,
			&i.Procdtend,
			&i.Procpos,
			&i.Proccomment,
			&i.Procbalorig,
			&i.Procbalcurrent,
			&i.Procamtpain,
			&i.Procbilled,
			&i.Procbillable,
			&i.Procauth,
			&i.Procrefdoc,
			&i.Procrefdt,
			&i.Procamtallowed,
			&i.Procdtbilled,
			&i.Proccurcovid,
			&i.Proccurcovtp,
			&i.Proccov1,
			&i.Proccov2,
			&i.Proccov3,
			&i.Proccov4,
			&i.Procmedicaidref,
			&i.Procmedicaidresub,
			&i.Proclabcharges,
			&i.Procstatus,
			&i.Procslidingscale,
			&i.Proctosoverride,
			&i.Orderid,
			&i.User,
			&i.Active,
			&i.Cptnameext,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
