// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reminders.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createReminder = `-- name: CreateReminder :execresult
INSERT INTO reminders (
  created_at, updated_at, user, patient,
  title, description, due_date, priority
) VALUES (
  NOW(), NOW(), ?, ?,
  ?, ?, ?,
  ?
)
`

type CreateReminderParams struct {
	UserID      int64          `json:"user_id"`
	PatientID   sql.NullInt64  `json:"patient_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	DueDate     sql.NullTime   `json:"due_date"`
	Priority    int32          `json:"priority"`
}

func (q *Queries) CreateReminder(ctx context.Context, arg CreateReminderParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createReminder,
		arg.UserID,
		arg.PatientID,
		arg.Title,
		arg.Description,
		arg.DueDate,
		arg.Priority,
	)
}

const deleteReminder = `-- name: DeleteReminder :exec
UPDATE reminders
SET updated_at = NOW(), deleted_at = NOW()
WHERE id = ?
  AND deleted_at IS NULL
`

func (q *Queries) DeleteReminder(ctx context.Context, reminderID int64) error {
	_, err := q.db.ExecContext(ctx, deleteReminder, reminderID)
	return err
}

const listRemindersByPatient = `-- name: ListRemindersByPatient :many
SELECT id, created_at, updated_at, deleted_at, user, patient, title, description, due_date, priority, status, completed_at FROM reminders
WHERE patient = ?
  AND deleted_at IS NULL
ORDER BY due_date ASC
`

func (q *Queries) ListRemindersByPatient(ctx context.Context, patientID sql.NullInt64) ([]Reminder, error) {
	rows, err := q.db.QueryContext(ctx, listRemindersByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reminder
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.User,
			&i.Patient,
			&i.Title,
			&i.Description,
			&i.DueDate,
			&i.Priority,
			&i.Status,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRemindersByUser = `-- name: ListRemindersByUser :many
SELECT id, created_at, updated_at, deleted_at, user, patient, title, description, due_date, priority, status, completed_at FROM reminders
WHERE user = ?
  AND deleted_at IS NULL
ORDER BY due_date ASC
`

func (q *Queries) ListRemindersByUser(ctx context.Context, userID int64) ([]Reminder, error) {
	rows, err := q.db.QueryContext(ctx, listRemindersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reminder
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.User,
			&i.Patient,
			&i.Title,
			&i.Description,
			&i.DueDate,
			&i.Priority,
			&i.Status,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReminderStatus = `-- name: UpdateReminderStatus :exec
UPDATE reminders
SET
  updated_at = NOW(),
  status = ?,
  completed_at = CASE
    WHEN ? = 'completed' THEN NOW()
    ELSE NULL
  END
WHERE id = ?
  AND deleted_at IS NULL
`

type UpdateReminderStatusParams struct {
	Status     string `json:"status"`
	ReminderID int64  `json:"reminder_id"`
}

func (q *Queries) UpdateReminderStatus(ctx context.Context, arg UpdateReminderStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateReminderStatus, arg.Status, arg.Status, arg.ReminderID)
	return err
}
