// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reporting.sql

package dbgen

import (
	"context"
)

const getReportById = `-- name: GetReportById :one
SELECT id, created_at, updated_at, deleted_at, report_name, report_uuid, report_locale, report_desc, report_type, report_sp, report_param_count, report_param_names, report_param_types, report_param_options, report_param_optional, report_acl, report_formatting FROM patient_reporting WHERE id = ?
`

func (q *Queries) GetReportById(ctx context.Context, id int64) (PatientReporting, error) {
	row := q.db.QueryRowContext(ctx, getReportById, id)
	var i PatientReporting
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ReportName,
		&i.ReportUuid,
		&i.ReportLocale,
		&i.ReportDesc,
		&i.ReportType,
		&i.ReportSp,
		&i.ReportParamCount,
		&i.ReportParamNames,
		&i.ReportParamTypes,
		&i.ReportParamOptions,
		&i.ReportParamOptional,
		&i.ReportAcl,
		&i.ReportFormatting,
	)
	return i, err
}

const getReportByUuid = `-- name: GetReportByUuid :one
SELECT id, created_at, updated_at, deleted_at, report_name, report_uuid, report_locale, report_desc, report_type, report_sp, report_param_count, report_param_names, report_param_types, report_param_options, report_param_optional, report_acl, report_formatting FROM patient_reporting WHERE report_uuid = ?
`

func (q *Queries) GetReportByUuid(ctx context.Context, reportUuid string) (PatientReporting, error) {
	row := q.db.QueryRowContext(ctx, getReportByUuid, reportUuid)
	var i PatientReporting
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ReportName,
		&i.ReportUuid,
		&i.ReportLocale,
		&i.ReportDesc,
		&i.ReportType,
		&i.ReportSp,
		&i.ReportParamCount,
		&i.ReportParamNames,
		&i.ReportParamTypes,
		&i.ReportParamOptions,
		&i.ReportParamOptional,
		&i.ReportAcl,
		&i.ReportFormatting,
	)
	return i, err
}

const listReports = `-- name: ListReports :many
SELECT id, created_at, updated_at, deleted_at, report_name, report_uuid, report_locale, report_desc, report_type, report_sp, report_param_count, report_param_names, report_param_types, report_param_options, report_param_optional, report_acl, report_formatting FROM patient_reporting ORDER BY report_name
`

func (q *Queries) ListReports(ctx context.Context) ([]PatientReporting, error) {
	rows, err := q.db.QueryContext(ctx, listReports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatientReporting
	for rows.Next() {
		var i PatientReporting
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ReportName,
			&i.ReportUuid,
			&i.ReportLocale,
			&i.ReportDesc,
			&i.ReportType,
			&i.ReportSp,
			&i.ReportParamCount,
			&i.ReportParamNames,
			&i.ReportParamTypes,
			&i.ReportParamOptions,
			&i.ReportParamOptional,
			&i.ReportAcl,
			&i.ReportFormatting,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
