// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createRoom = `-- name: CreateRoom :execresult
INSERT INTO room (
  created_at, updated_at, name, facility_id, room_type
) VALUES (
  NOW(), NOW(), ?, ?, ?
)
`

type CreateRoomParams struct {
	Name       string `json:"name"`
	FacilityID int64  `json:"facility_id"`
	RoomType   string `json:"room_type"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createRoom, arg.Name, arg.FacilityID, arg.RoomType)
}

const deactivateRoom = `-- name: DeactivateRoom :exec
UPDATE room
SET updated_at = NOW(),
    deleted_at = NOW(),
    active = 'inactive'
WHERE id = ?
  AND deleted_at IS NULL
`

func (q *Queries) DeactivateRoom(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deactivateRoom, id)
	return err
}

const getRoom = `-- name: GetRoom :one
SELECT id, created_at, updated_at, deleted_at, name, facility_id, room_type, active FROM room
WHERE id = ?
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetRoom(ctx context.Context, id int64) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoom, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.FacilityID,
		&i.RoomType,
		&i.Active,
	)
	return i, err
}

const listActiveRooms = `-- name: ListActiveRooms :many
SELECT id, created_at, updated_at, deleted_at, name, facility_id, room_type, active FROM room
WHERE deleted_at IS NULL
  AND active = 'active'
ORDER BY name
`

func (q *Queries) ListActiveRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, listActiveRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.FacilityID,
			&i.RoomType,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRooms = `-- name: ListRooms :many
SELECT id, created_at, updated_at, deleted_at, name, facility_id, room_type, active FROM room
WHERE deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, listRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.FacilityID,
			&i.RoomType,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoom = `-- name: UpdateRoom :exec
UPDATE room
SET updated_at = NOW(),
    name = ?,
    facility_id = ?,
    room_type = ?
WHERE id = ?
  AND deleted_at IS NULL
`

type UpdateRoomParams struct {
	Name       string `json:"name"`
	FacilityID int64  `json:"facility_id"`
	RoomType   string `json:"room_type"`
	ID         int64  `json:"id"`
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) error {
	_, err := q.db.ExecContext(ctx, updateRoom,
		arg.Name,
		arg.FacilityID,
		arg.RoomType,
		arg.ID,
	)
	return err
}
