// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rxnorm.sql

package dbgen

import (
	"context"
)

const searchRxNorm = `-- name: SearchRxNorm :many
SELECT id, created_at, updated_at, deleted_at, rxcui, drug_name, drug_class FROM rxnorm
WHERE deleted_at IS NULL
  AND drug_name LIKE CONCAT('%', ?, '%')
ORDER BY drug_name
LIMIT 50
`

func (q *Queries) SearchRxNorm(ctx context.Context, query interface{}) ([]Rxnorm, error) {
	rows, err := q.db.QueryContext(ctx, searchRxNorm, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rxnorm
	for rows.Next() {
		var i Rxnorm
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Rxcui,
			&i.DrugName,
			&i.DrugClass,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
