// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rxrefill.sql

package dbgen

import (
	"context"
)

const listRefillRequests = `-- name: ListRefillRequests :many
SELECT
  id,
  created_at,
  updated_at,
  deleted_at,
  user,
  patient,
  provider,
  rxorig,
  note,
  approved,
  locked
FROM rxrefillrequest
ORDER BY created_at DESC
LIMIT 50
`

// RxRefill: list all refill requests
func (q *Queries) ListRefillRequests(ctx context.Context) ([]Rxrefillrequest, error) {
	rows, err := q.db.QueryContext(ctx, listRefillRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rxrefillrequest
	for rows.Next() {
		var i Rxrefillrequest
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.User,
			&i.Patient,
			&i.Provider,
			&i.Rxorig,
			&i.Note,
			&i.Approved,
			&i.Locked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
