// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scanned_docs.sql

package dbgen

import (
	"context"
)

const getScannedDoc = `-- name: GetScannedDoc :one
SELECT id, created_at, updated_at, deleted_at, patient, filename, description, page_count, document_date, user, active FROM scanned_docs
WHERE id = ?
  AND active = 'active'
  AND deleted_at IS NULL
`

func (q *Queries) GetScannedDoc(ctx context.Context, id int64) (ScannedDoc, error) {
	row := q.db.QueryRowContext(ctx, getScannedDoc, id)
	var i ScannedDoc
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Patient,
		&i.Filename,
		&i.Description,
		&i.PageCount,
		&i.DocumentDate,
		&i.User,
		&i.Active,
	)
	return i, err
}

const listScannedDocs = `-- name: ListScannedDocs :many
SELECT id, created_at, updated_at, deleted_at, patient, filename, description, page_count, document_date, user, active FROM scanned_docs
WHERE patient = ?
  AND active = 'active'
  AND deleted_at IS NULL
ORDER BY document_date DESC
`

func (q *Queries) ListScannedDocs(ctx context.Context, patientID int64) ([]ScannedDoc, error) {
	rows, err := q.db.QueryContext(ctx, listScannedDocs, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScannedDoc
	for rows.Next() {
		var i ScannedDoc
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Patient,
			&i.Filename,
			&i.Description,
			&i.PageCount,
			&i.DocumentDate,
			&i.User,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
