// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduler_crud.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const getSchedulerById = `-- name: GetSchedulerById :one
SELECT id, created_at, updated_at, deleted_at, caldateof, calcreated, calmodified, caltype, calhour, calminute, calduration, calfacility, calroom, calphysician, calpatient, calcptcode, calstatus, calprenote, calpostnote, calmark, calgroupid, calgroupmembers, calrecurnote, calrecurid, calappttemplate, calattendees, user FROM scheduler WHERE id = ?
`

func (q *Queries) GetSchedulerById(ctx context.Context, id int64) (Scheduler, error) {
	row := q.db.QueryRowContext(ctx, getSchedulerById, id)
	var i Scheduler
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Caldateof,
		&i.Calcreated,
		&i.Calmodified,
		&i.Caltype,
		&i.Calhour,
		&i.Calminute,
		&i.Calduration,
		&i.Calfacility,
		&i.Calroom,
		&i.Calphysician,
		&i.Calpatient,
		&i.Calcptcode,
		&i.Calstatus,
		&i.Calprenote,
		&i.Calpostnote,
		&i.Calmark,
		&i.Calgroupid,
		&i.Calgroupmembers,
		&i.Calrecurnote,
		&i.Calrecurid,
		&i.Calappttemplate,
		&i.Calattendees,
		&i.User,
	)
	return i, err
}

const updateScheduler = `-- name: UpdateScheduler :exec
UPDATE scheduler SET
  caldateof = ?,
  calhour = ?,
  calminute = ?,
  calduration = ?,
  calmodified = ?
WHERE id = ?
`

type UpdateSchedulerParams struct {
	DateOf   time.Time    `json:"date_of"`
	Hour     int64        `json:"hour"`
	Minute   int64        `json:"minute"`
	Duration int64        `json:"duration"`
	Modified sql.NullTime `json:"modified"`
	ID       int64        `json:"id"`
}

func (q *Queries) UpdateScheduler(ctx context.Context, arg UpdateSchedulerParams) error {
	_, err := q.db.ExecContext(ctx, updateScheduler,
		arg.DateOf,
		arg.Hour,
		arg.Minute,
		arg.Duration,
		arg.Modified,
		arg.ID,
	)
	return err
}
