// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedulingrules.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createSchedulingRule = `-- name: CreateSchedulingRule :execresult
INSERT INTO schedulingrules (
  created_at, updated_at, user, provider, reason,
  dowbegin, dowend, datebegin, dateend, timebegin, timeend, newpatient
) VALUES (
  NOW(), NOW(), ?, ?, ?,
  ?, ?, ?, ?,
  ?, ?, ?
)
`

type CreateSchedulingRuleParams struct {
	UserID     int64          `json:"user_id"`
	Provider   sql.NullString `json:"provider"`
	Reason     sql.NullString `json:"reason"`
	Dowbegin   sql.NullInt32  `json:"dowbegin"`
	Dowend     sql.NullInt32  `json:"dowend"`
	Datebegin  sql.NullTime   `json:"datebegin"`
	Dateend    sql.NullTime   `json:"dateend"`
	Timebegin  sql.NullString `json:"timebegin"`
	Timeend    sql.NullString `json:"timeend"`
	Newpatient sql.NullBool   `json:"newpatient"`
}

func (q *Queries) CreateSchedulingRule(ctx context.Context, arg CreateSchedulingRuleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSchedulingRule,
		arg.UserID,
		arg.Provider,
		arg.Reason,
		arg.Dowbegin,
		arg.Dowend,
		arg.Datebegin,
		arg.Dateend,
		arg.Timebegin,
		arg.Timeend,
		arg.Newpatient,
	)
}

const deleteSchedulingRule = `-- name: DeleteSchedulingRule :exec
UPDATE schedulingrules
SET updated_at = NOW(), deleted_at = NOW()
WHERE id = ?
  AND deleted_at IS NULL
`

func (q *Queries) DeleteSchedulingRule(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSchedulingRule, id)
	return err
}

const getSchedulingRule = `-- name: GetSchedulingRule :one
SELECT id, created_at, updated_at, deleted_at, user, provider, reason, dowbegin, dowend, datebegin, dateend, timebegin, timeend, newpatient FROM schedulingrules
WHERE id = ?
  AND deleted_at IS NULL
`

func (q *Queries) GetSchedulingRule(ctx context.Context, id int64) (Schedulingrule, error) {
	row := q.db.QueryRowContext(ctx, getSchedulingRule, id)
	var i Schedulingrule
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.User,
		&i.Provider,
		&i.Reason,
		&i.Dowbegin,
		&i.Dowend,
		&i.Datebegin,
		&i.Dateend,
		&i.Timebegin,
		&i.Timeend,
		&i.Newpatient,
	)
	return i, err
}

const listSchedulingRules = `-- name: ListSchedulingRules :many
SELECT id, created_at, updated_at, deleted_at, user, provider, reason, dowbegin, dowend, datebegin, dateend, timebegin, timeend, newpatient FROM schedulingrules
WHERE deleted_at IS NULL
ORDER BY id DESC
`

func (q *Queries) ListSchedulingRules(ctx context.Context) ([]Schedulingrule, error) {
	rows, err := q.db.QueryContext(ctx, listSchedulingRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedulingrule
	for rows.Next() {
		var i Schedulingrule
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.User,
			&i.Provider,
			&i.Reason,
			&i.Dowbegin,
			&i.Dowend,
			&i.Datebegin,
			&i.Dateend,
			&i.Timebegin,
			&i.Timeend,
			&i.Newpatient,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSchedulingRule = `-- name: UpdateSchedulingRule :exec
UPDATE schedulingrules
SET
  updated_at = NOW(),
  provider = ?,
  reason = ?,
  dowbegin = ?,
  dowend = ?,
  datebegin = ?,
  dateend = ?,
  timebegin = ?,
  timeend = ?,
  newpatient = ?
WHERE id = ?
  AND deleted_at IS NULL
`

type UpdateSchedulingRuleParams struct {
	Provider   sql.NullString `json:"provider"`
	Reason     sql.NullString `json:"reason"`
	Dowbegin   sql.NullInt32  `json:"dowbegin"`
	Dowend     sql.NullInt32  `json:"dowend"`
	Datebegin  sql.NullTime   `json:"datebegin"`
	Dateend    sql.NullTime   `json:"dateend"`
	Timebegin  sql.NullString `json:"timebegin"`
	Timeend    sql.NullString `json:"timeend"`
	Newpatient sql.NullBool   `json:"newpatient"`
	ID         int64          `json:"id"`
}

func (q *Queries) UpdateSchedulingRule(ctx context.Context, arg UpdateSchedulingRuleParams) error {
	_, err := q.db.ExecContext(ctx, updateSchedulingRule,
		arg.Provider,
		arg.Reason,
		arg.Dowbegin,
		arg.Dowend,
		arg.Datebegin,
		arg.Dateend,
		arg.Timebegin,
		arg.Timeend,
		arg.Newpatient,
		arg.ID,
	)
	return err
}
