// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package dbgen

import (
	"context"
)

const searchAppointments = `-- name: SearchAppointments :many
SELECT
  s.id,
  CONCAT('Appt: ', p.ptlname) AS title,
  'appointment' AS result_type
FROM scheduler s
LEFT JOIN patient p ON s.calpatient = p.id
WHERE s.caldateof >= CURDATE()
  AND p.ptlname LIKE CONCAT('%', ?, '%')
LIMIT 5
`

type SearchAppointmentsRow struct {
	ID         int64  `json:"id"`
	Title      string `json:"title"`
	ResultType string `json:"result_type"`
}

// Global search: scheduler appointments by patient name (future only)
func (q *Queries) SearchAppointments(ctx context.Context, query interface{}) ([]SearchAppointmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchAppointments, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchAppointmentsRow
	for rows.Next() {
		var i SearchAppointmentsRow
		if err := rows.Scan(&i.ID, &i.Title, &i.ResultType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMessages = `-- name: SearchMessages :many
SELECT
  id,
  msgsubject AS title,
  'message' AS result_type
FROM messages
WHERE msgsubject LIKE CONCAT('%', ?, '%')
LIMIT 5
`

type SearchMessagesRow struct {
	ID         int64  `json:"id"`
	Title      string `json:"title"`
	ResultType string `json:"result_type"`
}

// Global search: messages by subject
func (q *Queries) SearchMessages(ctx context.Context, query interface{}) ([]SearchMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchMessages, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMessagesRow
	for rows.Next() {
		var i SearchMessagesRow
		if err := rows.Scan(&i.ID, &i.Title, &i.ResultType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPatients = `-- name: SearchPatients :many
SELECT
  id,
  ptlname,
  ptfname,
  ptid,
  'patient' AS result_type
FROM patient
WHERE (
  ptlname LIKE CONCAT('%', ?, '%')
  OR ptfname LIKE CONCAT('%', ?, '%')
  OR ptid LIKE CONCAT('%', ?, '%')
)
  AND ptarchive = 0
LIMIT 10
`

type SearchPatientsParams struct {
	Query interface{} `json:"query"`
}

type SearchPatientsRow struct {
	ID         int64  `json:"id"`
	Ptlname    string `json:"ptlname"`
	Ptfname    string `json:"ptfname"`
	Ptid       string `json:"ptid"`
	ResultType string `json:"result_type"`
}

// Global search: patients by name or ID
func (q *Queries) SearchPatients(ctx context.Context, arg SearchPatientsParams) ([]SearchPatientsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchPatients, arg.Query, arg.Query, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPatientsRow
	for rows.Next() {
		var i SearchPatientsRow
		if err := rows.Scan(
			&i.ID,
			&i.Ptlname,
			&i.Ptfname,
			&i.Ptid,
			&i.ResultType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
