// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signatures.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createSignature = `-- name: CreateSignature :execresult
INSERT INTO signatures (
  patient, module, module_field, oid,
  signature_data, format,
  collector_location, collector_model, collector_jobid,
  collector_finished, user
) VALUES (
  ?, ?, ?, ?,
  ?, ?,
  ?, ?, ?,
  ?, ?
)
`

type CreateSignatureParams struct {
	Patient           int64          `json:"patient"`
	Module            string         `json:"module"`
	ModuleField       string         `json:"module_field"`
	Oid               int64          `json:"oid"`
	SignatureData     sql.NullString `json:"signature_data"`
	Format            string         `json:"format"`
	CollectorLocation sql.NullString `json:"collector_location"`
	CollectorModel    sql.NullString `json:"collector_model"`
	CollectorJobid    sql.NullString `json:"collector_jobid"`
	CollectorFinished bool           `json:"collector_finished"`
	User              int64          `json:"user"`
}

func (q *Queries) CreateSignature(ctx context.Context, arg CreateSignatureParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSignature,
		arg.Patient,
		arg.Module,
		arg.ModuleField,
		arg.Oid,
		arg.SignatureData,
		arg.Format,
		arg.CollectorLocation,
		arg.CollectorModel,
		arg.CollectorJobid,
		arg.CollectorFinished,
		arg.User,
	)
}

const getSignature = `-- name: GetSignature :one
SELECT id, created_at, updated_at, deleted_at, patient, module, module_field, oid, signature_data, format, collector_location, collector_model, collector_jobid, collector_finished, user FROM signatures
WHERE id = ?
  AND deleted_at IS NULL
`

func (q *Queries) GetSignature(ctx context.Context, id int64) (Signature, error) {
	row := q.db.QueryRowContext(ctx, getSignature, id)
	var i Signature
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Patient,
		&i.Module,
		&i.ModuleField,
		&i.Oid,
		&i.SignatureData,
		&i.Format,
		&i.CollectorLocation,
		&i.CollectorModel,
		&i.CollectorJobid,
		&i.CollectorFinished,
		&i.User,
	)
	return i, err
}

const listSignaturesByPatient = `-- name: ListSignaturesByPatient :many
SELECT id, created_at, updated_at, deleted_at, patient, module, module_field, oid, signature_data, format, collector_location, collector_model, collector_jobid, collector_finished, user FROM signatures
WHERE patient = ?
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListSignaturesByPatient(ctx context.Context, patientID int64) ([]Signature, error) {
	rows, err := q.db.QueryContext(ctx, listSignaturesByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Signature
	for rows.Next() {
		var i Signature
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Patient,
			&i.Module,
			&i.ModuleField,
			&i.Oid,
			&i.SignatureData,
			&i.Format,
			&i.CollectorLocation,
			&i.CollectorModel,
			&i.CollectorJobid,
			&i.CollectorFinished,
			&i.User,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
