// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: social_history.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createSocialHistory = `-- name: CreateSocialHistory :execresult
INSERT INTO social_history (patient, smoking_status, smoking_detail, alcohol_use, alcohol_detail, drug_use, drug_detail, exercise_frequency, occupation, living_situation, food_insecurity, transportation_access, notes, recorded_date, user, active, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'active', NOW(), NOW())
`

type CreateSocialHistoryParams struct {
	Patient              int64          `json:"patient"`
	SmokingStatus        string         `json:"smoking_status"`
	SmokingDetail        string         `json:"smoking_detail"`
	AlcoholUse           string         `json:"alcohol_use"`
	AlcoholDetail        string         `json:"alcohol_detail"`
	DrugUse              string         `json:"drug_use"`
	DrugDetail           string         `json:"drug_detail"`
	ExerciseFrequency    string         `json:"exercise_frequency"`
	Occupation           string         `json:"occupation"`
	LivingSituation      string         `json:"living_situation"`
	FoodInsecurity       bool           `json:"food_insecurity"`
	TransportationAccess bool           `json:"transportation_access"`
	Notes                sql.NullString `json:"notes"`
	RecordedDate         time.Time      `json:"recorded_date"`
	User                 int64          `json:"user"`
}

func (q *Queries) CreateSocialHistory(ctx context.Context, arg CreateSocialHistoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSocialHistory,
		arg.Patient,
		arg.SmokingStatus,
		arg.SmokingDetail,
		arg.AlcoholUse,
		arg.AlcoholDetail,
		arg.DrugUse,
		arg.DrugDetail,
		arg.ExerciseFrequency,
		arg.Occupation,
		arg.LivingSituation,
		arg.FoodInsecurity,
		arg.TransportationAccess,
		arg.Notes,
		arg.RecordedDate,
		arg.User,
	)
}

const getLatestSocialHistory = `-- name: GetLatestSocialHistory :one
SELECT id, patient, smoking_status, smoking_detail, alcohol_use, alcohol_detail, drug_use, drug_detail, exercise_frequency, occupation, living_situation, food_insecurity, transportation_access, notes, recorded_date, user, active, created_at, updated_at, deleted_at FROM social_history
WHERE patient = ? AND active = 'active'
ORDER BY recorded_date DESC
LIMIT 1
`

func (q *Queries) GetLatestSocialHistory(ctx context.Context, patient int64) (SocialHistory, error) {
	row := q.db.QueryRowContext(ctx, getLatestSocialHistory, patient)
	var i SocialHistory
	err := row.Scan(
		&i.ID,
		&i.Patient,
		&i.SmokingStatus,
		&i.SmokingDetail,
		&i.AlcoholUse,
		&i.AlcoholDetail,
		&i.DrugUse,
		&i.DrugDetail,
		&i.ExerciseFrequency,
		&i.Occupation,
		&i.LivingSituation,
		&i.FoodInsecurity,
		&i.TransportationAccess,
		&i.Notes,
		&i.RecordedDate,
		&i.User,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listSocialHistory = `-- name: ListSocialHistory :many
SELECT id, patient, smoking_status, smoking_detail, alcohol_use, alcohol_detail, drug_use, drug_detail, exercise_frequency, occupation, living_situation, food_insecurity, transportation_access, notes, recorded_date, user, active, created_at, updated_at, deleted_at FROM social_history
WHERE patient = ? AND active = 'active'
ORDER BY recorded_date DESC
`

func (q *Queries) ListSocialHistory(ctx context.Context, patient int64) ([]SocialHistory, error) {
	rows, err := q.db.QueryContext(ctx, listSocialHistory, patient)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SocialHistory
	for rows.Next() {
		var i SocialHistory
		if err := rows.Scan(
			&i.ID,
			&i.Patient,
			&i.SmokingStatus,
			&i.SmokingDetail,
			&i.AlcoholUse,
			&i.AlcoholDetail,
			&i.DrugUse,
			&i.DrugDetail,
			&i.ExerciseFrequency,
			&i.Occupation,
			&i.LivingSituation,
			&i.FoodInsecurity,
			&i.TransportationAccess,
			&i.Notes,
			&i.RecordedDate,
			&i.User,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSocialHistory = `-- name: RemoveSocialHistory :exec
UPDATE social_history SET active = 'inactive', deleted_at = NOW(), updated_at = NOW()
WHERE id = ? AND patient = ?
`

type RemoveSocialHistoryParams struct {
	ID      int64 `json:"id"`
	Patient int64 `json:"patient"`
}

func (q *Queries) RemoveSocialHistory(ctx context.Context, arg RemoveSocialHistoryParams) error {
	_, err := q.db.ExecContext(ctx, removeSocialHistory, arg.ID, arg.Patient)
	return err
}
