// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: specialties.sql

package dbgen

import (
	"context"
)

const listSpecialties = `-- name: ListSpecialties :many
SELECT id, created_at, updated_at, deleted_at, name, display_value, active FROM specialties ORDER BY name
`

func (q *Queries) ListSpecialties(ctx context.Context) ([]Specialty, error) {
	rows, err := q.db.QueryContext(ctx, listSpecialties)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Specialty
	for rows.Next() {
		var i Specialty
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.DisplayValue,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
