// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: superbill_template.sql

package dbgen

import (
	"context"
)

const getSuperbillTemplate = `-- name: GetSuperbillTemplate :one
SELECT id, created_at, updated_at, deleted_at, name, template_data, active FROM superbill_template WHERE id = ?
`

func (q *Queries) GetSuperbillTemplate(ctx context.Context, id int64) (SuperbillTemplate, error) {
	row := q.db.QueryRowContext(ctx, getSuperbillTemplate, id)
	var i SuperbillTemplate
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.TemplateData,
		&i.Active,
	)
	return i, err
}

const listSuperbillTemplates = `-- name: ListSuperbillTemplates :many
SELECT id, created_at, updated_at, deleted_at, name, template_data, active FROM superbill_template ORDER BY name
`

func (q *Queries) ListSuperbillTemplates(ctx context.Context) ([]SuperbillTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listSuperbillTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuperbillTemplate
	for rows.Next() {
		var i SuperbillTemplate
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.TemplateData,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
