// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: superbills.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createSuperbill = `-- name: CreateSuperbill :execresult
INSERT INTO superbill (
  patient, date_from, date_to, provider, status, total_charges,
  date_created, user, active, created_at, updated_at
) VALUES (
  ?, ?, ?,
  ?, ?, ?,
  ?, ?, 'active', NOW(), NOW()
)
`

type CreateSuperbillParams struct {
	Patient      int64     `json:"patient"`
	DateFrom     time.Time `json:"date_from"`
	DateTo       time.Time `json:"date_to"`
	Provider     int64     `json:"provider"`
	Status       string    `json:"status"`
	TotalCharges float64   `json:"total_charges"`
	DateCreated  time.Time `json:"date_created"`
	User         int64     `json:"user"`
}

func (q *Queries) CreateSuperbill(ctx context.Context, arg CreateSuperbillParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSuperbill,
		arg.Patient,
		arg.DateFrom,
		arg.DateTo,
		arg.Provider,
		arg.Status,
		arg.TotalCharges,
		arg.DateCreated,
		arg.User,
	)
}

const getSuperbill = `-- name: GetSuperbill :one
SELECT id, created_at, updated_at, deleted_at, patient, date_from, date_to, provider, status, total_charges, date_created, user, active FROM superbill WHERE id = ?
`

func (q *Queries) GetSuperbill(ctx context.Context, id int64) (Superbill, error) {
	row := q.db.QueryRowContext(ctx, getSuperbill, id)
	var i Superbill
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Patient,
		&i.DateFrom,
		&i.DateTo,
		&i.Provider,
		&i.Status,
		&i.TotalCharges,
		&i.DateCreated,
		&i.User,
		&i.Active,
	)
	return i, err
}

const listSuperbills = `-- name: ListSuperbills :many
SELECT id, created_at, updated_at, deleted_at, patient, date_from, date_to, provider, status, total_charges, date_created, user, active FROM superbill ORDER BY date_created DESC
`

func (q *Queries) ListSuperbills(ctx context.Context) ([]Superbill, error) {
	rows, err := q.db.QueryContext(ctx, listSuperbills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Superbill
	for rows.Next() {
		var i Superbill
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Patient,
			&i.DateFrom,
			&i.DateTo,
			&i.Provider,
			&i.Status,
			&i.TotalCharges,
			&i.DateCreated,
			&i.User,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
