// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createTag = `-- name: CreateTag :execresult
INSERT INTO patienttag (
  tag, patient, user, datecreate, created_at, updated_at
) VALUES (
  ?, ?, ?, NOW(), NOW(), NOW()
)
`

type CreateTagParams struct {
	Tag       string `json:"tag"`
	PatientID int64  `json:"patient_id"`
	UserID    int64  `json:"user_id"`
}

// Tags: create a new patient tag
func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTag, arg.Tag, arg.PatientID, arg.UserID)
}

const expireTag = `-- name: ExpireTag :exec
UPDATE patienttag
SET dateexpire = NOW(), updated_at = NOW()
WHERE id = ?
`

// Tags: expire a tag (soft-delete by setting dateexpire)
func (q *Queries) ExpireTag(ctx context.Context, tagID int64) error {
	_, err := q.db.ExecContext(ctx, expireTag, tagID)
	return err
}

const listTags = `-- name: ListTags :many
SELECT
  id,
  tag,
  patient,
  user,
  datecreate,
  dateexpire,
  created_at,
  updated_at,
  deleted_at
FROM patienttag
WHERE patient = ?
  AND (dateexpire IS NULL OR dateexpire > NOW())
ORDER BY datecreate DESC
`

type ListTagsRow struct {
	ID         int64        `json:"id"`
	Tag        string       `json:"tag"`
	Patient    int64        `json:"patient"`
	User       int64        `json:"user"`
	Datecreate time.Time    `json:"datecreate"`
	Dateexpire sql.NullTime `json:"dateexpire"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	DeletedAt  sql.NullTime `json:"deleted_at"`
}

// Tags: list active tags for a patient (not expired)
func (q *Queries) ListTags(ctx context.Context, patientID int64) ([]ListTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTags, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsRow
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Tag,
			&i.Patient,
			&i.User,
			&i.Datecreate,
			&i.Dateexpire,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByTag = `-- name: SearchByTag :many
SELECT DISTINCT
  p.id AS patient_id,
  p.ptlname AS last_name,
  p.ptfname AS first_name,
  p.ptid AS patient_id_ext,
  t.tag
FROM patienttag t
JOIN patient p ON t.patient = p.id
WHERE t.tag LIKE CONCAT('%', ?, '%')
  AND (t.dateexpire IS NULL OR t.dateexpire > NOW())
`

type SearchByTagRow struct {
	PatientID    int64  `json:"patient_id"`
	LastName     string `json:"last_name"`
	FirstName    string `json:"first_name"`
	PatientIDExt string `json:"patient_id_ext"`
	Tag          string `json:"tag"`
}

// Tags: search patients by tag text
func (q *Queries) SearchByTag(ctx context.Context, query interface{}) ([]SearchByTagRow, error) {
	rows, err := q.db.QueryContext(ctx, searchByTag, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchByTagRow
	for rows.Next() {
		var i SearchByTagRow
		if err := rows.Scan(
			&i.PatientID,
			&i.LastName,
			&i.FirstName,
			&i.PatientIDExt,
			&i.Tag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
