// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: templates.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createTemplate = `-- name: CreateTemplate :execresult
INSERT INTO appttemplate (
  atname, atduration, atequipment, atcolor,
  created_at, updated_at
) VALUES (
  ?, ?, ?, ?,
  NOW(), NOW()
)
`

type CreateTemplateParams struct {
	Atname      string         `json:"atname"`
	Atduration  int64          `json:"atduration"`
	Atequipment sql.NullString `json:"atequipment"`
	Atcolor     string         `json:"atcolor"`
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTemplate,
		arg.Atname,
		arg.Atduration,
		arg.Atequipment,
		arg.Atcolor,
	)
}

const deleteTemplate = `-- name: DeleteTemplate :exec
DELETE FROM appttemplate WHERE id = ?
`

func (q *Queries) DeleteTemplate(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTemplate, id)
	return err
}

const getTemplate = `-- name: GetTemplate :one
SELECT id, created_at, updated_at, deleted_at, atname, atduration, atequipment, atcolor FROM appttemplate WHERE id = ?
`

func (q *Queries) GetTemplate(ctx context.Context, id int64) (Appttemplate, error) {
	row := q.db.QueryRowContext(ctx, getTemplate, id)
	var i Appttemplate
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Atname,
		&i.Atduration,
		&i.Atequipment,
		&i.Atcolor,
	)
	return i, err
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, created_at, updated_at, deleted_at, atname, atduration, atequipment, atcolor FROM appttemplate ORDER BY atname
`

func (q *Queries) ListTemplates(ctx context.Context) ([]Appttemplate, error) {
	rows, err := q.db.QueryContext(ctx, listTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appttemplate
	for rows.Next() {
		var i Appttemplate
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Atname,
			&i.Atduration,
			&i.Atequipment,
			&i.Atcolor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplate = `-- name: UpdateTemplate :exec
UPDATE appttemplate SET
  atname = ?,
  atduration = ?,
  atequipment = ?,
  atcolor = ?,
  updated_at = NOW()
WHERE id = ?
`

type UpdateTemplateParams struct {
	Atname      string         `json:"atname"`
	Atduration  int64          `json:"atduration"`
	Atequipment sql.NullString `json:"atequipment"`
	Atcolor     string         `json:"atcolor"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) error {
	_, err := q.db.ExecContext(ctx, updateTemplate,
		arg.Atname,
		arg.Atduration,
		arg.Atequipment,
		arg.Atcolor,
		arg.ID,
	)
	return err
}
