// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tools.sql

package dbgen

import (
	"context"
)

const getTool = `-- name: GetTool :one
SELECT id, created_at, updated_at, deleted_at, tool_name, tool_description, tool_class, tool_parameters, active FROM tools
WHERE id = ?
  AND active = 'active'
  AND deleted_at IS NULL
`

func (q *Queries) GetTool(ctx context.Context, id int64) (Tool, error) {
	row := q.db.QueryRowContext(ctx, getTool, id)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ToolName,
		&i.ToolDescription,
		&i.ToolClass,
		&i.ToolParameters,
		&i.Active,
	)
	return i, err
}

const listTools = `-- name: ListTools :many
SELECT id, created_at, updated_at, deleted_at, tool_name, tool_description, tool_class, tool_parameters, active FROM tools
WHERE active = 'active'
  AND deleted_at IS NULL
ORDER BY tool_name
`

func (q *Queries) ListTools(ctx context.Context) ([]Tool, error) {
	rows, err := q.db.QueryContext(ctx, listTools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tool
	for rows.Next() {
		var i Tool
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ToolName,
			&i.ToolDescription,
			&i.ToolClass,
			&i.ToolParameters,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
