// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_preferences.sql

package dbgen

import (
	"context"
	"database/sql"
)

const getUserPreferenceByKey = `-- name: GetUserPreferenceByKey :one
SELECT id, created_at, updated_at, deleted_at, option_key, default_value, title, section, option_type, options FROM user_preferences WHERE option_key = ?
`

func (q *Queries) GetUserPreferenceByKey(ctx context.Context, optionKey string) (UserPreference, error) {
	row := q.db.QueryRowContext(ctx, getUserPreferenceByKey, optionKey)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OptionKey,
		&i.DefaultValue,
		&i.Title,
		&i.Section,
		&i.OptionType,
		&i.Options,
	)
	return i, err
}

const listUserPreferences = `-- name: ListUserPreferences :many
SELECT id, created_at, updated_at, deleted_at, option_key, default_value, title, section, option_type, options FROM user_preferences ORDER BY section, option_key
`

func (q *Queries) ListUserPreferences(ctx context.Context) ([]UserPreference, error) {
	rows, err := q.db.QueryContext(ctx, listUserPreferences)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserPreference
	for rows.Next() {
		var i UserPreference
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.OptionKey,
			&i.DefaultValue,
			&i.Title,
			&i.Section,
			&i.OptionType,
			&i.Options,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserPreference = `-- name: UpsertUserPreference :exec
INSERT INTO user_preferences (option_key, default_value, title, section, option_type, options)
VALUES (?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
  default_value = VALUES(default_value),
  title = VALUES(title),
  section = VALUES(section),
  option_type = VALUES(option_type),
  options = VALUES(options)
`

type UpsertUserPreferenceParams struct {
	OptionKey    string         `json:"option_key"`
	DefaultValue string         `json:"default_value"`
	Title        string         `json:"title"`
	Section      string         `json:"section"`
	OptionType   string         `json:"option_type"`
	Options      sql.NullString `json:"options"`
}

func (q *Queries) UpsertUserPreference(ctx context.Context, arg UpsertUserPreferenceParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserPreference,
		arg.OptionKey,
		arg.DefaultValue,
		arg.Title,
		arg.Section,
		arg.OptionType,
		arg.Options,
	)
	return err
}
