// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package dbgen

import (
	"context"
)

const checkDuplicateUsername = `-- name: CheckDuplicateUsername :many
SELECT id FROM user WHERE username = ?
`

func (q *Queries) CheckDuplicateUsername(ctx context.Context, username string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, checkDuplicateUsername, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const checkUserPassword = `-- name: CheckUserPassword :one
SELECT id, created_at, updated_at, deleted_at, username, userpassword, usertype, userrealphy, userfname, usermname, userlname, userdescrip, userlevel, userfac, userphy, userphygrp, usermanageopt, useremail, usersms, usersmsprovider, usertitle FROM user
WHERE username = ?
  AND userpassword = ?
`

type CheckUserPasswordParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

func (q *Queries) CheckUserPassword(ctx context.Context, arg CheckUserPasswordParams) (User, error) {
	row := q.db.QueryRowContext(ctx, checkUserPassword, arg.Username, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Username,
		&i.Userpassword,
		&i.Usertype,
		&i.Userrealphy,
		&i.Userfname,
		&i.Usermname,
		&i.Userlname,
		&i.Userdescrip,
		&i.Userlevel,
		&i.Userfac,
		&i.Userphy,
		&i.Userphygrp,
		&i.Usermanageopt,
		&i.Useremail,
		&i.Usersms,
		&i.Usersmsprovider,
		&i.Usertitle,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, created_at, updated_at, deleted_at, username, userpassword, usertype, userrealphy, userfname, usermname, userlname, userdescrip, userlevel, userfac, userphy, userphygrp, usermanageopt, useremail, usersms, usersmsprovider, usertitle FROM user WHERE id = ?
`

func (q *Queries) GetUserById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Username,
		&i.Userpassword,
		&i.Usertype,
		&i.Userrealphy,
		&i.Userfname,
		&i.Usermname,
		&i.Userlname,
		&i.Userdescrip,
		&i.Userlevel,
		&i.Userfac,
		&i.Userphy,
		&i.Userphygrp,
		&i.Usermanageopt,
		&i.Useremail,
		&i.Usersms,
		&i.Usersmsprovider,
		&i.Usertitle,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, created_at, updated_at, deleted_at, username, userpassword, usertype, userrealphy, userfname, usermname, userlname, userdescrip, userlevel, userfac, userphy, userphygrp, usermanageopt, useremail, usersms, usersmsprovider, usertitle FROM user WHERE username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Username,
		&i.Userpassword,
		&i.Usertype,
		&i.Userrealphy,
		&i.Userfname,
		&i.Usermname,
		&i.Userlname,
		&i.Userdescrip,
		&i.Userlevel,
		&i.Userfac,
		&i.Userphy,
		&i.Userphygrp,
		&i.Usermanageopt,
		&i.Useremail,
		&i.Usersms,
		&i.Usersmsprovider,
		&i.Usertitle,
	)
	return i, err
}

const getUserCount = `-- name: GetUserCount :one
SELECT COUNT(*) FROM user
`

func (q *Queries) GetUserCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}
