// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package dbgen

import (
	"context"
	"database/sql"
)

const checkDuplicateUsername = `-- name: CheckDuplicateUsername :many
SELECT id FROM user WHERE username = ?
`

func (q *Queries) CheckDuplicateUsername(ctx context.Context, username string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, checkDuplicateUsername, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const checkUserPassword = `-- name: CheckUserPassword :one
SELECT id, created_at, updated_at, deleted_at, username, userpassword, userpassword_bcrypt, usertype, userrealphy, userfname, usermname, userlname, userdescrip, userlevel, userfac, userphy, userphygrp, usermanageopt, useremail, usersms, usersmsprovider, usertitle FROM user
WHERE username = ?
  AND userpassword = ?
`

type CheckUserPasswordParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

func (q *Queries) CheckUserPassword(ctx context.Context, arg CheckUserPasswordParams) (User, error) {
	row := q.db.QueryRowContext(ctx, checkUserPassword, arg.Username, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Username,
		&i.Userpassword,
		&i.UserpasswordBcrypt,
		&i.Usertype,
		&i.Userrealphy,
		&i.Userfname,
		&i.Usermname,
		&i.Userlname,
		&i.Userdescrip,
		&i.Userlevel,
		&i.Userfac,
		&i.Userphy,
		&i.Userphygrp,
		&i.Usermanageopt,
		&i.Useremail,
		&i.Usersms,
		&i.Usersmsprovider,
		&i.Usertitle,
	)
	return i, err
}

const createUser = `-- name: CreateUser :execresult
INSERT INTO user (username, userpassword, userfname, userlname, userdescrip, usertype)
VALUES (
  ?, ?, ?,
  ?, ?, ?
)
`

type CreateUserParams struct {
	Username     string         `json:"username"`
	Userpassword string         `json:"userpassword"`
	Userfname    sql.NullString `json:"userfname"`
	Userlname    sql.NullString `json:"userlname"`
	Userdescrip  sql.NullString `json:"userdescrip"`
	Usertype     sql.NullString `json:"usertype"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.Username,
		arg.Userpassword,
		arg.Userfname,
		arg.Userlname,
		arg.Userdescrip,
		arg.Usertype,
	)
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM user WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserById = `-- name: GetUserById :one
SELECT id, created_at, updated_at, deleted_at, username, userpassword, userpassword_bcrypt, usertype, userrealphy, userfname, usermname, userlname, userdescrip, userlevel, userfac, userphy, userphygrp, usermanageopt, useremail, usersms, usersmsprovider, usertitle FROM user WHERE id = ?
`

func (q *Queries) GetUserById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Username,
		&i.Userpassword,
		&i.UserpasswordBcrypt,
		&i.Usertype,
		&i.Userrealphy,
		&i.Userfname,
		&i.Usermname,
		&i.Userlname,
		&i.Userdescrip,
		&i.Userlevel,
		&i.Userfac,
		&i.Userphy,
		&i.Userphygrp,
		&i.Usermanageopt,
		&i.Useremail,
		&i.Usersms,
		&i.Usersmsprovider,
		&i.Usertitle,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, created_at, updated_at, deleted_at, username, userpassword, userpassword_bcrypt, usertype, userrealphy, userfname, usermname, userlname, userdescrip, userlevel, userfac, userphy, userphygrp, usermanageopt, useremail, usersms, usersmsprovider, usertitle FROM user WHERE username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Username,
		&i.Userpassword,
		&i.UserpasswordBcrypt,
		&i.Usertype,
		&i.Userrealphy,
		&i.Userfname,
		&i.Usermname,
		&i.Userlname,
		&i.Userdescrip,
		&i.Userlevel,
		&i.Userfac,
		&i.Userphy,
		&i.Userphygrp,
		&i.Usermanageopt,
		&i.Useremail,
		&i.Usersms,
		&i.Usersmsprovider,
		&i.Usertitle,
	)
	return i, err
}

const getUserCount = `-- name: GetUserCount :one
SELECT COUNT(*) FROM user
`

func (q *Queries) GetUserCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, userfname, userlname, userdescrip, usertype
FROM user
ORDER BY userlname, userfname
`

type ListUsersRow struct {
	ID          int64          `json:"id"`
	Username    string         `json:"username"`
	Userfname   sql.NullString `json:"userfname"`
	Userlname   sql.NullString `json:"userlname"`
	Userdescrip sql.NullString `json:"userdescrip"`
	Usertype    sql.NullString `json:"usertype"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Userfname,
			&i.Userlname,
			&i.Userdescrip,
			&i.Usertype,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE user SET
  username = ?,
  userfname = ?,
  userlname = ?,
  userdescrip = ?,
  usertype = ?
WHERE id = ?
`

type UpdateUserParams struct {
	Username    string         `json:"username"`
	Userfname   sql.NullString `json:"userfname"`
	Userlname   sql.NullString `json:"userlname"`
	Userdescrip sql.NullString `json:"userdescrip"`
	Usertype    sql.NullString `json:"usertype"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Username,
		arg.Userfname,
		arg.Userlname,
		arg.Userdescrip,
		arg.Usertype,
		arg.ID,
	)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE user SET userpassword = ?
WHERE id = ?
`

type UpdateUserPasswordParams struct {
	Userpassword string `json:"userpassword"`
	ID           int64  `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.Userpassword, arg.ID)
	return err
}
