// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vitals.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createVitals = `-- name: CreateVitals :execresult
INSERT INTO vitals (
  patient, date_taken, systolic, diastolic, heart_rate,
  respiratory_rate, temperature, oxygen_saturation,
  height_cm, weight_kg, bmi, notes, user,
  created_at, updated_at
) VALUES (
  ?, ?, ?, ?,
  ?, ?, ?,
  ?, ?, ?,
  ?, ?, ?,
  NOW(), NOW()
)
`

type CreateVitalsParams struct {
	PatientID        int64          `json:"patient_id"`
	DateTaken        time.Time      `json:"date_taken"`
	Systolic         sql.NullInt32  `json:"systolic"`
	Diastolic        sql.NullInt32  `json:"diastolic"`
	HeartRate        sql.NullInt32  `json:"heart_rate"`
	RespiratoryRate  sql.NullInt32  `json:"respiratory_rate"`
	Temperature      sql.NullString `json:"temperature"`
	OxygenSaturation sql.NullInt32  `json:"oxygen_saturation"`
	HeightCm         sql.NullString `json:"height_cm"`
	WeightKg         sql.NullString `json:"weight_kg"`
	Bmi              sql.NullString `json:"bmi"`
	Notes            sql.NullString `json:"notes"`
	UserID           int64          `json:"user_id"`
}

func (q *Queries) CreateVitals(ctx context.Context, arg CreateVitalsParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createVitals,
		arg.PatientID,
		arg.DateTaken,
		arg.Systolic,
		arg.Diastolic,
		arg.HeartRate,
		arg.RespiratoryRate,
		arg.Temperature,
		arg.OxygenSaturation,
		arg.HeightCm,
		arg.WeightKg,
		arg.Bmi,
		arg.Notes,
		arg.UserID,
	)
}

const getLatestVitals = `-- name: GetLatestVitals :one
SELECT id, patient, date_taken, systolic, diastolic, heart_rate, respiratory_rate, temperature, oxygen_saturation, height_cm, weight_kg, bmi, notes, user, created_at, updated_at, deleted_at FROM vitals
WHERE patient = ?
ORDER BY date_taken DESC
LIMIT 1
`

func (q *Queries) GetLatestVitals(ctx context.Context, patientID int64) (Vital, error) {
	row := q.db.QueryRowContext(ctx, getLatestVitals, patientID)
	var i Vital
	err := row.Scan(
		&i.ID,
		&i.Patient,
		&i.DateTaken,
		&i.Systolic,
		&i.Diastolic,
		&i.HeartRate,
		&i.RespiratoryRate,
		&i.Temperature,
		&i.OxygenSaturation,
		&i.HeightCm,
		&i.WeightKg,
		&i.Bmi,
		&i.Notes,
		&i.User,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listVitals = `-- name: ListVitals :many
SELECT id, patient, date_taken, systolic, diastolic, heart_rate, respiratory_rate, temperature, oxygen_saturation, height_cm, weight_kg, bmi, notes, user, created_at, updated_at, deleted_at FROM vitals
WHERE patient = ?
ORDER BY date_taken DESC
`

func (q *Queries) ListVitals(ctx context.Context, patientID int64) ([]Vital, error) {
	rows, err := q.db.QueryContext(ctx, listVitals, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vital
	for rows.Next() {
		var i Vital
		if err := rows.Scan(
			&i.ID,
			&i.Patient,
			&i.DateTaken,
			&i.Systolic,
			&i.Diastolic,
			&i.HeartRate,
			&i.RespiratoryRate,
			&i.Temperature,
			&i.OxygenSaturation,
			&i.HeightCm,
			&i.WeightKg,
			&i.Bmi,
			&i.Notes,
			&i.User,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
