// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflow_status.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const listWorkflowStatus = `-- name: ListWorkflowStatus :many
SELECT ws.id, ws.created_at, ws.updated_at, ws.deleted_at, ws.stamp, ws.patient, ws.user, ws.status_type, ws.status_completed, wst.status_name, wst.status_order, wst.status_module
FROM workflow_status ws
LEFT JOIN workflow_status_type wst ON ws.status_type = wst.id
WHERE ws.patient = ?
  AND ws.deleted_at IS NULL
ORDER BY ws.stamp DESC
`

type ListWorkflowStatusRow struct {
	ID              int64          `json:"id"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
	Stamp           time.Time      `json:"stamp"`
	Patient         int64          `json:"patient"`
	User            int64          `json:"user"`
	StatusType      int64          `json:"status_type"`
	StatusCompleted bool           `json:"status_completed"`
	StatusName      sql.NullString `json:"status_name"`
	StatusOrder     sql.NullString `json:"status_order"`
	StatusModule    sql.NullString `json:"status_module"`
}

func (q *Queries) ListWorkflowStatus(ctx context.Context, patientID int64) ([]ListWorkflowStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowStatus, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkflowStatusRow
	for rows.Next() {
		var i ListWorkflowStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Stamp,
			&i.Patient,
			&i.User,
			&i.StatusType,
			&i.StatusCompleted,
			&i.StatusName,
			&i.StatusOrder,
			&i.StatusModule,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowStatusForDate = `-- name: ListWorkflowStatusForDate :many
SELECT ws.id, ws.created_at, ws.updated_at, ws.deleted_at, ws.stamp, ws.patient, ws.user, ws.status_type, ws.status_completed, wst.status_name, wst.status_order, wst.status_module
FROM workflow_status ws
LEFT JOIN workflow_status_type wst ON ws.status_type = wst.id
WHERE ws.patient = ?
  AND DATE(ws.stamp) = ?
  AND ws.deleted_at IS NULL
ORDER BY ws.stamp DESC
`

type ListWorkflowStatusForDateParams struct {
	PatientID  int64     `json:"patient_id"`
	StatusDate time.Time `json:"status_date"`
}

type ListWorkflowStatusForDateRow struct {
	ID              int64          `json:"id"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
	Stamp           time.Time      `json:"stamp"`
	Patient         int64          `json:"patient"`
	User            int64          `json:"user"`
	StatusType      int64          `json:"status_type"`
	StatusCompleted bool           `json:"status_completed"`
	StatusName      sql.NullString `json:"status_name"`
	StatusOrder     sql.NullString `json:"status_order"`
	StatusModule    sql.NullString `json:"status_module"`
}

func (q *Queries) ListWorkflowStatusForDate(ctx context.Context, arg ListWorkflowStatusForDateParams) ([]ListWorkflowStatusForDateRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowStatusForDate, arg.PatientID, arg.StatusDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkflowStatusForDateRow
	for rows.Next() {
		var i ListWorkflowStatusForDateRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Stamp,
			&i.Patient,
			&i.User,
			&i.StatusType,
			&i.StatusCompleted,
			&i.StatusName,
			&i.StatusOrder,
			&i.StatusModule,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWorkflowStatus = `-- name: SetWorkflowStatus :execresult
INSERT INTO workflow_status (
  patient, user, status_type, status_completed,
  stamp, created_at, updated_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  NOW(),
  NOW()
)
`

type SetWorkflowStatusParams struct {
	PatientID       int64     `json:"patient_id"`
	UserID          int64     `json:"user_id"`
	StatusType      int64     `json:"status_type"`
	StatusCompleted bool      `json:"status_completed"`
	Stamp           time.Time `json:"stamp"`
}

func (q *Queries) SetWorkflowStatus(ctx context.Context, arg SetWorkflowStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, setWorkflowStatus,
		arg.PatientID,
		arg.UserID,
		arg.StatusType,
		arg.StatusCompleted,
		arg.Stamp,
	)
}
