// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: zipcodes.sql

package dbgen

import (
	"context"
)

const cityStateZipByCity = `-- name: CityStateZipByCity :many
SELECT id, created_at, updated_at, deleted_at, zip, city, state, latitude, longitude, timezone, dst, country FROM zipcodes
WHERE city LIKE CONCAT('%', ?, '%')
LIMIT 20
`

// Zipcode picklist: search by city only
func (q *Queries) CityStateZipByCity(ctx context.Context, city interface{}) ([]Zipcode, error) {
	rows, err := q.db.QueryContext(ctx, cityStateZipByCity, city)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Zipcode
	for rows.Next() {
		var i Zipcode
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Zip,
			&i.City,
			&i.State,
			&i.Latitude,
			&i.Longitude,
			&i.Timezone,
			&i.Dst,
			&i.Country,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cityStateZipByStateCity = `-- name: CityStateZipByStateCity :many
SELECT id, created_at, updated_at, deleted_at, zip, city, state, latitude, longitude, timezone, dst, country FROM zipcodes
WHERE state = UPPER(?)
  AND city LIKE CONCAT('%', ?, '%')
LIMIT 20
`

type CityStateZipByStateCityParams struct {
	State string      `json:"state"`
	City  interface{} `json:"city"`
}

// Zipcode picklist: search by state and city
func (q *Queries) CityStateZipByStateCity(ctx context.Context, arg CityStateZipByStateCityParams) ([]Zipcode, error) {
	rows, err := q.db.QueryContext(ctx, cityStateZipByStateCity, arg.State, arg.City)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Zipcode
	for rows.Next() {
		var i Zipcode
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Zip,
			&i.City,
			&i.State,
			&i.Latitude,
			&i.Longitude,
			&i.Timezone,
			&i.Dst,
			&i.Country,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cityStateZipByZip = `-- name: CityStateZipByZip :many
SELECT id, created_at, updated_at, deleted_at, zip, city, state, latitude, longitude, timezone, dst, country FROM zipcodes
WHERE zip LIKE CONCAT('%', ?, '%')
LIMIT 20
`

// Zipcode picklist: search by zip code
func (q *Queries) CityStateZipByZip(ctx context.Context, zip interface{}) ([]Zipcode, error) {
	rows, err := q.db.QueryContext(ctx, cityStateZipByZip, zip)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Zipcode
	for rows.Next() {
		var i Zipcode
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Zip,
			&i.City,
			&i.State,
			&i.Latitude,
			&i.Longitude,
			&i.Timezone,
			&i.Dst,
			&i.Country,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
